### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by perseval** [tanersener/flutter-ffmpeg#100]
**Description**
I add flutter_ffmpeg as a dependency in my pubspec.yaml file like this :
`  flutter_ffmpeg: 
    git: 
      url: git://github.com/tanersener/flutter-ffmpeg.git 
      ref: v0.2.1
      path: packages/flutter_ffmpeg_video_lts`

build when i run  this is logs i get. 

**Logs**
https://ghostbin.co/paste/xprgg

**Environment**
`[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale fr-FR)
    • Flutter version 1.12.13+hotfix.5 at /Users/verone/development/flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/verone/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 • 76EA3FB5-C9FE-486E-B8E0-2CCB41B352DE • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!`

**Comment by tanersener** [comment]
`v0.2.1` is pretty old, why don't you try the latest version?

**Comment by perseval** [comment]
i get this when i run pub get : 
`
Could not find a file named "packages/flutter_ffmpeg_video_lts/pubspec.yaml" in git://github.com/tanersener/flutter-ffmpeg.git e77bd52188952eb04491799df35c3120744e85c7.
pub get failed (1; Could not find a file named "packages/flutter_ffmpeg_video_lts/pubspec.yaml" in git://github.com/tanersener/flutter-ffmpeg.git e77bd52188952eb04491799df35c3120744e85c7.)
`

**Comment by tanersener** [comment]
The mechanism you use to install `video-lts` package is deprecated. Please see [2.1 Packages](https://github.com/tanersener/flutter-ffmpeg#21-packages) section and update your project according to instructions given there.

**Comment by perseval** [comment]
Thanks it's work :)

**Comment by perseval** [comment]
Thanks it's work :)
