### ISSUE TITLE
Converting video  with smallest quality loss

### ISSUE THREAD

**Issue by perseval** [tanersener/flutter-ffmpeg#101]
This package is awesome !!! 

But i try to convert video, quality is not so good, i want to know if it's possible to  uses  arguments like -crf or -preset.

**Comment by tanersener** [comment]
Which codec do you use in your command? `x264` gives best output most of the time.

**Comment by perseval** [comment]
to get x264 i try to install package `https-gpl-lts` by replacing this in Plugin Pods section :

> plugin_pods = parse_KV_file('../.flutter-plugins')
> plugin_pods.each do |name, path|
>   symlink = File.join('.symlinks', 'plugins', name)
>   File.symlink(path, symlink)
>   if name == 'flutter_ffmpeg'
>       pod name+'/https-gpl-lts', :path => File.join(symlink, 'ios')
>   else
>       pod name, :path => File.join(symlink, 'ios')
>   end
> end

i get : 

> [!] Invalid `Podfile` file: no implicit conversion of Hash into String.
>      #  from /***/ios/Podfile:69
>      #  -------------------------------------------
>      #  plugin_pods.each do |name, path|
>      >    symlink = File.join('.symlinks', 'plugins', name)
>      #    File.symlink(path, symlink)
>      #  -------------------------------------------
> 

:(

**Comment by tanersener** [comment]
`Podfile` format defined by `flutter` changed over time. `README` includes instructions for the latest format defined by `flutter`. If you're using an older version you may experience this kind of errors.

README or https://github.com/tanersener/react-native-ffmpeg-test/commits/master/default/ios/Podfile file I use in my test applications include previous instructions used to define a package. Can you take a look at them?

**Comment by perseval** [comment]
It's work, i put this on plugin pods section : 

>   # Plugin Pods
>   plugin_pods = parse_KV_file('../.flutter-plugins')
>   plugin_pods.map { |p|
>     symlink = File.join('.symlinks', 'plugins', p[:name])
>     File.symlink(p[:path], symlink)
>     if p[:name] == 'flutter_ffmpeg'
>       pod p[:name]+'/https-gpl-lts', :path => File.join(symlink, 'ios')
>     else
>     pod p[:name], :path => File.join(symlink, 'ios')
>     end
>   }

x264 video is better 👍  ... but processing is slower :(

**Comment by tanersener** [comment]
You can use different options like the ones you've asked in your first post to increase the speed. https://trac.ffmpeg.org/wiki/Encode/H.264 guide explains all of them.

**Comment by perseval** [comment]
Good ! Thanks a lot

Le dim. 26 janv. 2020 à 15:04, Taner Sener <notifications@github.com> a
écrit :
