### ISSUE TITLE
pod install went wrong

### ISSUE THREAD

**Issue by sisychen** [tanersener/flutter-ffmpeg#102]
The error information is:
[!] CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/a/2/mobile-ffmpeg-full/4.3.1/mobile-ffmpeg-full.podspec.json, error: Connection reset by peer - SSL_connect

**Comment by tanersener** [comment]
It looks like a cocoapods issue. Did you try adding another pods to your project, another one which is not in your cocoapods cache?
