### ISSUE TITLE
Not able to add LTS dependency from version v0.2.7 onwards

### ISSUE THREAD

**Issue by v4-adi** [tanersener/flutter-ffmpeg#106]
**Description**
 v0.2.7 and above gives an error when I try to add the LTS dependency of the library.

dependencies:
  flutter:
    sdk: flutter
  flutter_ffmpeg:
    git:
      url: git://github.com/tanersener/flutter-ffmpeg.git
      ref: v0.2.10
      path: packages/flutter_ffmpeg_https_lts

**Logs**
Could not find a file named "packages/flutter_ffmpeg_https_lts/pubspec.yaml" in git://github.com/tanersener/flutter-ffmpeg.git c785bf139539a34d0e800958b7850c26354047d7.
pub get failed (1; Could not find a file named "packages/flutter_ffmpeg_https_lts/pubspec.yaml" in git://github.com/tanersener/flutter-ffmpeg.git c785bf139539a34d0e800958b7850c26354047d7.)

**Comment by tanersener** [comment]
The mechanism you use to install `https-lts` package is deprecated. Please see [2.1 Packages](https://github.com/tanersener/flutter-ffmpeg#21-packages) section and update your project according to instructions given there.

**Comment by v4-adi** [comment]
Worked for me. Thanks.
