### ISSUE TITLE
Option to include only Mp3 encoder-decoder

### ISSUE THREAD

**Issue by v4-adi** [tanersener/flutter-ffmpeg#108]
**Description**
I enabled the audio-lts package but it increased the size by around 10 MB. Is there a way I can only include MP3 encoder-decoder since I only intend to work with these codecs?

**Comment by tanersener** [comment]
Unfortunately, no. You need to build your own version of parent [mobile-ffmpeg](https://github.com/tanersener/mobile-ffmpeg) project to do that.

**Comment by v4-adi** [comment]
> Unfortunately, no. You need to build your own version of parent [mobile-ffmpeg](https://github.com/tanersener/mobile-ffmpeg) project to do that.

Can you help me with that? Is there some script or guidelines which I can follow to do it?

**Comment by tanersener** [comment]
README of `mobile-ffmpeg` is pretty detailed. You can find all the information there. If you receive any errors you can create an issue and ask for help.

I don't have an official guide about using your own `mobile-ffmpeg` library in `flutter_ffmpeg` but it is not too difficult. You just need to override `mobile-ffmpeg` coming from `flutter_ffmpeg` with your own version.
