### ISSUE TITLE
No implementation found for method executeFFmpegWithArguments on channel flutter_ffmpeg

### ISSUE THREAD

**Issue by BedRockGx** [tanersener/flutter-ffmpeg#111]
Hello, I got this error when using the plug-in. When I check your code, the problem is:

binaryMessenger.send(
      name,
      codec.encodeMethodCall(MethodCall(method, arguments)),
   );

I didn't get the value. How can I solve the problem
Thanks!

**Comment by remcova** [comment]
I got the same problem, did you solve this?
