### ISSUE TITLE
Unrecognized option 'preset'.

### ISSUE THREAD

**Issue by jonataslaw** [tanersener/flutter-ffmpeg#112]
Hi, first of all, thanks for this wonderful library.
I am trying to do a reverse loop effect (similar to instagram) and the decoding is very slow (about 15 seconds for a 1 second video file on a high end device).
I tried changing the preset to ultrafast and I'm having this error:

```
Error:
E/mobile-ffmpeg( 7261): Unrecognized option 'preset'.
E/mobile-ffmpeg( 7261): Error splitting the argument list:
E/mobile-ffmpeg( 7261): Option not found
D/flutter-ffmpeg( 7261): FFmpeg exited with rc: 1
```

I am using this command to get the intended one. If I remove the "preset" the command works, but it is very slow. I'm sorry if this is a silly error, I'm not so familiar with FFMPEG, and if you can help me with this error, or with a way to use reverse quickly in mp4 files (camera recording format) I would appreciate it.

```dart
 var cmd4 =
        "-y -i $path -c:v libx264 -preset ultrafast -crf 22 -filter_complex [0]reverse[r];[0][r]concat,loop=2:50 $outPath";
    int rc = await _flutterFFmpeg.execute(cmd4);
```

**Comment by jonataslaw** [comment]
My bad, add flutterFFmpegPackage  = "min-gpl-lts" on build.gradle fix

**Comment by kapilkarda** [comment]
@jonataslaw this should add on root build.gradle or app level build.gredle
