### ISSUE TITLE
Metadata AttachedPicture of mp3 file

### ISSUE THREAD

**Issue by Nailik** [tanersener/flutter-ffmpeg#116]
Hello,

this is more like a feature request or question.
Is there a way to retreive the preview image of a sound file (like mp3) via `getMediaInformation `?

**Comment by tanersener** [comment]
I don't plan to implement that kind of functions in this library. 

I think it is already possible to achieve it by running a command. Did you try googling about it? [This thread](https://stackoverflow.com/questions/13592709/retrieve-album-art-using-ffmpeg) has a few examples you can try.

**Comment by Nailik** [comment]
No didn't see this. But this example directly writes the cover to a file, afterwards i would need to read that file - that would cost "a lot" time (when you scan houndreds or thousands of song).
The reason i would have to read each file is, that i use crc to get a hash of the image to not store covers of songs multiple times.
Right now i use the dart tags package for this.

**Comment by tanersener** [comment]
I understand what you want to achieve. Unfortunately, this library can't help you about that.
