### ISSUE TITLE
ffmpeg-Zmq not available

### ISSUE THREAD

**Issue by foxtailmega** [tanersener/flutter-ffmpeg#117]
**Description**
I am using full-gpl-lts version of flutter ffmpeg but zmq is not available

**Expected behavior**
I wish to change the __```filter_complex```__ parameters at runtime, now this behaviour is only possible by __```sendcmd```__ or __```zmq```__ in ffmpeg, but for zmq, flutter-ffmpeg has to be built with that zmq enabled. Is there any other way to change filter_complex parameters at runtime ?

**Current behavior**
zmq command not available

**Comment by tanersener** [comment]
Building `ffmpeg` with all optional features and external libraries is not one of the objectives of this project. So, some of the optional components are not enabled. `zmq` is one them.

I don't know how to change filter_complex parameters at runtime. Can you please ask this question to [ffmpeg-user](https://ffmpeg.org/mailman/listinfo/ffmpeg-user) mailing list.

**Comment by foxtailmega** [comment]
thanks for reply. So is there any way i can build flutter-ffmpeg for both ios and android by enabling that zmq library ? I really need that zmq in my flutter-ffmpeg for my app to work. Is there any guide or is there any way you can help adding zmq to flutter-ffmpeg ?

**Comment by tanersener** [comment]
You need to build the parent project, [mobile-ffmpeg](https://github.com/tanersener/mobile-ffmpeg), to achieve that. It also doesn't have support for `zmq` but it supports a lot of external libraries. You can copy the build scripts of those libraries to compile `libzmq` and enable `zmq` in `ffmpeg`.
