### ISSUE TITLE
Checking if Flutter ffmpeg is compressing

### ISSUE THREAD

**Issue by febg11** [tanersener/flutter-ffmpeg#124]
Hi,

Is there anyway of checking whether ffmpeg is compressing? Or do I have to manually keep track of it

Thanks

**Comment by tanersener** [comment]
Your question is not clear. Please add some more details and also consider filling issue template fields.

**Comment by febg11** [comment]
Sorry. I have been calling    _ffmpeg.cancel(); in a dispose method to stop a video compressing if the user leave the page. The problem is if i keep switching to and from that page the app evenutually crashes.

Is there a method to check whether ffmpeg is executing something to ensure that this method is only called in the dispose if ffmpeg is actually doing something.

e.g. Something like 

``` 
if(_ffmpeg.isExectuting(){
   _ffmpeg.cancel();
}

**Comment by tanersener** [comment]
`flutter_ffmpeg` can run multiple commands at the same time. It is hard to know which command you're referring to. Why don't you implement it yourself.

```
Future<int> executeFFmpeg(String command) async {
    return await _flutterFFmpeg.execute(command);
}

executeFFmpeg("command")
    .then((rc) => ffmpegExecuting = false);
```

**Comment by febg11** [comment]
oh i didnt realise it can run multiple commands at the same time. 

Does 
```
 _ffmpeg.cancel();
```
Just cancel all of them? or can you cancel individual ones by assigning id's or something.

**Comment by tanersener** [comment]
No ids right now. All of them will be cancelled.

**Comment by febg11** [comment]
Ah ok thanks for answering my questions 😊
