### ISSUE TITLE
Can ffmpeg be used to encode for video conferencing?

### ISSUE THREAD

**Issue by rgb1380** [tanersener/flutter-ffmpeg#125]
**Description**
Is it possible to use this plug-in to encode the camera video stream in real-time by passing a stream of bytes as opposed to passing a file?

**Comment by tanersener** [comment]
Yes you can. Refer to https://trac.ffmpeg.org/wiki/StreamingGuide for some the options you can use.

**Comment by rgb1380** [comment]
Can you please elaborate how this plug-in can be used to receive the mobile device's camera video feed and turn into a stream of encoded frames? I do not want to stream it to a server directly but be able to access the encoded stream on the same mobile device (the aim is then to use the encoded stream for P2P streaming).
Thanks.
