### ISSUE TITLE
Unable to find mobile-ffmpeg-https (= 4.3.1)

### ISSUE THREAD

**Issue by Xiaojuanmao** [tanersener/flutter-ffmpeg#127]
**Description**
I am try to use `flutter_ffmpeg: ^0.2.10`

I got below error after i run 'pod install'
<img width="545" alt="截屏2020-04-16 下午3 07 18" src="https://user-images.githubusercontent.com/9401858/79425625-8b0f3980-7ff4-11ea-8594-1647378dfd64.png">

Podfile:
![截屏2020-04-16 下午3 07 43](https://user-images.githubusercontent.com/9401858/79425795-cf023e80-7ff4-11ea-9709-1fd34caa84cd.png)

**Comment by tanersener** [comment]
You need to update pods repo. The error message tells you how you to do it. Did you try running one of those two commands?

**Comment by Xiaojuanmao** [comment]
yes, i have tried several times and read the README three times. 
just now, i found the pod source had been set, but without 'https://github.com/CocoaPods/Specs.git', so the pod find 'mobile-ffmpeg-https' in other private repo. 

i am fetching the cocoapods now..... :) problem resolved, thank you so much!
