### ISSUE TITLE
executeWithArguments fail when put filter_complex parameter

### ISSUE THREAD

**Issue by pratakr** [tanersener/flutter-ffmpeg#130]
**Description**
execute command "ffmpeg -i video.mp4 -c:v copy -filter_complex "amovie=music.mov [l] ; amovie=vc2.mp3 [r] ; [l] [r] amerge" -f mp4 -ac  2 output.mp4
" work on PC version but fail on mobile lib.  

var arguments = ["-i",music,"-c:v","-filter_complex","amovie=$music [l];amovie=$vocol [r];[l] [r] amerge","-ac","2","$dir/output.mp4"]; 
 _flutterFFmpeg.executeWithArguments(arguments).then((rc) => print("FFmpeg process exited with rc $rc"));
error "Unable to find a suitable output format for 'amovie=/data/u..." 
the error look like I pass invalid parameter after -filter_complex
How can I fix it?

**Logs**
https://ghostbin.co/paste/8avoq

**Environment**
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at c:\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\prata\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\prata\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\prata\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Redmi Note 7 • bfb4ae6 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by tanersener** [comment]
You have unnecessary space characters inside your filters.
1- Remove unnecessary space characters inside your filter_complex block
2- Wrap your filter_complex block using double quotes
