### ISSUE TITLE
Stream from Camera file

### ISSUE THREAD

**Issue by ollydixon** [tanersener/flutter-ffmpeg#132]
We're trying to stream from a local camera file real time, we're so close but it's not working, it just repeats the first few seconds.

We are streaming to a URL, it does actually stream. It's streaming to a live RTMP endpoint.

Using the Flutter camera plugin so far we have:

```
Future<void> _streamUpload() async {

    final cameraFilePath = await _createCameraFilePath();
    final cameraFile = File(cameraFilePath);
    await cameraFile.delete();
    await _cameraController.startVideoRecording(cameraFile.path);

    // Wait so here is some content.
    await Future.delayed(Duration(seconds: 2));

    _flutterFFmpeg?.cancel();
    _flutterFFmpeg = FlutterFFmpeg();
    final FlutterFFmpegConfig flutterFFmpegConfig = new FlutterFFmpegConfig();

    final url = widget.rtmpStreamUrl + '/' + widget.streamKey;
    _flutterFFmpeg.execute("-threads 2 -re -fflags +genpts -stream_loop -1 -i $cameraFilePath -b:v 2000 -r 24 -g 48 -f flv $url");

    // Log Stream stats
    void statisticsCallback(int time, int size, double bitrate, double speed, int videoFrameNumber, double videoQuality, double videoFps) {
      print("Statistics: time: $time, size: $size, bitrate: $bitrate, speed: $speed, videoFrameNumber: $videoFrameNumber, videoQuality: $videoQuality, videoFps: $videoFps");
    }

    flutterFFmpegConfig.enableStatisticsCallback(statisticsCallback);
}
```

We get the error ``moov atom not found``, how can we ignore the moov?

**Comment by tanersener** [comment]
`moov atom` error is received when `mpeg-4` header is not found in a stream. Can you try specifying input format with `-f` option? Also, I don't understand why you need to use `-stream_loop -1` for a streaming input. Did you try without using it?

**Comment by ollydixon** [comment]
@tanersener yes I tried a few options including the ones you mentioned, no luck. I restored to creating a native plugin using UiKitView. I was trying to use the Camera plugin to cross-platform streaming, it worked if the file was saved, then the stream started but not while the file was being written too.

**Comment by tanersener** [comment]
It is not an easy case to solve. What is the format of `cameraFilePath` and `url`? Do you have extension in them?

**Comment by ollydixon** [comment]
They are different formats on different platforms but generally, FFMPEG has been good at decoding them after the camera finishes writing. The URL is a typical RTMP endpoint.

**Comment by tanersener** [comment]
`moov atom` is written to the end of the file by default. Did you try to move `atom` to the beginning or use an empty `atom` using the `movflags` options defined in [ffmpeg documentation](https://ffmpeg.org/ffmpeg-formats.html#mov_002c-mp4_002c-ismv)?

Also, can you provide logs/console output about this case? It can help me to understand formats of input/output streams.

**Comment by ollydixon** [comment]
Yes, but I don't know if I got the correct command to move the moov.

**Comment by ollydixon** [comment]
Still looking into a solution for this, will post back if we find one.

**Comment by ollydixon** [comment]
@tanersener we decided to go with this https://github.com/pinkfish/flutter_rtmppublisher, had to make some fixes but works really nice.

It would be epic if this function was built into the Flutter camera.
