### ISSUE TITLE
[IOS] Crash fullter_ijkplayer as soon as i add flutter-ffmpeg

### ISSUE THREAD

**Issue by neckaros** [tanersener/flutter-ffmpeg#137]
**Description**
A project with  just ijkplayer works well
 ` flutter_ijkplayer: ^0.3.5+1`
but as soon as i add flutter_ffmpeg i have a crash
  flutter_ffmpeg: ^0.2.10
but it works well on android

**Expected behavior**
No crash and i can modify video thanks to flutter_ffmpeg and play them thanks to ijkplayer in the same app

**Current behavior**
The application start but as soon as i hit start it crash

**Screenshots**
![ffmpeg error](https://user-images.githubusercontent.com/7789770/81512366-599e3b00-9320-11ea-9a28-297b3b774052.jpg)

**Logs**
in ff_read (see screenshot)
 0x10432bd7b <+580>:  movl   %eax, %r15d  
ff_read (33): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

**Environment**
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-FR)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.45.0)
[✓] Connected device (1 available)

**Step to reproduce**
flutter sample app
add both dependencies
```
  flutter_ijkplayer: ^0.3.5+1
  flutter_ffmpeg: ^0.2.10
```
modify podfile and xcode project to target platform 10 to be compatible with flutter_ffmpeg
platform :ios, '10.0'

main.dart:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_ijkplayer/flutter_ijkplayer.dart';

void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // is not restarted.
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  IjkMediaController controller = IjkMediaController();

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: Container(
        width: MediaQuery.of(context).size.width,
        height: 400,
        child: ListView(
          children: <Widget>[
            buildIjkPlayer(),
          ]
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.play_arrow),
        onPressed: () async {
          await controller.setNetworkDataSource(
              'http://mirror.bigbuckbunny.de/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov',
              autoPlay: true);
          print("set data source success");
          // controller.playOrPause();
        },
      ),
    );
  }

  Widget buildIjkPlayer() {
    return Container(
      // height: 400,
      child: IjkPlayer(
        mediaController: controller,
      ),
    );
  }
}
```

Launch ios simulator
flutter run
click on the play FAB

**Comment by tanersener** [comment]
Both packages come with their own `ffmpeg` implementations. This means you have two `ffmpeg` libraries which clash with each other. There is not an easy solution for this. I explained the situation in the parent project's wiki page [Using Multiple FFmpeg Implementations In The Same iOS Application](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application).

**Comment by neckaros** [comment]
Thanks for this quick reply! Not easy indeed especially with flutter.

I tried to look into Xcode Other linked files but could only find -framework Flutter
And we don’t have a Pods-<Your App>.debug.xcconfig at least in flutter default app

**Comment by at-namnguyen2** [comment]
> Both packages come with their own `ffmpeg` implementations. This means you have two `ffmpeg` libraries which clash with each other. There is not an easy solution for this. I explained the situation in the parent project's wiki page [Using Multiple FFmpeg Implementations In The Same iOS Application](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application).

I have the same issue. So i try follow this doc. it worked well if i call ffmpeg, but with flutter_ijkplayer still crash when call it. Do you have another solution for this. Thanks!
