### ISSUE TITLE
_flutterFFmpegConfig.setFontDirectory not working properly until app is restarted

### ISSUE THREAD

**Issue by foxtailmega** [tanersener/flutter-ffmpeg#138]
currently i just updated my flutter to version 1.17.0 and i am trying to hardcode .ass subtitle to video. I am using custom fonts

```dart
_flutterFFmpeg.cancel();
_flutterFFmpegConfig.resetStatistics();
var _fontMap = {"Pacifico": "Pacifico_Regular.ttf", "Roboto": "Roboto-Regular.ttf"};
_flutterFFmpegConfig.setFontDirectory("/storage/emulated/0/Download", _fontMap);

await _flutterFFmpeg.execute("-y -i $videopath -filter_complex \"[0:v]subtitles=$subtitlePath\" -c:v libx264 -c:a copy -crf 27 -tune zerolatency -preset ultrafast -f mp4 $outputVideoPath");
```

Now this above code works fine and embeds subtitle to video everytime i restart my app and run it again. But if i try to re-run this piece of code once it has been executed and without restarting the app, then code runs well, but subtitle is not embedded into video.

**Comment by foxtailmega** [comment]
I just found out that instead of that regular font name map, if i leave it empty, it works fine.
for example:- instead of
```dart
var _fontMap = {"Pacifico": "Pacifico_Regular.ttf", "Roboto": "Roboto-Regular.ttf"};
```

if i use
```dart
var _fontMap = {"": ""};
_flutterFFmpegConfig.setFontDirectory("/storage/emulated/0/Download", _fontMap);
```
Now it works perfectly fine. But i am not sure why name maps doesn't work if its not empty.

**Comment by Amerr** [comment]
For me it fails at this point, couldn't figure out tried both mehtods. No luck

**Comment by foxtailmega** [comment]
@Amerr make sure you put all fonts in a folder. For example i put all fonts in a `fonts` directory in `Download` folder which has path like 

> "/storage/emulated/0/Download/fonts"

 and then use this command
```dart
var _fontMap = {"": ""};
_flutterFFmpegConfig.setFontDirectory("/storage/emulated/0/Download/fonts", _fontMap);
```

I have no idea why named font mapping doesn't work, but surely empty map works for me. Try it.
