### ISSUE TITLE
Installing additional external ffmpeg libraries

### ISSUE THREAD

**Issue by andreaalessandretti** [tanersener/flutter-ffmpeg#141]
Is there a way to add/modify the plugging to support an additional external ffmpeg library? Thanks!

**Comment by tanersener** [comment]
This project uses [mobile-ffmpeg](https://github.com/tanersener/mobile-ffmpeg) library. You can build your own version of `MobileFFmpeg` using scripts provided there and use generated libraries alongside with `flutter_ffmpeg`.

**Comment by ariefwijaya** [comment]
@tanersener  from this section [https://github.com/tanersener/mobile-ffmpeg#52-build-scripts](https://github.com/tanersener/mobile-ffmpeg#52-build-scripts) , right ?

**Comment by tanersener** [comment]
@ariefwijaya Yes
