### ISSUE TITLE
FlutterFFmpegConfig.setFontDirectory not working properly

### ISSUE THREAD

**Issue by Amerr** [tanersener/flutter-ffmpeg#144]
**Description**
FlutterFFmpegConfig.setFontDirectory is failing silently i dono the reason.
These parameters passed to function
```
{fontDirectory: /var/mobile/Containers/Data/Application/3C8BEA15-1C07-4EAB-9DC3-F75C743EA36D/Documents/wizhapp/fonts/, fontNameMap: {robotoItalic: Roboto-Italic.ttf, robotoMedium: Roboto-Medium.ttf, robotoMediumItalic: Roboto-MediumItalic.ttf, robotoBlackItalic: Roboto-BlackItalic.ttf}}
```

i tried both null 
```
{fontDirectory: /var/mobile/Containers/Data/Application/3C8BEA15-1C07-4EAB-9DC3-F75C743EA36D/Documents/wizhapp/fonts/}
```

**Expected behavior**
It needs to execute properly

**Current behavior**
It stalled the loading process 

**Environment**
✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/amerrnathmurugan/flutter
    • Framework revision e0c63cd35e (4 weeks ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/amerrnathmurugan/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    •  amerr iPhone • 00008020-001324282291002E • ios • iOS 13.4.1

• No issues found!
**Other**
I checked other threads but it's not helpful

**Comment by tanersener** [comment]
I don't understand what is the current behaviour? Your first sentence says that it is `failing silently. They you say that `It stalled the loading process`. Also, I don't understand what you mean by `loading` process. 

Please give more details like does it crash your application, or print something to console.

**Comment by Amerr** [comment]
@tanersener  Sorry the issues are resolved.
I was trying to add an `await` to resolve this promise. 
This made the application to stall. We should update the README.md
Don't
```
await _flutterFFmpegConfig.setFontDirectory(fontDir, this.fontmap);
```

DO
```
_flutterFFmpegConfig.setFontDirectory(fontDir, this.fontmap);
```

Is it the intended way or did I misunderstood the code? 
Thanks, for the quick response

**Comment by tanersener** [comment]
`setFontDirectory` is an async function, it returns `Future<void>`. So general `async` rules apply here. If you want to wait the function to complete then you need to use `await`. If you don't want to wait then you don't. 

Example test application includes a working example for this function. Please take a loot at it, [here](https://github.com/tanersener/flutter-ffmpeg/blob/master/example/lib/flutter_ffmpeg_example.dart#L458).
