### ISSUE TITLE
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.

### ISSUE THREAD

**Issue by DoubleTime** [tanersener/flutter-ffmpeg#147]
**Description**
Trying to load mp4 from https url and got this error message.
> "https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled."

```
String _url = "some https audio here";
final FlutterFFprobe _flutterFFprobe = new FlutterFFprobe();
_flutterFFprobe.getMediaInformation(_url).then((info) => print(info));
```

How do I enable the audio to load over https?
Searching on the web seem like I have to add --enable-openssl, not sure how to implement it, please show some guidance. 

Thanks.

**Expected behavior**
Obtain media information

**Current behavior**
Error message:
`https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
`
**Environment**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/eric/Sites/flutter
    • Framework revision f139b11009 (9 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/eric/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/eric/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0
```

**Comment by cristoj** [comment]
Me too, somebody can help us??

Thanks!!!

**Comment by tanersener** [comment]
`https` protocol is not included in all `flutter_ffmpeg` packages. It is enabled by `gnutls` external library and only packages that include `gnutls` supports it. Refer to README to see those packages.

If you're using a package which has `gnutls` inside then there should be another problem. Console output/logs are needed to analyse that.

**Comment by icelija** [comment]
I ran into this issue too and lost couple of hours today trying to find the cause for this, and what bothered me was that in the example of flutter-ffmpeg library I tried to get media information of the online video and there it worked but with the same configuration in my project it gave me the error from above.

I am not sure what was the exact reason, but I had in my project https://pub.dev/packages/flutter_vlc_player and when I removed it, it miraculously started working.

If anyone has the idea about why one library messes the other and how to make them work together, feel free to share it 😄
