### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by techyrajeev** [tanersener/flutter-ffmpeg#148]
**Description**
Ios release build is failing. Debug mode is running fine
**Expected behavior**
Proper release build should be generated.

**Current behavior**
Getting this error while building
`Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MobileFFprobe", referenced from:
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
  "_OBJC_CLASS_$_MobileFFmpeg", referenced from:
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
  "_OBJC_CLASS_$_MobileFFmpegConfig", referenced from:
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
  "_OBJC_CLASS_$_ArchDetect", referenced from:
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Environment**
  **flutter_ffmpeg: ^0.2.10**

Flutter doctor output
```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.8)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.45.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Other**
```
 # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    if name == 'flutter_ffmpeg'
        pod name+'/full', :path => File.join(symlink, 'ios')
    else
        pod name, :path => File.join(symlink, 'ios')
    end
  end```

**Comment by NikolaMijovic93** [comment]
I had the same issue. You need to use one of the LTS versions specified in your podfile. The clean version don't include the armv7 architecture.
For example use mobile-ffmpeg-full', '4.3.1.LTS'

**Comment by Amerr** [comment]
I am also facing the same issue, I don't know how to resolve it using LTS.

I just changed the podfile
```
system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    if name == 'flutter_ffmpeg'
        pod name+'/https-lts', :path => File.join(symlink, 'ios')
    else
        pod name, :path => File.join(symlink, 'ios')
    end
  end
```

but same issue

**Comment by kbanta11** [comment]
Also having the same issue using the audio package, blocking from building for release or creating archive:

```
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    if name == 'flutter_ffmpeg'
            pod name+'/audio', :path => File.join(symlink, 'ios')
        else
            pod name, :path => File.join(symlink, 'ios')
        end
  end
```

**Comment by tanersener** [comment]
Sometimes, after upgrading `flutter`, you may start receiving this error. Running `flutter clean` and building the project again fixes the issue.

Remember that `Main` releases don't support 32 bit architectures like `armv7`, `armv7s` and `i386`. Because they are not supported by `Xcode` since `v11`.

- If you're using an up to date Xcode version, you shouldn't be receiving this error. If you get it, clean your project and rebuild it again
- If you want to support 32 bit architectures, you need to use an `Xcode` version lower than `v11` and install one of the `LTS` packages of `flutter_ffmpeg`. `LTS` packages support 32 bit architectures. See #45, #57, #62

**Comment by jpiabrantes** [comment]
I am getting this error after doing `flutter clean`. I am using Xcode v11.6.

**Comment by balajiks-dev** [comment]
Same error here too. Its Frustrating while on Production day
