### ISSUE TITLE
LGPL 3.0 Question

### ISSUE THREAD

**Issue by plam50** [tanersener/flutter-ffmpeg#149]
Hi 

I have a project that cannot be licenced as GPL3 so I cannot use H264 encoder. I have managed to accomplish what I need to do using the mpeg4 encoder which is used in your example 

```
_flutterFFmpeg.execute("-i file1.mp4 -c:v mpeg4 file2.mp4").then((rc) => print("FFmpeg process exited with rc $rc"));
```

I cant see mpeg4 on your table however it seems to work without any of the special packages e.g. min-gpl.

is this ok to be used on my app for commercial use as I read this on the ffmpeg website 

"Q: Is it perfectly alright to incorporate the whole FFmpeg core into my own commercial product?
A: You might have a problem here. There have been cases where companies have used FFmpeg in their products. These companies found out that once you start trying to make money from patented technologies, the owners of the patents will come after their licensing fees. Notably, MPEG LA is vigilant and diligent about collecting for MPEG-related technologies."

I am not certain what ffmeg core is and whether i am using it by using ffmpeg flutter with no special packages 

kind regards 
P lam

**Comment by tanersener** [comment]
It doesn't matter which package you use. `mpeg4` encoder is enabled in all packages.

Unfortunately that statement about using `ffmpeg` in commercial binds you too. Because `flutter_ffmpeg` is an `ffmpeg` port and it has `ffmpeg` in its core.

**Comment by plam50** [comment]
Thank you for replying so quickly 

I understand what you are saying and have since looked online and seen you can use the Cisco ````openh264```` library 
https://github.com/cisco/openh264

with ````ffmpeg```` to avoid the gpl licencing. I have also read for this to work the user must download the binaries from Cisco themselves meaning i cannot bundle them with the application (correct me if im wrong). 

How can I do this with ````flutter_ffmpeg````?

Furthermore I was also reading this 
https://www.openh264.org/faq.html

and saw that IOS is unable to install packages after installation of the app but apple provides the video toolbox library (````h264_videotoolbox````). Is the ````h264_videotoolbox````  BSD licence and can i use this for ios and use the ````openh264```` for android, meaning this way they will both be using BSD licenses?

I would really appreciate it if you can help me a bit more as I feel out of my depth with this.

Thanks 
P lam

**Comment by tanersener** [comment]
You can use `h264_videotoolbox` in iOS. However, `flutter_ffmpeg` does not include `openh264`. You need to build parent `mobile-ffmpeg` library with `openh264` on `Android`.

This library is licensed under LGPL or GPL depending on the package you're using. So, you need to read the terms of those two licenses. Also, if you distribute your application in a country where patent laws accept that software is patentable then you are obligated to pay MPEG LA licenses too. It is a complex topic. I'm working on writing some extra documentation about it but it will take time.

**Comment by plam50** [comment]
Hi tanersener,

Im sorry but I have four more questions. 

1. On the Cisco openh264 it states that the license is BSD https://github.com/cisco/openh264#license If I pull the binaries at run time from Cisco’s website.

And this can also been read here https://www.openh264.org/faq.html 
Q: If I use the source code in my product, and then distribute that product on my own, will Cisco cover the MPEG LA licensing fees which I'd otherwise have to pay?
A: No. Cisco is only covering the licensing fees for its own binary module, and products or projects that utilize it must download it at the time the product or project is installed on the user's computer or device. Cisco will not be liable for any licensing fees incurred by other parties.

And in this video https://vimeo.com/79578794

Doesn’t these mean I won’t have to pay MPEG LA licenses as they will be covered by Cisco? 
You said that I need to build the parent mobile-ffmpeg library but If I do this won’t I be distributing the binary and therefore be liable?  

I want to try get a dynamic link to the library working that will be installed at runtime rather than building it into my apk. I don’t really understand how the “For Android Builds section works” and how to do this with flutter.Is the dynamic download from Cisco’s website an option flutter_ffmpeg library could offer so many users could use it? 

2. Futhermore as the h264_videotoolbox is a hardware encoder is this not covered by apple? Meaning there will be no MPEG LA licence costs if I use openh264 for android and the   h264_videotoolbox for iOS. 

3. I understand that ffmpeg is licensed under LGPL/GPL, is there a method of using the openh264 library while still only using the min version of FFMpeg flutter. This way I will can run a video encode ffmpeg command that uses either h264_videotoolbox or openh264 and still only need to meet the LGPL requirements. 

4. I have spent quite a long time trying to run the openh264 with ffmpeg on my Mac to test the behaviour with running 2pass commands. I still haven’t managed to get this to run, does the open264 support 2 pass? 

You are correct this is very complicated and I want to make sure I do everything properly. 

Kind regards,
P lam

**Comment by febg11** [comment]
@plam50 This is a really good question. I would also like to know of an easy method to use Cisco's Openh264 library with flutter ffmpeg but still retain the LGPL licence and remove any chance of royalty fees. I cannot answer your questions but maybe @tanersener can.

Hopefully there is a method of doing this... I imagine downloading the binary files in dart would be quite easy, but i am not sure how would we go about installing the cisco package on Android and ensure Flutter FFmpeg can use it.

Also is it true that using  the h264_videotoolbox means there are no royalties that have to be paid to MPEG LA?

**Comment by tanersener** [comment]
@plam50

First of all I'm not a lawyer. I'm telling you what I read from the licenses and the relevant documentation. 

1) As far as I know, it is not possible to download a binary from internet and load it in your application on both Android and iOS. However. if you know a method to do this, then you don't need to pay MPEG LA licensing fees. Cisco will cover them for you.

2) `h264_videotoolbox` is covered by iOS.

3) This is explained in the `LICENSE` section.

  `  This project is licensed under the LGPL v3.0. However, if installation is customized to use a 
  package with -gpl postfix (min-gpl, https-gpl, full-gpl) then FlutterFFmpeg is subject to the GPL 
  v3.0 license.`

4) I don't know.

**Comment by febg11** [comment]
Do you know if there is an android hardware encoder that is similar to the apple h264_videotoolbox?

**Comment by alexcohn** [comment]
> Do you know if there is an android hardware encoder that is similar to the apple h264_videotoolbox?

Sure, the MediaCodec (enabled in all **flutter-ffmpeg** packages) can encode H264.

**Comment by febg11** [comment]
> > Do you know if there is an android hardware encoder that is similar to the apple h264_videotoolbox?
> 
> Sure, the MediaCodec (enabled in all **flutter-ffmpeg** packages) can encode H264.

How would I use that with ffmpeg and will this be using any MPEG LA patented code.

**Comment by alexcohn** [comment]
Sure, the hardware encoder is subject to all rules of patent licensing, but luckily, the app developer is not expected to pay the fee: it was included in the price of the device bought by the end user.

**Comment by febg11** [comment]
Oh that's great news. Does the name of the hardware encoder change on each device/manufacturer then?
What do I have to specify as the -c:v Param to use this in ffmpeg.

**Comment by tanersener** [comment]
@alexcohn MediaCodec is only a decoder, see https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by alexcohn** [comment]
> @alexcohn MediaCodec is only a decoder, see https://trac.ffmpeg.org/wiki/HWAccelIntro

Well, that's something worth fixing 😉

**Comment by febg11** [comment]
:(
