### ISSUE TITLE
No such filter: 'eq'

### ISSUE THREAD

**Issue by amansrivastava17** [tanersener/flutter-ffmpeg#152]
**eq filter not supported**
I am trying to execute ffmpeg command `-i input.mp4 -vf eq=gamma=1.5:saturation=1.3 -c:a copy output.mp4` but getting this error.

`I/mobile-ffmpeg(22027): Press [q] to stop, [?] for help
E/mobile-ffmpeg(22027): [AVFilterGraph @ 0x70f2e0dd40] No such filter: 'eq'
E/mobile-ffmpeg(22027): Error reinitializing filters!
E/mobile-ffmpeg(22027): Failed to inject frame into filter network: Invalid argument
E/mobile-ffmpeg(22027): Error while processing the decoded data for stream #0:0`

I found nothing related to this problem on the internet.
Let me know if I am doing something wrong because the same command is working for Linux ffmpeg.

**Comment by tanersener** [comment]
`eq` is one of the `GPL` licensed filters, see [GPL Licensed Filters](https://github.com/tanersener/mobile-ffmpeg/wiki/GPL-Licensed-Filters). You need to install one of the `GPL` licensed packages to use it.

**Comment by amansrivastava17** [comment]
@tanersener thank you for the response :)
Also, how can I install flutter package with GPL license?

**Comment by tanersener** [comment]
https://github.com/tanersener/flutter-ffmpeg#213-package-names lists all `flutter_ffmpeg` packages. Packages ending with `-gpl` are licensed under GPL.
