### ISSUE TITLE
Is there a way to set environment variables for FFmpeg?

### ISSUE THREAD

**Issue by ozburo** [tanersener/flutter-ffmpeg#157]
FFmpeg accepts a `http_proxy` env var so that you don't have to declare it in your args.

Is there a way to set this in Android or Flutter that FFmpeg can find and use?

Perhaps this could be an additional API feature?

Thanks for a great project! 👍

**Comment by tanersener** [comment]
`Android` has an internal `setNativeEnvironmentVariable` function but is not open to public. I can update its visibility in the next release though.

**Comment by ozburo** [comment]
Thanks for looking into it! I think it would be a great addition if possible 👍

**Comment by tanersener** [comment]
Fix released in `v0.3.0`.
