### ISSUE TITLE
provide brief overview of each package

### ISSUE THREAD

**Issue by bsutton** [tanersener/flutter-ffmpeg#159]
The doco mentions a no. of optional packages.

It would be useful if the list includes a brief overview of what features each package provided and a link to the API doco for that package.

As someone looking for codec conversion and not being familiar with ffmpeg the doco doesn't give any guidance on where to start.

**Comment by ozburo** [comment]
FFmpeg has all the documentation regarding codecs and packages I would suggest going there for full info.

There wouldn't be must benefit of reproducing that here IMO as this package implies users have at least a working knowledge of FFmpeg.

**Comment by bsutton** [comment]
My experience suggests otherwise.
I found flutter-ffmpeg when looking through pub.dev for a package that does transcoding.
I had no prior knowledge of ffmpeg except that I was vaguely aware that there was a program called ffmpeg.
I doubt that I will be the only potential user to have the same experience.

I'm not suggesting that you duplicate the ffmpeg doco, only that you provides some links to relevant parts so that someone like myself at least gets a running start at using the library.

**Comment by ozburo** [comment]
@bsutton well, if you've never heard of ffmpeg and just came across it looking for a transcoding solution, I would say you'd be in the minority, but then again I'm probably showing my ignorance assuming everyone has heard of "FFmpeg".

By all means add as much doco as you want. Maybe a link to the ffmpeg.org website and documentation page(s) would suffice, something like firebase_ffmpeg and others do.
