### ISSUE TITLE
[Question] Any way to easy remove unneeded native libraries from the build?

### ISSUE THREAD

**Issue by PiotrWpl** [tanersener/flutter-ffmpeg#16]
Hi,

once again great plugin! It helps me a lot with project I'm currently working on. Thanks!

_[I did my tests only on Android, I'm not sure how to measure iOS - but maybe You will have some ideas how to solve this problem on iOS too?]_

I have a question related to the output app size. Adding this plugin to project increasing my app size a lot. I did some tests (using apk analyzer) and turns out that this plugin adds a lot of native libraries:
![native_libraries](https://user-images.githubusercontent.com/1515300/55409470-61f34680-5562-11e9-8cd5-6fbfd7b238c9.png)

As You can see, some of them are really heavy, and when we sum up them they are more than 60% of app size. I'm using current Github development branch as a plugin source.

Is there any easy way to remove unneeded native libraries? For example, in my app I just want to merge a couple of jpg files into one .mp4 file (using mpeg4 codec) and add background music to it from .aac file.
I guess that I'm using only a small part of those libraries.
If there is no option to configure this plugin, can You help me with detection which library is for what? There is an option to exclude files from Gradle build file https://stackoverflow.com/a/37110505/2372631 so maybe I will be able to use this as a workaround (if only I will know what is safe to exclude).

Greetings!

**Comment by tanersener** [comment]
Thanks for this question. You are very right about your analysis. Unfortunately excluding some of the native libraries is not the right approach. 

Can you try using min package using instructions in [packages](https://github.com/tanersener/flutter-ffmpeg#21-packages) section?

**Comment by PiotrWpl** [comment]
Hi @tanersener 
Thanks for such a fast response, and a good advice.

I tried with (as You proposed):
>   flutter_ffmpeg:
>     git:
>       url: git://github.com/tanersener/flutter-ffmpeg.git
>       ref: development
>       path: packages/flutter_ffmpeg_min_lts

And results for Android are a little bit better (about 6MB overall, including about 2MB for armeabi-v7a which is probably the most popular architecture - so it's an improvement):
![native-libraries2](https://user-images.githubusercontent.com/1515300/55456152-9ad4ff00-55e6-11e9-8d6f-91a9d0f07e30.png)
I also can confirm, that min package is working fine on my android device, and iOS simulator (I couldn't do test on iOS device).

Any more ideas what I can do decrease app size further?

**Comment by tanersener** [comment]
Well, you need to build parent `mobile-ffmpeg` library yourself to decrease app size further. It is not an easy process but you will be able to disable all unused components in native libraries.

**Comment by PiotrWpl** [comment]
Hmm, understand.
You mean that I should follow this steps -> https://github.com/tanersener/mobile-ffmpeg#5-building
From what I understand:
`./android.sh --lts`
is an equivalent of **flutter_ffmpeg_min_lts**, right ?
Based on wiki in yours project, what I can do more with custom build is only disable "armv7-neon" architecture (that will be probably the biggest gain in decreasing app size). Or maybe I missed something more?

And when it comes to "armv7-neon", do You have any idea how big decrease (in %) in speed may be in my case when I will remove it?

**Comment by tanersener** [comment]
> Hmm, understand.
> You mean that I should follow this steps -> https://github.com/tanersener/mobile-ffmpeg#5-building
> From what I understand:
> `./android.sh --lts`
> is an equivalent of **flutter_ffmpeg_min_lts**, right ?

Yes, exactly.

> Based on wiki in yours project, what I can do more with custom build is only disable "armv7-neon" architecture (that will be probably the biggest gain in decreasing app size). Or maybe I missed something more?
> 

It is possible to decrease native library size further by customizing this line in [ffmpeg build script for Android](https://github.com/tanersener/mobile-ffmpeg/blob/master/build/android-ffmpeg.sh#L320). This `configure` line defines all enabled/disabled ffmpeg components. You need to disable everything with `--disable-everything` flag and enabled only components necessary for your application.

> And when it comes to "armv7-neon", do You have any idea how big decrease (in %) in speed may be in my case when I will remove it?

I've made some tests a while ago but I don't remember the numbers. Performance difference between `arm-v7a` and `arm-v7a-neon` depends on the codecs used in your application. You can test it yourself and decide to exclude it or not.

**Comment by PiotrWpl** [comment]
Thanks for everything! I will do some tests with that this week, and let You know what I manage to achieve.
Have a good day!
