### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by aytunch** [tanersener/flutter-ffmpeg#160]
Hi Taner, thanks for this great package. I think that this project uses native SDKs behind the scenes. I wonder how would performance of transcoding or other tools would be effected if dart:ffi were to be used with rust or c++ instead? Do you think there would be a gain or would it be neglibigle? Also would this make it more cross platform(thinking of desktops) I see that some people are having problems for real time encoding of video, that's why I wanted to ask about this in the first place.

**Comment by tanersener** [comment]
Hi Aytunc, native libraries of this plugin comes from [mobile-ffmpeg](https://github.com/tanersener/mobile-ffmpeg). They're already compiled from c/c++. So, in terms of transcoding performance nothing will change.

However, in the platform specific parts of the plugin, especially on Android, there are some areas that can be improved using `dart:ffi`. `flutter_ffmpeg` calls the Java API of the `mobile-ffmpeg` and I believe it can be skipped using `dart:ffi`. There will be some improvements there in terms of API call speed. But I don't think they'll be noticeable. 

I must also add that a lot of effort is needed to integrate into `mobile-ffmpeg`'s native Android API using `dart:ffi`. It is a two way integration, there are some asynchronous native calls made by `mobile-ffmpeg` library that won't be easy to implement.

**Comment by aytunch** [comment]
Thanks a lot for the detailed answer. I was hoping that the performance difference would be negligible like you said. Take care.

**Comment by PiotrWpl** [comment]
@tanersener 
Will You give a chance for dart:ffi now when Flutter 2.0 and Dart 2.12 were released?
Based on my understanding this package https://pub.dev/packages/ffigen can be used to generate bindings between C/C++ and Dart.

**Comment by tanersener** [comment]
Sorry, this item doesn't have a high priority in my `todo` list. 

I know that there is a performance difference between running a command in `flutter_ffmpeg` and running it natively. `flutter_ffmpeg` is clearly slower. But for me, the question here is, where does that performance hit come from? This must be investigated first. Then we can talk about a solution, `dart:ffi`, `isolates` or something else. Unfortunately, I won't be able to investigate this soon. Though I can help if some of you guys want to work on this.
