### ISSUE TITLE
Can we add watermark in video?

### ISSUE THREAD

**Issue by parth22** [tanersener/flutter-ffmpeg#164]
I look into your [package](https://pub.dev/packages/flutter_ffmpeg) to add watermark in video. But can't find anything about this functionality so, Could you please guide me for this or plugin didn't contain this functionality?
Thank You.

**Comment by YazeedAlKhalaf** [comment]
@parth22 I guess that you didn’t get the way this package works. It executes real ffmpeg commands. So you have to have basic understanding of ffmpeg commands.

A quick google search will show you how to add watermark to video using ffmpeg.
