### ISSUE TITLE
To get metadata continued from radio stream

### ISSUE THREAD

**Issue by silver-cap** [tanersener/flutter-ffmpeg#166]
Thanks for the great package.
I am making a radio app and I want to get song title from the metadata.
Of course, I can get the data very first time by using getMediaInformation method. 
But from next song, I can't get the data. I've tried getMediaInformation(URL).asStream().listen() but it didn't work. 
If there is a way to get information when metadata changed, pls let me know. 
Thanks.

**Comment by RogyBear** [comment]
Was there any solution to this issue? I am currently running into the same problem and cannot find the necessary information in the docs.
