### ISSUE TITLE
How to identify ffmpeg compression command execution ?

### ISSUE THREAD

**Issue by krunaldoshi2019** [tanersener/flutter-ffmpeg#170]
I have use case in Video sharing app like

Record multiple videos > ffmpeg compression fire on each video > ffmpeg run it in stack 

How can we identify which command is running and for which file it's running ? 

Below method only giving this info which can not uniquely identify the video 
statisticsCallback(int time, int size, double bitrate, double speed,
      int videoFrameNumber, double videoQuality, double videoFps)

Please help
Thanks in advance.

**Comment by tanersener** [comment]
Implemented in the `development` branch.

**Comment by tanersener** [comment]
Released in `v0.3.0`.
