### ISSUE TITLE
How to execute multiple commands at multiple threads

### ISSUE THREAD

**Issue by ahndwon** [tanersener/flutter-ffmpeg#172]
**Description**
I am trying to watermark several videos at same time.
I achieved this in Android with multi-threading by using tanersener's ffmpeg.
But in Flutter looks like it's not working.
I tried futures and isolates.
Does flutter-ffmpeg not support multi-threads?

**Expected behavior**
Execute commands successfully on multi-threads.

**Current behavior**
I am executing ffmpeg command by async method in a for each loop.
The app crashes whenever the for loop is run.

I also tried isolates, but same result.

The command is adding a png file to a video file to a corner

My command is 
`"-i $videoUrl -i $imageUrl -filter_complex overlay=0:0 -crf 20 -y $outputUrl" `

Errors like bottom occurs. There are more errors are below on the Logs ghostbin
`
Error while decoding stream #0:1: Invalid data found when processing input
flutter: Invalid NAL unit size (449653942 > 6468).
flutter: Error splitting the input into NAL units
flutter: Sample rate index in program config element does not match the sample rate index configured by the container.
`

**Logs**
https://ghostbin.co/paste/9g8kn

**Environment**
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.2 19C57, locale en-KR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

**Comment by ahndwon** [comment]
Updated template

**Comment by tanersener** [comment]
Your logs show decoding errors about your input file. 

- Is that file a valid one? Did you try to run the same command using the same file on another device? It can be a desktop computer as well.
- Do you have the same error when you run just one command?

**Comment by ahndwon** [comment]
Same files works well when I run with just one command.
I found out that It behaves differently on different devices.
When run on Iphone 11 pro max, it just logs errors as above and all commands stop.
But on Iphone 7, last command seems to execute successfully, but other commands fail with errors.
Same files, commands were used.
Could the OS versions affect the commands?

**Comment by tanersener** [comment]
No, but different devices have different cameras. If you're using videos recorded by camera as input then your results won't be the same.

**Comment by tanersener** [comment]
Your first post tells that you're using the beta channel. Did you try this case in stable channel as well?
