### ISSUE TITLE
Water Mark

### ISSUE THREAD

**Issue by chinu999** [tanersener/flutter-ffmpeg#173]
**Description**

I am tying to add water mark to a video.

i saw all the watermark issue but i did not get how to add image from asset or from internet

i used this ffmpeg code =ffmpeg -i 1.mkv -i boxicon.png -filter_complex "overlay=20:20" $ou.mp4

Code:
AssetImage img=AssetImage("assets/images/boxicon.png");
                                    or
    Image imag=Image.asset("assets/images/boxicon.png");
                                    or
    String image = "https://images.vexels.com/media/users/3/156051/isolated/preview/72094c4492bc9c334266dc3049c15252-flat-flower-icon-flower-by-vexels.png";

 var arguments = ["-i $saveVideoFile" "-i$img" "-filter_complex ""overlay=10:10" "$WatermarkVideoFile"];
                                                                                          or
     var arguments = ["-i $saveVideoFile" "-i$imag" "-filter_complex ""overlay=10:10" "$WatermarkVideoFile"];
                                                                                           or
 var arguments = ["-i $saveVideoFile" "-i$image" "-filter_complex ""overlay=10:10" "$WatermarkVideoFile"];

   _flutterFFmpeg.executeWithArguments(
          arguments)

**Comment by chinu999** [comment]
**Logs**
D/flutter-ffmpeg(18165): Running FFmpeg with arguments: [-i /data/user/0/com.techworks.bitbox/app_flutter/Movies/flutter_test/1595343008993.mp4-ihttps://images.vexels.com/media/users/3/156051/isolated/preview/72094c4492bc9c334266dc3049c15252-flat-flower-icon-flower-by-vexels.png-filter_complex overlay=10:10/data/user/0/com.techworks.bitbox/app_flutter/Movies/flutter_test/1595343008994.mp4].
D/flutter-ffmpeg(18165): FFmpeg exited with rc: 1
I/mobile-ffmpeg(18165): ffmpeg version git-2020-01-25-fd11dd500
I/mobile-ffmpeg(18165):  Copyright (c) 2000-2020 the FFmpeg developers
I/mobile-ffmpeg(18165): 
I/mobile-ffmpeg(18165):   built with Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
I/mobile-ffmpeg(18165):   configuration: --cross-prefix=i686-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-x86/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=i686 --cpu=i686 --cc=i686-linux-android24-clang --cxx=i686-linux-android24-clang++ --target-os=android --disable-neon --disable-asm --disable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --di
I/mobile-ffmpeg(18165):   libavutil      56. 38.100 / 56. 38.100
I/mobile-ffmpeg(18165):   libavcodec     58. 65.102 / 58. 65.102
I/mobile-ffmpeg(18165):   libavformat    58. 35.101 / 58. 35.101
I/mobile-ffmpeg(18165):   libavdevice    58.  9.103 / 58.  9.103
I/mobile-ffmpeg(18165):   libavfilter     7. 70.101 /  7. 70.101
I/mobile-ffmpeg(18165):   libswscale      5.  6.100 /  5.  6.100
I/mobile-ffmpeg(18165):   libswresample   3.  6.100 /  3.  6.100
E/mobile-ffmpeg(18165): Unrecognized option 'i /data/user/0/com.techworks.bitbox/app_flutter/Movies/flutter_test/1595343008993.mp4-ihttps://images.vexels.com/media/users/3/156051/isolated/preview/72094c4492bc9c334266dc3049c15252-flat-flower-icon-flower-by-vexels.png-filter_complex overlay=10:10/data/user/0/com.techworks.bitbox/app_flutter/Movies/flutter_test/1595343008994.mp4'.
E/mobile-ffmpeg(18165): Error splitting the argument list:

**Comment by chinu999** [comment]
Can yo please help me i don't know how to add water mark 

i used this code 

  _flutterFFmpeg.execute(
          "-i $saveVideoFile -i $image -filter_complex overlay=10:10 $WatermarkVideoFile")

and 

this one-
var arguments = ["-i $saveVideoFile" "-i$image" "-filter_complex ""overlay=10:10" "$WatermarkVideoFile"];

_flutterFFmpeg.executeWithArguments(
arguments)

please can you tell me what is the proper code to get image from asset and video from dir.

**Comment by tanersener** [comment]
Your command string is wrong. Error message returned explains what is wrong there. Please take look at `example` test application to see how a command can be split.

**Comment by chinu999** [comment]
ya ya 
i tried this code:- -i $saveVideoFile -i $image -filter_complex overlay=10:10 -codec:a copy $WatermarkVideoFile"
and eveything worked.

Thank you for replying.

**Comment by jtkeyva** [comment]
@chinu999 can you please paste the exact function you got working?
thx
