### ISSUE TITLE
Apk size

### ISSUE THREAD

**Issue by chinu999** [tanersener/flutter-ffmpeg#177]
**Description**

i used every possible way to compress the app but after adding ffmpeg my app size increased to more 42 mb.
is their any to compress it.
And using full-gpl it goes to 70 md.--

**Expected behavior**
I mean is there any way when i need ffmpeg it will download from internet to my app.
and
how this flutter packages use ffmpeg but size does not increase(flutter_video_compress 0.3.7+8/video_trimmer 0.2.6)

**Current behavior**
i only use ffmpeg

  flutter_ffmpeg: ^0.2.10

**Screenshots**

**Logs**
√ Built build\app\outputs\apk\release\app-release.apk (49.3MB).

**Environment**
Flutter doctor output

**Other**

**Comment by tanersener** [comment]
`flutter_ffmpeg` comes with different packages. Each package has a different size. They're listed in the `README`. Try to use a smaller package.

**Comment by chinu999** [comment]
actually i am using water marking,audio extraction,video and audio merge  so i need full-gpl. i tried min-gpl no worked at all,i tried audio i cant use water mark,i tried video and full but i cant extract audio from video.So is their any way after downloading the app from appstore. Full-gul will download  automatically to app.Any link to download and add it.

**Comment by tanersener** [comment]
Yeah, you can build a custom `mobile-ffmpeg` package and use it with `flutter_ffmpeg`. [mobile-ffmpeg](https://github.com/tanersener/mobile-ffmpeg) has build scripts you can use. Read the README and wiki pages. All information you need is there.

**Comment by chinu999** [comment]
Thank you so much for replying so fast and quick.
But does that mean I have to create a ffmpeg plugin from Java. I have some experience with Java but due to errors and complexity I move to kotlin and then flutter.Does it support kotlin or is there any way to use flutter to create plugin.

**Comment by tanersener** [comment]
Another plugin? As I told you in my previous answer, you can use `mobile-ffmpeg` with `flutter_ffmpeg`. `flutter_ffmpeg` calls `mobile-ffmpeg` for you. `flutter_ffmpeg` already comes with a published `mobile-ffmpeg` package. By building your own `mobile-ffmpeg` package, you'll replace that version with yours.

**Comment by chinu999** [comment]
Thank you so much it helped me a lot.
