### ISSUE TITLE
Path to use for .acv curve files

### ISSUE THREAD

**Issue by alsiPanda** [tanersener/flutter-ffmpeg#179]
In my flutter app, I am using a photoshop curve file to create a bunch of filter effects. For input and output file, I am giving the full absolute path. Do I also need to use the absolute path for the curve file ? The curve files are stored in filter folder, in the the same folder as the dart file with ffmpeg code. The argument is like this : `'-i "$oldpath" -vf "curves=psfile=filter/filter_name.acv" -c:a copy $newpath'`. My mobile-ffmpeg output however shows `No such file or directory` right after libswresample. And as expected, no file is created at newpath.

Is the relative path the source of problem then ?

**Comment by alsiPanda** [comment]
I have tried using path_provider but didn't work out in the end. I hardly understand the path and file structure. So what is the best place to store all the .acv file and how to get the absolute path ? Any help is much appreciated.

**Comment by tanersener** [comment]
You can take a look at the test application under the `example` folder. It has examples about getting full paths.

**Comment by alsiPanda** [comment]
@tanersener  thanks for that, it really helped me out. Although, after executing the ffmpeg command, the app crashes towards the end. Not sure if it is due to the low ram in virtual device.

**Comment by tanersener** [comment]
Applications usually print the reason of the crash on exit. It can give an idea about the reason.
