### ISSUE TITLE
[Feature Request] Adding a stream returning function for getting progress in realtime

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [tanersener/flutter-ffmpeg#180]
I would like to propose adding a progress feature. It might be implemented using a stream returning function.

**Comment by tanersener** [comment]
You can already use `statisticsCallback` to get progress. Why we need another function for this?

**Comment by YazeedAlKhalaf** [comment]
I am a newbie to FFmpeg. My question is how to get the progress of the current process/command into the UI in Flutter.
I am making a video splitting app so what I need to do is display the progress for the user so that he doesn't think the app is not working. So does `statisticsCallback` give a percentage from 100 of what is done?

Thanks in advance

**Comment by YazeedAlKhalaf** [comment]
If you have time can you give an example of a function that uses `statisticsCallback` and gives a percentage?

**Comment by tanersener** [comment]
You don't need an example for that. `statisticsCallback` gives you processed time and processed frame number. You can calculate the percentage yourself. Divide time to total duration.

Note that `flutter_ffmpeg` or `ffmpeg` can't give you the total duration while execution is still ongoing.

**Comment by YazeedAlKhalaf** [comment]
Ah okay, no problem I have duration. It is a video trimmer for social media so duration for each part is determined beforehand. Like for example, Facebook 20 seconds.

So `$timeInSeconds / $durationInSeconds` = `$percentage`

**Comment by YazeedAlKhalaf** [comment]
Thank you so much. I have tried it and have implemented it in my app. Now I have a percentage for each process.
```dart
double percentage = ((time / 1000) / totalDurationOfVideoBeingWorkedOn) * 100;
```

**Comment by YazeedAlKhalaf** [comment]
I feel this is safe to close
