### ISSUE TITLE
Using external FFmpeg library with this package

### ISSUE THREAD

**Issue by sbis04** [tanersener/flutter-ffmpeg#181]
**Description**
I want to use an external library with **FFmpeg** called [Frei0r](https://www.dyne.org/software/frei0r/).

Is there a way to integrate an external library with `flutter-ffmpeg` directly?

**Comment by tanersener** [comment]
Unfortunately, no. It is not one of the supported libraries.

**Comment by sbis04** [comment]
But, I came across [this](https://proandroiddev.com/android-ndk-how-to-integrate-pre-built-libraries-in-case-of-the-ffmpeg-7ff24551a0f) article for integrating pre-built libraries with **FFmpeg**.

So, is it possible to integrate the library **Frei0r** in that way?

**Comment by tanersener** [comment]
What is your plan? Did you try to build `frei0r` before, or do you have prebuilt `frei0r` libraries built by someone else?

Having prebuilt binaries or building them is one part of the problem. After that, `ffmpeg` has to be rebuild with `frei0r` enabled. You can't just put `frei0r` libraries inside a folder and expect `ffmpeg` to use those libraries.

**Comment by sbis04** [comment]
Okay, so, currently there is no Flutter package for applying **video filter** in an app directly. So, some people requested me to create one like that. But, defining video filters is a lot of time-consuming and complex process. And when there is already a library compatible with **FFmpeg** called `frei0r` (consisting of different video filters), it doesn't make any sense creating it again. 

That's why I just wanted a way of using this library with **FFmpeg**. 

The library `frei0r` is available on **GitHub** here: https://github.com/dyne/frei0r

This is an article showing some of the video effects that can be created using `frei0r` with **FFmpeg**: https://yalantis.com/blog/experiments-with-ffmpeg-filters-and-frei0r-plugin-effects/

As you are very familiar with **FFmpeg**, you are the best person I can reach.

I have already created one Flutter package for trimming videos, called [video_trimmer](https://pub.dev/packages/video_trimmer) using **FFmpeg**. And, I am willing to work on some more packages in the field of video editing in Flutter, as there are very limited packages in this range.

**Comment by tanersener** [comment]
I've tried to integrate `frei0r` before. And I still remember the issues I had about it. So, I don't plan to support it in this project. It is not an easy task for me.

But you're free to clone the project and work on it. 

If I were you, I'd try using the [curves filter](https://ffmpeg.org/ffmpeg-filters.html#curves-1). It is pretty good. I don't remember if it supports videos though.

**Comment by sbis04** [comment]
Okay, I will try out the `curves` filter. 

Earlier, I had been using the [colorchannelmixer](https://ffmpeg.org/ffmpeg-filters.html#colorchannelmixer) to create some simple color effects.

**Comment by sbis04** [comment]
@tanersener I see that you have assigned yourself to this issue. So, are you working on any implementation of this?

**Comment by tanersener** [comment]
Nope

**Comment by sbis04** [comment]
Okay, I am closing this issue.
