### ISSUE TITLE
Unknown input format: 'avfoundation'

### ISSUE THREAD

**Issue by moeiscool** [tanersener/flutter-ffmpeg#182]
**Description**
ffmepg fails to get the camera on iOS. Fails with
```
flutter: Unknown input format: 'avfoundation'
```

This the command I'm using
```
flutter: -loglevel warning -probesize 1000 -analyzeduration 1000 -r 30 -video_size hd720 -f avfoundation -pixel_format bgr0 -i 0:0 -f mpegts -an -vf fps=30 -q:v 1 udp://localhost:1337 -an -vf fps=30 -f segment -segment_atclocktime 1 -reset_timestamps 1 -strftime 1 -segment_list /var/mobile/Containers/Data/Application/AC05D503-663C-4EF9-B46B-DC130A32905E/Library/Caches/mf_pipe_1 -segment_time 120.0 /var/mobile/Containers/Data/Application/AC05D503-663C-4EF9-B46B-DC130A32905E/Documents/Recordings/%Y-%m-%d %H:%M:%S.mp4
```

The set outputs work fine on Android. I am able to provided the camera to those outputs without any issue. iOS just fails and says it doesn't know what `avfoundation` is.

**Expected behavior**
Operate the same as android. Capture camera stream and encode for selected outputs.

**Current behavior**
The set outputs work fine on Android. I am able to provided the camera to those outputs without any issue. iOS just fails and says it doesn't know what `avfoundation` is.

**Screenshots**
N/A

**Logs**
```
flutter: Unknown input format: 'avfoundation'
```
```
flutter: -loglevel warning -probesize 1000 -analyzeduration 1000 -r 30 -video_size hd720 -f avfoundation -pixel_format bgr0 -i 0:0 -f mpegts -an -vf fps=30 -q:v 1 udp://localhost:1337 -an -vf fps=30 -f segment -segment_atclocktime 1 -reset_timestamps 1 -strftime 1 -segment_list /var/mobile/Containers/Data/Application/AC05D503-663C-4EF9-B46B-DC130A32905E/Library/Caches/mf_pipe_1 -segment_time 120.0 /var/mobile/Containers/Data/Application/AC05D503-663C-4EF9-B46B-DC130A32905E/Documents/Recordings/%Y-%m-%d %H:%M:%S.mp4
```

**Environment**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.4 19E287, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

**Other**

**Comment by tanersener** [comment]
Can you please add version and package information for `flutter_ffmpeg`? Also startup logs of your application please? Startup logs show which `mobile-ffmpeg` version (parent project of `flutter_ffmpeg`)  is used in your application.

Additionally, running `-devices` can be helpful. This command shows enabled input and output devices.
