### ISSUE TITLE
LGPL 3.0 Question

### ISSUE THREAD

**Issue by violet-dev** [tanersener/flutter-ffmpeg#184]
**Description**

**Expected behavior**

**Current behavior**

**Screenshots**

**Logs**

**Environment**

**Other**

Thank you for creating this library!
I have a question in using this library.
I know your flutter library (not ffmpeg) is distributed under the LGPLv3.0.
If so, if I use this library, I must provide the object files under the lgpl license. 
However, Flutter does not create any object file on build time.
How do I comply with the lgpl license?
Since you are the author of this library, I would love to hear from you.
Are users of this library not required to publish any output?

**Comment by tanersener** [comment]
I created [this page](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-MobileFFmpeg-in-Commercial-Applications) for the parent `mobile-ffmpeg` project. It is valid for `flutter_ffmpeg` as well. 

Can't answer the specifics about flutter. I'm not sure what `flutter` generates for your app or for a package/plugin.

**Comment by violet-dev** [comment]
Thanks for the answer. If there are any problems in the future, I will ask again
