### ISSUE TITLE
CocoaPods could not find compatible versions for pod

### ISSUE THREAD

**Issue by rubikon-movement** [tanersener/flutter-ffmpeg#187]
I am unable to run flutter-ffmpeg. I created a new project using flutter 1.17.5 and flutter-ffmpeg 0.2.10 and i encountered an issue. In Podfile i added the following code : 
```
if name == 'flutter_ffmpeg'
    pod name+'/app', :path => File.join(symlink, 'ios')
else
     pod name, :path => File.join(symlink, 'ios')
```
but i don't know what is really the package name and where can i find it. I added the name of the flutter project i catch an error: 
```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "flutter_ffmpeg/app":
  In Podfile:
    flutter_ffmpeg/app (from `.symlinks/plugins/flutter_ffmpeg/ios`)

None of your spec sources contain a spec satisfying the dependency: `flutter_ffmpeg/app (from `.symlinks/plugins/flutter_ffmpeg/ios`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Please can somebody tell me where can i find the `'<package name>'`,that i need to put here : 
`pod name+'/<package name>', :path => File.join(symlink, 'ios')`

**Comment by tanersener** [comment]
See [2.1.3 Package Names](https://github.com/tanersener/flutter-ffmpeg#213-package-names) in README.
