### ISSUE TITLE
Convert animated widget into video output

### ISSUE THREAD

**Issue by rafazold** [tanersener/flutter-ffmpeg#189]
**Description**
I have a Stack widget that includes a static background and multiple animated elements. 
I want to record the whole animation and run it in a loop (each loop is about 5 seconds).

Is there a way of achieving this with ffmpeg? If so, how should I input the widget animation?

**Comment by ueman** [comment]
You can try to capture your widget every x milliseconds with the help of a RepaintBoundary. When the animation completed you can combine those images to a video or gif.

**Comment by rafazold** [comment]
I tried something similar without success. I tried to make a screenshot of the whole screen and then render them as a video, the issue was that some of my elements are .gif @ 25fps and that required me a large amount of screenshots and overcomplicated the project.

My new attempt is to replicate the widget by setting each element and it's location and size in ffmpeg using -filter_complex which seems achievable, but I'm not being able to open a .gif from the assets folder.

I read issue #31  and tried the suggestion there for prepareAssets method and assetPath, but it seems like it will work only for images. Do you have a suggestion for a .gif?

**Comment by ueman** [comment]
As per Readme assets won't work. You'll need to copy those first into your app storage folder and use those copied files with ffmpeg.

**Comment by rafazold** [comment]
I was able to render a video using the assets as APNG instead of Gif (gif was rendering the transparent background with color when copied).

I have another issue though:

When I'm trying to add sound to my video (recorded with the client), but I'm not able to reach a lossless quality. 
I'm running executeWithArguments and this are my arguments:

```
arguments = [
        "-i",
        "$bgPath",
        "-stream_loop",
        "-1",
        "-r",
        "25",
        "-i",
        "$animatedPath",
        "-filter_complex",
        "[0]transpose=dir=1:passthrough=portrait[bgTranspose], 
         [bgTranspose]scale=w=${makeIntEven(bgW)}:h=${makeIntEven(bgH)}[bg], 
         [1]fps=25[fps],[fps]scale=w=${makeIntEven(eyW)}:h=${makeIntEven(eyH)}[eyes], 
         [bg][eyes]overlay=$xOff:$yOff",
        "-i",
        "$audioUrl",
        "-c:v",
        "libx264",
        "-t",
        "15",
        "-pix_fmt",
        "yuv420p",
        "-preset",
        "veryslow",
        "-crf",
        "17",
        "-shortest",
        "$videoUrl"
      ];
```

Thank you

**Comment by iamsandeepsk** [comment]
any solution?
