### ISSUE TITLE
Can not use list_devices?

### ISSUE THREAD

**Issue by OhYee** [tanersener/flutter-ffmpeg#19]
**Description**
It seems that flutter-ffmpeg can not use `ffmpeg -list_devices true` command.

**Expected behavior**
List the device, such as android camera.

**Current behavior**
`Unrecognized option 'list_devices'`

**Environment**
Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.14393], locale zh-CN
Android SDK version 28.0.3

**Other**
Some way to publish rtmp stream from camera?

**Comment by tanersener** [comment]
> It seems that flutter-ffmpeg can not use `ffmpeg -list_devices true` command.

I don't think so. Can you show me a documentation reference which says `-list_devices true` can be used to list devices? `-devices` is the option to see list available devices, including `android_camera`. 

> **Other**
> Some way to publish rtmp stream from camera?

I don't have an example personally but there are some issues in [react-native-ffmpeg](https://github.com/tanersener/react-native-ffmpeg) project with example commands inside. You can check them with [this](https://github.com/tanersener/react-native-ffmpeg/issues?utf8=%E2%9C%93&q=is%3Aissue+rtmp+) link.

**Comment by OhYee** [comment]
Lots of blogs say `ffmpeg -list_devices true -f dshow -i dummy` can list the cameras and microphones on pc. 
Maybe I misunderstand this command.


And I have publish the video stream successfully from the android camera using
`-f android_camera -camera_index 0 -video_size hd1080 -framerate 60 -input_queue_size 1000 -i discarded -c:v libx264 -r 30 -preset ultrafast -f flv rtmp://10.240.169.163:1935/a/b`

Now, I have another question: **how to preview the camera data**(put the video data to the screen? ).

Maybe deploying a rtmp server on the phone and using video player (such as ijkplayer) to play it will work, but this must be so foolish, any better idea?

**Comment by tanersener** [comment]
> Lots of blogs say `ffmpeg -list_devices true -f dshow -i dummy` can list the cameras and microphones on pc.
> Maybe I misunderstand this command.

As explained in [ffmpeg devices](https://ffmpeg.org/ffmpeg-devices.html) documentation, `-list_devices true` is a supplementary option for input device providers. You need to have one of `-f avfoundation`, `-f decklink`, `-f dshow` or `-f openal` with `-list_devices true`. Unfortunately, none of them supports Android. So `-list_devices true` won't help you much.

> Now, I have another question: **how to preview the camera data**(put the video data to the screen? ).
> 
> Maybe deploying a rtmp server on the phone and using video player (such as ijkplayer) to play it will work, but this must be so foolish, any better idea?

This library does not provide a mechanism to preview data. You can use other player libraries like `ijkplayer` to do that but I didn't try previewing, so I don't have a recommendation.

**Comment by OhYee** [comment]
Thanks for your help. I will try to use `ijkplayer`
