### ISSUE TITLE
java.io.IOException: Cannot run program "/data/user/0/com.godatu.dance/files/ffmpeg": error=13, Permission denied

### ISSUE THREAD

**Issue by lalit3102** [tanersener/flutter-ffmpeg#191]
**Description**
Getting error  while compressing video

**Expected behavior**
It should compress video and return the compressed video

**Current behavior**
app get close after i choose a video to compress

**Logs**
https://ghostbin.co/paste/2a5tc.

**Environment**
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.20.2 at C:\Users\Admin\Desktop\flutter-dart\flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • vivo 1904 (mobile) • DYSGCEBYEMLJSKHY • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by tanersener** [comment]
I don't see anything about `flutter_ffmpeg` in your logs. Please open your issue under the right project.
