### ISSUE TITLE
Live preview of the filter/audio or sticker adding to the video

### ISSUE THREAD

**Issue by VovaMedvediev** [tanersener/flutter-ffmpeg#199]
Hi!

I'd like to apply filter on a recorded video. 

So my steps are:
1. Record a video using camera.
2. Show recorded video on the screen.
3. Apply filter to this video. I don't want this video to be saved with filter. I only want to see the preview of the video with filter on the screen.  
4. Save edited video.

As far as I know it is possible to see the preview on desktop using "ffplay". 

Is it possible to do on the mobile device? Share the example if you have some please.

**Comment by tanersener** [comment]
`mobile-ffmpeg` does not include `ffplay`. You can't use it to preview files.

**Comment by VovaMedvediev** [comment]
@tanersener So there is no option to see the preview?

**Comment by tanersener** [comment]
Not in this project.

**Comment by VovaMedvediev** [comment]
Got it. Thanks!
