### ISSUE TITLE
error minsdk24

### ISSUE THREAD

**Issue by YahiaAgwa** [tanersener/flutter-ffmpeg#20]
the project have minds 21 and targetsdk 28

when run build
flutter build app --release
have this error

* What went wrong:                                                      
Execution failed for task ':app:processReleaseManifest'.                
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.arthenica:mobile-ffmpeg-https:4.2.1] /Users/YahiaAgwa/.gradle/caches/transforms-1/files-1.1/mobile-ffmpeg-https-4.2.1.aar/a7b6ca1ab27c2612e90bb9e88826dd44/AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 24,
                or use tools:overrideLibrary="com.arthenica.mobileffmpeg" to force usage (may lead to runtime failures)

**Comment by tanersener** [comment]
Your build fails because the default package requires API Level 24 on Android. To support API Level 21, you need to depend on an LTS release. Can you update your dependency using instructions in [Packages](https://github.com/tanersener/flutter-ffmpeg#21-packages) section?

**Comment by lifenautjoe** [comment]
Hmm doing the steps on the packages section, still fails on run with the minSdk error.

Should we uninstall flutter_ffmpeg from pubspec?

**Comment by praaggg** [comment]
> Your build fails because the default package requires API Level 24 on Android. To support API Level 21, you need to depend on an LTS release. Can you update your dependency using instructions in [Packages](https://github.com/tanersener/flutter-ffmpeg#21-packages) section?

Hello: Would you be able to guide me with the issue below please?
DEBUG:p4a:[DEBUG]:      
[DEBUG]:        > Task :processDebugManifest FAILED
DEBUG:p4a:[DEBUG]:   rge> Task :processDebugManifest FAILED
[DEBUG]:        /home/prashant/Prashant/Jigyasu/Python/PythonTutorial/SpeechRecognition/VoiceAssistantMob/.buildozer/android/platform/build-armeabi-v7a/dists/VoiceAsstMob__armeabi-v7a/src/main/AndroidManifest.xml:22:5-74 Error:
DEBUG:p4a:[DEBUG]:      /home/prashant/Prashant/Jigyasu/Python/PythonTutorial/SpeechRecognition/VoiceAssistantMob/.buildozer/android/platform/build-armeabi-v7a/dists/VoiceAsstMob__armeabi-v7a/src/main/AndroidManifest.xml:22:5-74 Error:
[DEBUG]:                uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.arthenica:mobile-ffmpeg-full:4.4] /home/prashant/.gradle/caches/transforms-2/files-2.1/eae601a8601cf2a280543aacb6e509a4/AndroidManifest.xml as the library might be using APIs not available in 21
DEBUG:p4a:[DEBUG]:              uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.arthenica:mobile-ffmpeg-full:4.4] /home/prashant/.gradle/caches/transforms-2/files-2.1/eae601a8601cf2a280543aacb6e509a4/AndroidManifest.xml as the library might be using APIs not available in 21
[DEBUG]:                Suggestion: use a compatible library with a minSdk of at most 21,
DEBUG:p4a:[DEBUG]:              Suggestion: use a compatible library with a minSdk of at most 21,
[DEBUG]:                        or increase this project's minSdk version to at least 24,
DEBUG:p4a:[DEBUG]:                      or increase this project's minSdk version to at least 24,
[DEBUG]:                        or use tools:overrideLibrary="com.arthenica.mobileffmpeg" to force usage (may lead to runtime failures)
DEBUG:p4a:[DEBUG]:                      or use tools:overrideLibrary="com.arthenica.mobileffmpeg" to force usage (may lead to runtime failures)
[DEBUG]:
