### ISSUE TITLE
Result return 0 but can not mix file 

### ISSUE THREAD

**Issue by abhijitrajmane** [tanersener/flutter-ffmpeg#201]
**Description**
I have issue with audio mix in a flutter, I am getting return code 0 means success, but when i checked output audio file its not mix..This issue happen with some audio files 
**Expected behavior**
every audio file can mix in another audio file 
**Current behavior**
i have issue with audio mix in flutter, i am getting return code 0 means success, but when i checked output audio file its not mix

Command.:-
    String fileMixCommand = "-i "+ filepath1 +" -i "+filepath2+" -filter_complex amix=inputs=2:duration=first:dropout_transition=0 "+outputpath;

The console shows following message:-
[mp3 @ 0xc7dcbc00] Frame rate very high for a muxer not efficiently supporting it.
I/flutter (12942): Please consider specifying a lower framerate, a different muxer or -vsync 2

**Comment by abhijitrajmane** [comment]
Please give me replay as early as possible

**Comment by abhijitrajmane** [comment]
I am waiting for your answer, please

**Comment by tanersener** [comment]
I don't know the answer. Hard to say whether something is wrong there or not. Maybe this is the normal behaviour. 

See #23
