### ISSUE TITLE
getMediaInformation cannot always get complete information.

### ISSUE THREAD

**Issue by zxl777** [tanersener/flutter-ffmpeg#202]
getMediaInformation cannot always get complete information.
Sometimes complete information can be obtained, sometimes only one piece can be obtained.
iOS 13, flutter_ffmpeg: ^0.2.10
```
      final FlutterFFprobe _flutterFFprobe = new FlutterFFprobe();

      _flutterFFprobe.getMediaInformation(bigFile.path).then((info) {
          print(info);
}

```

**Comment by zxl777** [comment]
The problem seems to have been resolved. getMediaInformation is not thread-safe, and getMediaInformation cannot be called multiple times at the same time. It should be changed to await and executed in sequence, and the result is normal.

**Comment by tanersener** [comment]
Yeah, `getMediaInformation` does not support concurrent executions. Documentation of the parent project explains this detail in [FFprobe](https://github.com/tanersener/mobile-ffmpeg/blob/master/android/app/src/main/java/com/arthenica/mobileffmpeg/FFprobe.java#L92-L94). We need to add this into `flutter_ffmpeg` as well.

**Comment by tanersener** [comment]
Documentation updated in `v0.3.0`.
