### ISSUE TITLE
Downloading HLS Stream

### ISSUE THREAD

**Issue by developeralp** [tanersener/flutter-ffmpeg#206]
Hello all,

First of all thanks for this great plugin :)

I'm developing an app, this app needs to download hls streams.

I'm using this code to download it:
`ffmpeg -i $HLSURL -c copy out.mkv`

But this code gives me this error:

`Unable to find a suitable output format for 'ffmpeg'`

How can I solve this?

Also I'm using `full-gpl-lts` package (because of api level)

**Comment by tanersener** [comment]
Use full path for your video file. If you don't specify a directory `ffmpeg` will try to create it in the default directory which is not writable.

**Comment by developeralp** [comment]
Thank you @tanersener I handled it with the `path_provider` plugin and `getExternalStorageDirectory()` method.

**Comment by rahulshamkuwar** [comment]
I'm trying to do a similar thing but I keep getting the error `No such file or directory`.
I use the `getApplicationDocumentsDirectory()` from `path_provider` since I want to be able to use the directory on both iOS and Android, and this is my command:
```dart
final externalDir = await getApplicationDocumentsDirectory();
String directory = "${externalDir.path}/ms_lectures/";
String path = "$directory${lectureItem.title.replaceAll(' ', '')}.mp4";
Uri uri = Uri.directory(directory, windows: false);

if (!await Directory(directory).exists()) {
  Directory.fromUri(uri);
}
if (await File(path).exists()) {
  this.failed = true;
  this.error = "File already exists!";
  notifyListeners();
  return;
}
executeAsyncFFmpeg("-i ${lectureItem.hlsUrl} -map 0 -c copy $path", callback);
```

I tried it with `getExternalStorageDirectory()` and that didn't work either.
