### ISSUE TITLE
using flutter_ffmpeg with agora

### ISSUE THREAD

**Issue by surielb** [tanersener/flutter-ffmpeg#209]
**Description**
So I hit a problem recently. My app has been using flutter_ffmpeg for a while, but recently I have added the agora.io rtc video chat engine to my app and it seems their package comes with their own (very slim) version of ffmpeg linked for iOS.
This caused the formidable "WARNING: library configuration mismatch" message when running ffmpeg and I could see that the version that was being used was the trimmed down version.

This caused an error whenever the app attempted to encode a video as no encoders are included in their ffmpeg lib

**Expected behavior**
The app should use the linked ffmpeg from flutter_ffmpeg instead of agora's

**Current behavior**
Since flutter's pod implementation adds the list of frameworks in OTHER_LDFLAGS alphabetically and agora is alphabetically before flutter_ffmpeg the wrong libraries are being liked

**Other**
Modifying the Pods-Runner.debug.xcconfig manually and reorganizing the frameworks does work, however this is not practical as flutter will rewrite it any time `pub get` is run.

**Solution**
So, since I came up with a solution for this, I thought of sharing it here in the issues in case someone hits the same issue in the future.

Basically modifying the Podfile to rewrite the  OTHER_LDFLAGS as part of the pod logic:

```ruby

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
      target.build_configurations.each do |config|
        if target.name == "Pods-Runner"
            
            xcconfig_path = config.base_configuration_reference.real_path

            # read from xcconfig to build_settings dictionary
            build_settings = Hash[*File.read(xcconfig_path).lines.map{|x| x.split(/\s*=\s*/, 2)}.flatten]

            # read current OTHER_LDFLAGS
            flags = build_settings['OTHER_LDFLAGS']
            
            #extract agora frameworks - this can be modified if you have issues with a different lib
            agora = flags.scan(/-framework "agora[^"]*" /i)
            
            #remove all references
            flags.gsub! /-framework "agora[^"]*" /i,''
            
            #place extracted frameworks back at the end of the list
            flags.sub!('-weak_framework ',agora.join('') + ' -weak_framework ')
            
            #store changes
            build_settings['OTHER_LDFLAGS'] = flags


            # write build_settings dictionary to xcconfig
            File.open(xcconfig_path, "w") do |file|
              build_settings.each do |key,value|
                file.puts "#{key} = #{value}"
              end
            end
        end
      end
    
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by tanersener** [comment]
Thanks for sharing this :+1:

**Comment by jtkeyva** [comment]
thanks
