### ISSUE TITLE
can't run on iOS, getting error on flutter run ?

### ISSUE THREAD

**Issue by dubeyteja** [tanersener/flutter-ffmpeg#210]
In file included from /Users/user/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.0/ios/Classes/EmptyLogDelegate.m:20:
    /Users/user/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.0/ios/Classes/EmptyLogDelegate.h:20:10: fatal error:
    'mobileffmpeg/LogDelegate.h' file not found
    #include <mobileffmpeg/LogDelegate.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by tanersener** [comment]
![screenshot](https://user-images.githubusercontent.com/10158439/93825942-253b7380-fc5e-11ea-8bb3-3845f1569faa.gif)

**Comment by dubeyteja** [comment]
I don't know why ? But I am unable to run the app in. iOS . I have no issues in android .

**Comment by tanersener** [comment]
Clean your `cocoapods` cache and try again. Sometimes it helps to resolve this kind of issues.

**Comment by dubeyteja** [comment]
I tried that , even removed flutter sdk and reinstalled it . created a new flutter project but still no use.

**Comment by dubeyteja** [comment]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from
    /Users/dubeysaivithalteja/Softwares/flutter/.pub-cache/hosted/pub.dartlang.o
    rg/flutter_ffmpeg-0.3.0/ios/Classes/FlutterFFmpegPlugin.m:20:
    /Users/dubeysaivithalteja/Softwares/flutter/.pub-cache/hosted/pub.dartlang.o
    rg/flutter_ffmpeg-0.3.0/ios/Classes/EmptyLogDelegate.h:20:10: fatal error:
    'mobileffmpeg/LogDelegate.h' file not found
    #include <mobileffmpeg/LogDelegate.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from
    /Users/dubeysaivithalteja/Softwares/flutter/.pub-cache/hosted/pub.dartlang.o
    rg/flutter_ffmpeg-0.3.0/ios/Classes/FlutterExecuteDelegate.m:20:
    /Users/dubeysaivithalteja/Softwares/flutter/.pub-cache/hosted/pub.dartlang.o
    rg/flutter_ffmpeg-0.3.0/ios/Classes/FlutterExecuteDelegate.h:21:9: fatal
    error: 'mobileffmpeg/ExecuteDelegate.h' file not found
    #import <mobileffmpeg/ExecuteDelegate.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from
    /Users/dubeysaivithalteja/Softwares/flutter/.pub-cache/hosted/pub.dartlang.o
    rg/flutter_ffmpeg-0.3.0/ios/Classes/EmptyLogDelegate.m:20:
    /Users/dubeysaivithalteja/Softwares/flutter/.pub-cache/hosted/pub.dartlang.o
    rg/flutter_ffmpeg-0.3.0/ios/Classes/EmptyLogDelegate.h:20:10: fatal error:
    'mobileffmpeg/LogDelegate.h' file not found
    #include <mobileffmpeg/LogDelegate.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by tanersener** [comment]
Your problem is not about `flutter`. Cleaning, deleting, re-installing `flutter` won't solve your issue. 

You need to check your `cocoapods` cache. Clean it or check that package and see why that file is not there.

**Comment by dubeyteja** [comment]
Can you please tell me how to check the header files that are missing. Atleast tell me the directory to look into.
I open ios/classes/logdelegate.h but its showing error in vs code that these files doesn't exist . Provide a correct path to the files.

**Comment by tanersener** [comment]
Inside `ios/Pods` directory you should have a `mobile-ffmpeg-...` folder. Headers can be found under `mobileffmpeg.framework/Headers` folder under it.

**Comment by dubeyteja** [comment]
![Screenshot 2020-09-22 at 6 16 59 PM](https://user-images.githubusercontent.com/50695128/93883943-dc3bfb80-fcff-11ea-9c66-13666c22599a.jpg)
the error in Xcode is showing like this.

**Comment by tanersener** [comment]
Read my previous post.

**Comment by dubeyteja** [comment]
I have checked the headers folder and I can see ExecuteDelegate.h and LogDelegate.h there but still it show error.
Xcode is searching for them in .symlinks I think ?

**Comment by dubeyteja** [comment]
I have cleaned cocoapods cache and even uninstalled cocoapods and installed them again. I have no issues in android . I don't have other Mac to check whether is that a fault in my machine. but If I remove the dependency from pubspec.yaml everything works fine. I am not sure what's causing the problem ? can you please try to create a new flutter project and try to run it on a simulator.

**Comment by tanersener** [comment]
Why don't you try to run the `example` application under the `example` folder?

**Comment by dubeyteja** [comment]
I don't know how but the example is working . and I tried to run my project again and it works . Thank  you sir . Sorry for annoying you.

**Comment by BrutalCoding** [comment]
I can confirm that 0.3.0 is able to run on iOS 14 simulators. Issue can be closed @tanersener

**Comment by pbajr** [comment]
I needed to manually add each of this to make this work

![Screen Shot 2021-03-11 at 12 45 00 AM](https://user-images.githubusercontent.com/7844463/110665219-17c17800-8203-11eb-9da8-b591e04f4153.png)
