### ISSUE TITLE
[Question] Does it make sense to use multi-threading?

### ISSUE THREAD

**Issue by jpiabrantes** [tanersener/flutter-ffmpeg#211]
I want to encode a large video in my phone. My phone has 4 cores, does it make sense to split the video into 4 and have 4 isolates encoding their part and then concat it all in the end?

**Comment by tanersener** [comment]
I've tried this before but didn't see any noticeable improvement. However, the result depends on the codec/format used and the size of the video. So, I'll suggest trying.
