### ISSUE TITLE
File not found : mobileffmpeg/LogDelegate.h

### ISSUE THREAD

**Issue by DebugTheCode** [tanersener/flutter-ffmpeg#212]
**Description**
I'm trying to run my Flutter app on an iOS 14.0 Simulator device (iPhone 11). The app depends on flutter_ffmpeg 0.3.0.

**Expected behavior**
App installs and launches on the Simulator.

**Current behavior**
Retrieving an error from Xcode Build (see logs). App does not install on the Simulator.

**Logs**
Xcode output:
```
Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command MergeSwiftModule failed with a nonzero exit code
    In file included from /Users/x/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.0/ios/Classes/EmptyLogDelegate.m:20:
    /Users/x/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.0/ios/Classes/EmptyLogDelegate.h:20:10: fatal error: 'mobileffmpeg/LogDelegate.h' file not found
    #include <mobileffmpeg/LogDelegate.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
```

**Environment**
```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale nl-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)
    ! Error: Hobbykamer is not connected. Xcode will continue when Hobbykamer is connected. (code -13)

! Doctor found issues in 1 category.
```

**Comment by DebugTheCode** [comment]
@tanersener Still unable to run on iOS device with 14.0 installed.

Error: ` In file included from /Users/x/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.0/ios/Classes/EmptyLogDelegate.m:20:
    /Users/x/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.0/ios/Classes/EmptyLogDelegate.h:20:10: fatal error: 'mobileffmpeg/LogDelegate.h' file not found
    #include <mobileffmpeg/LogDelegate.h>`

Cleared CocoaPods cache and checked if LogDelegate.h was in the Headers folder, it is.

Please help me out with this.

**Comment by tanersener** [comment]
Take a look at framework search paths / header search paths in `Xcode` and make sure that they're set to recursive. I don't know if that is the problem but it's worth checking out.

You can also try running the `example` app. Running it helps to resolve this kind of errors.

**Comment by hyobbb** [comment]
I have the same problem. It works on debug mode build but on profile mode it gives error. I checked the search path and it is not set to recursive.

**Comment by NTJ3** [comment]
same error

**Comment by singhamit089** [comment]
comment to reopen
`/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.4.0/ios/Classes/EmptyLogDelegate.h:20:10: fatal error: 'mobileffmpeg/LogDelegate.h' file not found
    #include <mobileffmpeg/LogDelegate.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete`
