### ISSUE TITLE
[Question] Using FFMPEG correct

### ISSUE THREAD

**Issue by Lix-ai** [tanersener/flutter-ffmpeg#217]
Hi and thanks for the awesome plugin :),
After prolonging time when longing to using the library I still didn't understand how to use the FFMPEG command right: 

How to use data in FFMPEG commands (input & output). Like: "ffmpeg -i 1.mp3 -i 2.mp3 -i 3.mp3 -i 4.mp3 -filter_complex "[0:a][1:a][2:a][3:a]amerge=inputs=4[aout]" -map "[aout]" output.mp3"

2 Question regarding this command:

1. What is the path to bring the '1.mp3', '2.mp3'... to the FFMPEG.
2. Where is the 'output.mp3' goes to? eventually?
Didn't find any solution, let's speak locally and after that remotlly (API/SERVER).

* Can I add my own assets to the data/storage/0 using path provider? (For example)
OR
Only solution is adding to cloud service or what?
====> What is the best solution?

Thaks in advance =]!!!!!!

**Comment by tanersener** [comment]
Please see [Tips](https://github.com/tanersener/flutter-ffmpeg#5-tips) about paths. Also take a look at example app and see how how example app sets input/output paths.

**Comment by Lix-ai** [comment]
Thanks on it 👍

**Comment by Lix-ai** [comment]
Didn't see any input/output examples (the main example is regarding user input for files) dig a little bit on the examples and didn't see...
sorry..

**Comment by tanersener** [comment]
`example` app runs different `ffmpeg` commands. It has different tabs for each functionality. Each command has at least one input file and one output file. If you follow how those input and output file paths are created then you can understand how they work. If you look but don't see anything just try to read some flutter tutorials. They may help you to understand the concept.
