### ISSUE TITLE
[Question] ffmpeg scale

### ISSUE THREAD

**Issue by ercangurevin** [tanersener/flutter-ffmpeg#218]
First, thanks a lot for the very useful plugin.

I would like to scale the video if its width larger than 1024. I've tried to append "_command" the followings as the ffmpeg documentation suggests but it's not seems to work. 

`_command += ' scale=\'min(1024,iw)\':\'min(720,ih)\'" ';`
`_command += 'scale=1024:-1'` 
and so on..

Any suggestion ?

**Comment by ercangurevin** [comment]
My final execute commands looks like these

`-i "/data/user/0/com.kibrismikro.challengeapp/cache/image_picker3468402018120075392.jpg" -ss 0:00:08.004000 -t 0:00:21.995000 -vf scale=1024:720  -c:a copy -c:v copy "/data/user/0/com.kibrismikro.challengeapp/app_flutter/HLN/image_picker3468402018120075392_trimmed:20201014185037.mp4"

-i "/data/user/0/com.kibrismikro.challengeapp/cache/image_picker4573037421678797457.jpg" -ss 0:00:10.587000 -t 0:00:23.309000 -vf "scale=1024:720" -c:a copy -c:v copy "/data/user/0/com.kibrismikro.challengeapp/app_flutter/HLN/image_picker4573037421678797457_trimmed:20201014185936.mp4"
`

**Comment by ercangurevin** [comment]
Hello @tanersener ,

Do you plan to fix this or it's not an issue but I'm doing something wrong ?

**Comment by tanersener** [comment]
This issue is marked as `missing-issue-template` fields. Because some important issue template fields are not provided. Try to provide logs and define what is `it does not work`.

You're using `-c:v copy`. Did you try removing it? You can't copy a video stream and scale it at the same time as far as I know.
