### ISSUE TITLE
How to expand kind of codec ?

### ISSUE THREAD

**Issue by lxcyha** [tanersener/flutter-ffmpeg#22]
**Description**
I want about using mp3 and its codec libmp3lame. but it doesn't have this codec or lib

**Logs**
Unknown encoder 'libmp3lame'

**Environment**
flutter_ffmpeg:
    git:
      url: git://github.com/tanersener/flutter-ffmpeg.git
      ref: development

**Comment by tanersener** [comment]
`lame` is not included in the default package. You need to install `audio`, `full` or `full-gpl` package using instructions in [2.1 Packages](https://github.com/tanersener/flutter-ffmpeg#21-packages).

**Comment by lxcyha** [comment]
thanks a lot

**Comment by aj019** [comment]
Hi guys thanks for this thread. I was able to convert an mp4 file to mp3 file using the following command 
`-i file1.mp4 -f mp3 -ab 192000 -acodec libmp3lame file2.mp3`
But for some reason the converted mp3 file is not being read by any of the music player on my phone device. Do you have any idea , why that might be happening ? And have you faced the same issue ?

**Comment by lxcyha** [comment]
@aj019 I'm sorry ..I don't know

**Comment by ming0520** [comment]
Hi i did include 
```
    ext {
        flutterFFmpegPackage  = "full-gpl-lts"
    }
```

this section in the build.gradle in Android folder, but it still show the same error in the terminal, may i know what is the next step i need to do after including this code?
