### ISSUE TITLE
iOS crashes on _flutterFFmpeg.execute(_command)

### ISSUE THREAD

**Issue by frankyvij** [tanersener/flutter-ffmpeg#220]
**Description**
Application crashes both on the simulator and physical device as soon as the execute function is called.

I am running the following command:
`ffmpeg command: -i "/Users/shauryanvij/Library/Developer/CoreSimulator/Devices/27F7D20F-A571-4F80-9BE1-61B4A0B3096B/data/Containers/Data/Application/0DA9559D-13F1-4178-AFA8-DFCF20928B92/tmp/trim.9AFA2179-C6CC-4E26-9CC7-91F81A23A4FC.MOV" -ss 0:00:00.000000 -t 0:00:15.000000 -c:v libx264 -crf 19 -level 3.1 -preset slow -tune film -filter:v scale=trunc(oh*a/2)2:480 -sws_flags lanczos -c:a copy "/Users/shauryanvij/Library/Developer/CoreSimulator/Devices/27F7D20F-A571-4F80-9BE1-61B4A0B3096B/data/Containers/Data/Application/0DA9559D-13F1-4178-AFA8-DFCF20928B92/Documents/Trimmer/trim_trimmed:Oct27,2020-15:57:18.mp4"`

I have tried to simplify the command above, but it still crashes.
`ffmpeg command: -i "/Users/shauryanvij/Library/Developer/CoreSimulator/Devices/27F7D20F-A571-4F80-9BE1-61B4A0B3096B/data/Containers/Data/Application/0DA9559D-13F1-4178-AFA8-DFCF20928B92/tmp/trim.9AFA2179-C6CC-4E26-9CC7-91F81A23A4FC.MOV" -ss 0:00:00.000000 -t 0:00:15.000000 -c:v copy -c:a copy "/Users/shauryanvij/Library/Developer/CoreSimulator/Devices/27F7D20F-A571-4F80-9BE1-61B4A0B3096B/data/Containers/Data/Application/0DA9559D-13F1-4178-AFA8-DFCF20928B92/Documents/Trimmer/trim_trimmed:Oct27,2020-15:57:18.mp4"`

**Expected behavior**
Application should not crash, and FFMpeg should encode the video properly.

**Current behavior**
Application is crashing.

**Screenshots**

**Logs**
This is what I have been able to capture from XCode.
https://ghostbin.co/paste/mhr77

**Environment**
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4 19E287, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
[✓] Connected device (2 available)

• No issues found!

**Other**
I can provide more details if required.

**Comment by frankyvij** [comment]
Also, please note that the code implemented works perfectly fine in Android.

Following is my pods file if it may help:

`# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

def flutter_install_ios_plugin_pods(ios_application_path = nil)
  # defined_in_file is set by CocoaPods and is a Pathname to the Podfile.
  ios_application_path ||= File.dirname(defined_in_file.realpath) if self.respond_to?(:defined_in_file)
  raise 'Could not find iOS application path' unless ios_application_path

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.

  symlink_dir = File.expand_path('.symlinks', ios_application_path)
  system('rm', '-rf', symlink_dir) # Avoid the complication of dependencies like FileUtils.

  symlink_plugins_dir = File.expand_path('plugins', symlink_dir)
  system('mkdir', '-p', symlink_plugins_dir)

  plugins_file = File.join(ios_application_path, '..', '.flutter-plugins-dependencies')
  plugin_pods = flutter_parse_plugins_file(plugins_file)
  plugin_pods.each do |plugin_hash|
    plugin_name = plugin_hash['name']
    plugin_path = plugin_hash['path']
    if (plugin_name && plugin_path)
      symlink = File.join(symlink_plugins_dir, plugin_name)
      File.symlink(plugin_path, symlink)

      if plugin_name == 'flutter_ffmpeg'
          pod 'flutter_ffmpeg/min-gpl-lts', :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      else
          pod plugin_name, :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      end
    end
  end
end

target 'Runner' do
  pod "Firebase/MLVisionBarcodeModel"

  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'

      # You can remove unused permissions here
        # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',

          ## dart: PermissionGroup.calendar
          'PERMISSION_EVENTS=0',

          ## dart: PermissionGroup.reminders
          'PERMISSION_REMINDERS=0',

          ## dart: PermissionGroup.contacts
          'PERMISSION_CONTACTS=0',

          ## dart: PermissionGroup.camera
          # 'PERMISSION_CAMERA=0',

          ## dart: PermissionGroup.microphone
          'PERMISSION_MICROPHONE=0',

          ## dart: PermissionGroup.speech
          'PERMISSION_SPEECH_RECOGNIZER=0',

          ## dart: PermissionGroup.photos
          # 'PERMISSION_PHOTOS=0',

          ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
          # 'PERMISSION_LOCATION=0',

          ## dart: PermissionGroup.notification
          'PERMISSION_NOTIFICATIONS=0',

          ## dart: PermissionGroup.mediaLibrary
          'PERMISSION_MEDIA_LIBRARY=0',

          ## dart: PermissionGroup.sensors
          'PERMISSION_SENSORS=0'
        ]
    end

    flutter_additional_ios_build_settings(target)
  end
end
`

**Comment by tanersener** [comment]
Can you please run your app in Xcode and show us where it crashes exactly.

```
2020-10-27 14:09:43.529172+0800 Runner[5647:1133375] -[NSNull length]: unrecognized selector sent to instance 0x1c9cf97f0
2020-10-27 14:09:43.553348+0800 Runner[5647:1133375] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1c9cf97f0'
```

**Comment by frankyvij** [comment]
I am so sorry! The issue was caused by another package that would generate the thumbnail. I have fixed the problem. I will now close the issue! Thank you.
