### ISSUE TITLE
flutter-ffmpeg with flutter_unity_widget

### ISSUE THREAD

**Issue by guoguoguilai** [tanersener/flutter-ffmpeg#222]
**Description**
Both flutter_ffmpeg and flutter_unity_widget work pretty good in both Android and iOS seperately. 
But after  running flutter_ffmpeg, the app would crash if open flutter_unity_widget. I don't know why.  **And this only happens in Android.**

**Expected behavior**
The app will not crash after I open ffmpeg then flutter_unity_widget.

**Current behavior**
The app will crash after I open ffmpeg then flutter_unity_widget.

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
Flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 1.22.1, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

**Other**

**Comment by tanersener** [comment]
A method is implemented to prevent that crash on the parent `mobile-ffmpeg` project. Please read https://github.com/tanersener/mobile-ffmpeg/issues/258 and https://github.com/tanersener/mobile-ffmpeg/wiki/Using-MobileFFmpeg-in-Unity. 

It is not exposed by `flutter_ffmpeg` API, so I'll mark this issue as an enhancement request.

**Comment by guoguoguilai** [comment]
> A method is implemented to prevent that crash on the parent `mobile-ffmpeg` project. Please read [tanersener/mobile-ffmpeg#258](https://github.com/tanersener/mobile-ffmpeg/issues/258) and https://github.com/tanersener/mobile-ffmpeg/wiki/Using-MobileFFmpeg-in-Unity.
> 
> It is not exposed by `flutter_ffmpeg` API, so I'll mark this issue as an enhancement request.

Thanks for you help! 
After add some code to Unity, it works!
`AndroidJavaClass configClass = new AndroidJavaClass("com.arthenica.mobileffmpeg.Config");
            AndroidJavaObject paramVal = new AndroidJavaClass("com.arthenica.mobileffmpeg.Signal").GetStatic<AndroidJavaObject>("SIGXCPU");
            configClass.CallStatic("ignoreSignal", new object[] { paramVal });`
