### ISSUE TITLE
Specs satisfying the flutter_ffmpeg/https (= 0.3.0) dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by mohyM** [tanersener/flutter-ffmpeg#225]
**Description**
Description of what the issue is about.
can't use it in flutter app 

**Expected behavior**
What you expected to happen.
install it correctly 

**Current behavior**
What happened.
[!] CocoaPods could not find compatible versions for pod "flutter_ffmpeg/https":
In Podfile:
flutter_ffmpeg (from .symlinks/plugins/flutter_ffmpeg/ios) was resolved to 0.3.0, which depends on
flutter_ffmpeg/https (= 0.3.0)

Specs satisfying the flutter_ffmpeg/https (= 0.3.0) dependency were found, but they required a higher minimum deployment target.

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
Flutter doctor output

**Other**

**Comment by tanersener** [comment]
Are you defining an iOS deployment target in your Podfile? It has to be 11.0 for Main and 9.3 for LTS releases.
```
platform :ios, '11.0'
```

**Comment by mohyM** [comment]
I changed to 
platform :ios, '11.0'
now this error disappeared and another one released 
fatal error: 'mobileffmpeg/LogDelegate.h' file not found
    #include <mobileffmpeg/LogDelegate.h>

**Comment by tanersener** [comment]
There are similar issues reported previously. Have a look at them please.

**Comment by mohyM** [comment]
Thanks bro @tanersener

**Comment by quetool** [comment]
Hi @mohyM did you solve it?

**Comment by mohyM** [comment]
yes, I solved it after updating cocopodes 
`sudo gem install cocoapods`
and update mac os to macOS Big Sur and Xcode to 12.2

**Comment by quetool** [comment]
Thanks @mohyM, updating cocoapods and targeting ios11 was enough for me. I'm still on Catalina and Xcode 11

**Comment by dhyani15** [comment]
Unable to solve this issue,  I am using an M1 mac.

`[!] CocoaPods could not find compatible versions for pod "flutter_ffmpeg/https":
  In Podfile:
    flutter_ffmpeg (from `.symlinks/plugins/flutter_ffmpeg/ios`) was resolved to 0.3.1, which depends on
      flutter_ffmpeg/https (= 0.3.1)

Specs satisfying the `flutter_ffmpeg/https (= 0.3.1)` dependency were found, but they required a higher minimum deployment target.`
