### ISSUE TITLE
Could not find com.arthenica:mobile-ffmpeg-bluewhale:4.4.

### ISSUE THREAD

**Issue by muneeb900** [tanersener/flutter-ffmpeg#226]
**Description**
After Run project error generate.
* What went wrong:
Could not determine the dependencies of task ':flutter_ffmpeg:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':flutter_ffmpeg:debugCompileClasspath'.
   > Could not find com.arthenica:mobile-ffmpeg-bluewhale:4.4.
     Required by:
         project :flutter_ffmpeg

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
Exception: Gradle task assembleDebug failed with exit code 1

![error](https://user-images.githubusercontent.com/51731384/98580870-7b35aa80-22e2-11eb-9db4-5410d0913743.jpeg)

**Comment by tanersener** [comment]
Something is wrong about the package name you're setting. Do you have something like `ext.flutterFFmpegPackage  = "bluewhale"` in your parent `build.gradle` file? Please have a look at [2.1.1 Android Packages](https://github.com/tanersener/flutter-ffmpeg#211-android) again.

**Comment by muneeb900** [comment]
![fileadd](https://user-images.githubusercontent.com/51731384/98587877-9c9b9400-22ec-11eb-951f-d976a8c229b2.PNG)
I've checked it out. same package name and also add ext.flutterFFmpegPackage. 
same error occurs kindly, solve its issue.

**Comment by tanersener** [comment]
I think there is a misunderstanding on your side. Instructions on section `2.1.1 Android Packages` clearly says that you need to use one of the package names listed in section 2.1 of the README. There are 8 packages listed in section 2.1 and `bluewhale` is not one of them.

````
ext {
    flutterFFmpegPackage  = "<flutter ffmpeg package name listed in section 2.1>"
}
```

**Comment by muneeb900** [comment]
@tanersener Thank you so much. problem solved.

**Comment by imwa5i7** [comment]
@tanersener I read all of your comments. Can you please tell me what am I doing wrong here? 
PS : I have the same problem
![Screenshot_2021-02-11_02-06-02](https://user-images.githubusercontent.com/53287794/107609708-c7f48e80-6c0d-11eb-9303-7ca60b4f503b.png)

**Comment by tanersener** [comment]
`shine` is not a flutter_ffmpeg package name. See section 2.1 of README please.

```
ext {
    flutterFFmpegPackage  = "<flutter ffmpeg package name listed in section 2.1 of README>"
}
```
