### ISSUE TITLE
How can I add libsrt?

### ISSUE THREAD

**Issue by tobisweb** [tanersener/flutter-ffmpeg#227]
Hi,
in FFMPEG it is possible to use the SRT protocol by building it with `--enable-libsrt` flag.
Source: https://srtlab.github.io/srt-cookbook/apps/ffmpeg/

**I was wondering how I could add this library to the mobile version too?**

My goal is to be able to receive streams (srt://example.com) and display them as video through the flutter_video_player plugin. Similar to your example app with https.

I woulld really appreciate any kind of help for this issue.

**Comment by tanersener** [comment]
See this issue created on parent `mobile-ffmpeg` project please: tanersener/mobile-ffmpeg/issues/81.

**Comment by tobisweb** [comment]
Thanks!
