### ISSUE TITLE
Apk size will be huge after adding flutter_ffmpeg package

### ISSUE THREAD

**Issue by Malloumabba1** [tanersener/flutter-ffmpeg#228]
Hello, my apk size is 19MB, but after adding `flutter_ffmpeg` package with package name `min` it will be 60MB and 51MB with package name `min-lts`. How i can do to decrement my apk size? please help me

Note: I want to use `flutter_ffmpeg` only for compress my audio to `OPUS file`

here my example:
All work fine, but my problem only with apk size will be up to 50MB.

```
 executeFFMPEG() async {
    try {
      final FlutterFFmpeg _flutterFFmpeg = new FlutterFFmpeg();

      String uuid = DateTime.now().millisecondsSinceEpoch.toString();

      String outputPath = '/output_audio_ffmpe$uuid.opus';
      io.Directory appDocDirectory;
      if (io.Platform.isIOS) {
        appDocDirectory = await getApplicationDocumentsDirectory();
      } else {
        appDocDirectory = await getExternalStorageDirectory();
      }

      outputPath = appDocDirectory.path + outputPath;

      _flutterFFmpeg.execute("-i ${_recording.path} -c:a opus -strict -2 $outputPath")
          .whenComplete(() {
        setState(() {
          outputPathFFMPEG = outputPath;
          sendToDB();
        });
      }).then((rc) => print("FFmpeg process exited with rc $rc"));

      print("File FFMPEG Converted $outputPath");
    } catch (e) {
      print("Try Catch for FFMPEG Execution $e");
    }
  }

```

**Comment by ilkercankaya** [comment]
Same issue here, My app size is 60MB after importing this lib otherwise it is 16MB. I used "audio-lts". This makes my app 4x bigger which is not  tolerable sadly...

**Comment by filipedfs** [comment]
Are you comparing the size of the release apk or the debug apk?

**Comment by ilkercankaya** [comment]
Both values are for release apk in my case

**Comment by filipedfs** [comment]
In my case, the biggest apk for release is 36.5MB and the lowest size is 24.9MB. But I don't know the size without the package.

**Comment by Malloumabba1** [comment]
Yes @filipedfs

**Comment by yurijdvornyk** [comment]
I'm having the same issue.
The app had 50-55Mb previously and after adding `flutter_ffmpeg: ^0.3.0` the size is 120-125 Mb.

**Comment by stha-ums** [comment]
same issue here.

**Comment by tanersener** [comment]
I see that there is misunderstanding about this plugin. Mostly about how it can be used and the size of it. Let me repeat some of the details written in the README, and add a few notes from Android documentation.

`flutter_ffmpeg` is a plugin but it doesn't have a fixed size. It comes in 8 different packages and 2 release variants. This makes 16 different `flutter_ffmpeg` binaries (including dependencies). All of them are different in content and size.

If you're not happy with the application size after adding `flutter_ffmpeg`, what you can do is:
1. You can use a smaller package. README lists all `flutter_ffmpeg` packages and includes details about what's inside each of them. Instructions for installing a different package is also given there. Choose the smallest package available that includes external libraries you need and use it in your app.

    You can check the size of each package by using the information available in the parent `mobile-ffmpeg` project.  `fluttter_ffmpeg` itself is small but it depends on `mobile-ffmpeg` and the size of `mobile-ffmpeg` package used is the main factor that increases the application size. The latest version of the plugin, `v0.3.0` depends on `mobile-ffmpeg v4.4`. Assets section of [mobile ffmpeg v4.4 release](https://github.com/tanersener/mobile-ffmpeg/releases/tag/v4.4) lists all 8 Android packages (.aar files). 

    A simple calculation can tell how much your app will be affected by including this plugin. For example `mobile-ffmpeg-min-4.4.aar` is the package used by `min` package of `flutter_ffmpeg`. It has a size of 25.8 MB. `v4.4` is a Main release (note that there are also LTS releases), and it includes 4 architectures inside. This means 6.45 MB for each architecture. If you include this plugin and use the `min` package users will download on average 6.45 MB more. If you use a bigger package size will increase. Numbers are there you can do the math yourself.

2. Make sure that you use an [apk split configuration](https://developer.android.com/studio/build/configure-apk-splits) to decrease download size. This approach is recommended by Android. You can use it for your `Flutter` apps as well. 

    For example, this is the configuration used by the [test application of mobile-ffmpeg ](https://github.com/tanersener/mobile-ffmpeg/blob/v4.4/android/test-app/build.gradle#L31-L38).

3. If using a smaller package or apk splitting is not enough for you then you can try building your own `mobile-ffmpeg` package. This is what I suggest to all `mobile-ffmpeg` and `flutter_ffmpeg` users. There is a wiki page that shows how it can be done, https://github.com/tanersener/mobile-ffmpeg/wiki/How-to-decrease-binary-size. It is not simple, but the option is there. It will give you the smallest binary possible.

**Comment by Giacomo1993** [comment]
Hi, @tanersener refer to https://github.com/tanersener/flutter-ffmpeg/issues/228#issuecomment-754658550 your previous comment, I have an apk app size too big after installing flutter_ffmpeg. i saw on the analyze apk that the problem is related to lib implemented based on different CPU configurations. Can i reduce or remove one of these architecture/lib? Is there a mode for resolving or reduce app size rather than your previous comment?  you can see attached image. Thank you very much!
![Screenshot 2021-09-17 at 13 23 23](https://user-images.githubusercontent.com/68004050/133774903-efb6e430-d269-4212-b83a-92b947e79043.png)
!

**Comment by tanersener** [comment]
>  Can i reduce or remove one of these architecture/lib?

If you delete an architecture, devices that have that architecture won't be able to use your app. If you are happy about it then you can delete those folders.

> Is there a mode for resolving or reduce app size rather than your previous comment?

There is not.

**Comment by Giacomo1993** [comment]
> > Can i reduce or remove one of these architecture/lib?
> 
> If you delete an architecture, devices that have that architecture won't be able to use your app. If you are happy about it then you can delete those folders.
> 
> > Is there a mode for resolving or reduce app size rather than your previous comment?
> 
> There is not.

**Comment by Giacomo1993** [comment]
i added ffmpeg library on pubspec.yaml file on my flutter project and I didn't edit android/build.gradle and app/build.gradle, but why my apk is so big? I read your comment and my default package is https. is it possible that only one package is so big?
I tried to add a minor package like "min" or "min-gpl" on android/build.gradle file: 
ext {
    flutterFFmpegPackage  = "min-gpl"
}

but this action increases my apk size. Please can you help me?

**Comment by Giacomo1993** [comment]
> > Can i reduce or remove one of these architecture/lib?
> 
> If you delete an architecture, devices that have that architecture won't be able to use your app. If you are happy about it then you can delete those folders.
> 
> > Is there a mode for resolving or reduce app size rather than your previous comment?
> 
> There is not.

i added ffmpeg library on pubspec.yaml file on my flutter project and I didn't edit android/build.gradle and app/build.gradle, but why my apk is so big? I read your comment and my default package is https. is it possible that only one package is so big?
I tried to add a minor package like "min" or "min-gpl" on android/build.gradle file:
ext {
flutterFFmpegPackage = "min-gpl"
}

but this action increases my apk size. Please can you help me?

**Comment by tanersener** [comment]
@Giacomo1993 Mate, I gave all instructions to find the app size in my post above. You can find the size of `https` package and see how big each architecture is. Please compare that with the libraries in your `apk and see if it is normal or not.

**Comment by Giacomo1993** [comment]
Hi @tanersener, I followed your advice. I compared two apk of my app and the different size is too big. 
![Screenshot 2021-09-21 at 15 32 53](https://user-images.githubusercontent.com/68004050/134184012-997894c3-9a5e-479b-95d1-dff6e9398632.png)
you can see attached image and the difference between apk size is 96.6Mb. it seems to be wrong! based on your previous comment: 

**_"You can check the size of each package by using the information available in the parent mobile-ffmpeg project. fluttter_ffmpeg itself is small but it depends on mobile-ffmpeg and the size of mobile-ffmpeg package used is the main factor that increases your application size. The latest version of the plugin, v0.3.0 depends on mobile-ffmpeg v4.4. Assets section of mobile ffmpeg v4.4 release lists all 8 Android packages (.aar files) with their sizes.

A simple calculation can tell how much your app will be affected by including this plugin. For example mobile-ffmpeg-min-4.4.aar is the package used by min package of flutter_ffmpeg. It has a size of 25.8 MB. v4.4 is a Main release (note that there are also LTS releases), and it includes 4 architectures inside. This means 6.45 MB for each architecture. If you include this plugin and use the min package users will download 6.45 MB more on average. If you use a bigger package, the total size will increase. Numbers are there you can do the math yourself and find the final application size."_**

I implemented ffmpeg library without adding anything else external library, so the default package implemented is https. 
https.aar size is 33.8 Mb right? Fine. 
next, ffmpeg library size is 40Mb, right? Fine.
total size is 33.8 Mb + 40Mb = 73.8 Mb. 
Why my app size is 96.6Mb? 

follow the images from analyzing apk: 
![Screenshot 2021-09-21 at 16 02 00](https://user-images.githubusercontent.com/68004050/134185168-85102713-1f08-41cd-9f8d-9f480169fc10.png)
![Screenshot 2021-09-21 at 16 02 14](https://user-images.githubusercontent.com/68004050/134185185-42e52df9-4c73-4154-b975-364d4aaa4c2e.png)


Sorry for my continued requests for help, but I need to reduce apk size in order to send apk to the Client. Actually, we are not using the bundle in order to generate a build android. 

 Please, everything you tell me can be utils!!

**Comment by tanersener** [comment]
@Giacomo1993 Mate, you're building a universal `apk`, all ABIs are in the same file. It is normal to have a very big .apk file. 

It seems like you're using an LTS version which includes 5 architectures. That is also increasing the app size.

Also, do you see the `libflutter.so` and `libapp.so` files inside each architecture? They are coming from `flutter`. They are not part of `flutter_ffmpeg`. 17 MB for each architecture.

**Comment by Giacomo1993** [comment]
**I followed step by step your advice and the README file on flutter_ffmpeg, so I installed the library and this is the android/build.gradle of library:** 

static String safePackageName(String prop) {
    prop.replace("-lts", "")
}

static String safePackageVersion(String prop, String version, String ltsVersion) {
    prop.contains("-lts") ? ltsVersion + ".LTS" : version
}

String safeExtGet(String prop, String fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

group 'com.arthenica.flutter.ffmpeg'
version '0.4.2'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
    }
}

rootProject.allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion safeExtGet('flutterFFmpegPackage', 'https').contains("-lts") ? 16 : 24
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-' + safePackageName(safeExtGet('flutterFFmpegPackage', 'https')) + ':' + safePackageVersion(safeExtGet('flutterFFmpegPackage', 'https'), safeExtGet('mobileFFmpegVersion', '4.4'), safeExtGet('mobileFFmpegLTSVersion', '4.4'))
}

**I'm not edited android/build.gradle and app/build.gradle of my project. in Fact, in the previous comment I asked you why apk size is too big?**

**My android/build.gradle file:** 



buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}



**my app/build.gradle file:** 

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}


apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"



android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "none(i'm sorry but i'd like avoid of share my applicationID)"
        minSdkVersion 24
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}


dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

Do you know why the size of components and library is too big? 

"It seems like you're using an LTS version which includes 5 architectures. That is also increasing the app size."

But I used the library so, without edit anything else!

**Comment by tanersener** [comment]
Mate, I share what I see from your screenshots but I don't understand what you're asking from me. Are you asking me to explain why `flutter` adds `libflutter.so` and `libapp.so` files?
