### ISSUE TITLE
Image Output not being overwritten

### ISSUE THREAD

**Issue by mtkgeek** [tanersener/flutter-ffmpeg#233]
I'm trying to generate waveform images for different audio files but no matter what i do, i keep getting the same waveform image for every audio. The first audio file returns the correct waveform image but subsequent files also return that same image as output. Yes, i already set the overwrite flag to my command but it doesn't change anything. Here's my code.

```
class RecordController extends GetxController {
Rx<File> cachedAudioFile = Rx<File>();
  RxString waveFormImagePath = "".obs;

Future<int> getWaveForm(String url) async {
    final FlutterFFmpeg _flutterFFmpeg = FlutterFFmpeg();
    final FlutterFFmpegConfig _flutterFFmpegConfig = FlutterFFmpegConfig();
    // clear out path for new wave form
    if (waveFormImagePath.value != "") {
      File(waveFormImagePath.value).delete();
    }
    waveFormImagePath.value = "";
    Directory appDocumentDir = await getApplicationDocumentsDirectory();
    String rawDocumentPath = appDocumentDir.path;
    waveFormImagePath.value = [rawDocumentPath, '/audioWaveForm.png'].join();

    cachedAudioFile.value = await DefaultCacheManager().getSingleFile(url);
    String inputFilePath = cachedAudioFile.value.path;
    String commandToExecute = [
      '-y -i $inputFilePath -filter_complex "compand,aformat=channel_layouts=mono,showwavespic=s=4000x2000:colors=white" -frames:v 1 ',
      waveFormImagePath.value
    ].join();
    _flutterFFmpeg
        .execute(commandToExecute)
        .then((rc) => print("FFmpeg process exited with rc $rc"));
    int returnCode = await _flutterFFmpegConfig.getLastReturnCode();
    var output = await _flutterFFmpegConfig.getLastCommandOutput();
    print(output);
    print(waveFormImagePath.value);

    return returnCode;
  }
}
```
I'm using the Getx package to manage state and as such i can use the waveFormImagePath anywhere in my UI plus it's reactive. So somewhere in my UI i have this

`FileImage(File(recordController?.waveFormImagePath?.value))`

**Comment by BesartLaci** [comment]
@mtkgeek have you checket the outputs directly on your device storage or only in the UI?  
  
Because using FileImage with an ImagePath which did not change, will show you on rebuild the allready cached Image, which in your case would be your first produced waveFromImage. This is an FlutterFramework StateManagement issue  
  
to rerender changing images which have the same filePaths you have to do it this way  
  
```dart  
  @override
  Widget build(BuildContext context) {

    var imageBytes = File(previewValue).readAsBytesSync();

    return Container(
        child: Image.memory(imageBytes),    
    );
  }  
```
