### ISSUE TITLE
Knowing completion of async execution

### ISSUE THREAD

**Issue by Extazx2** [tanersener/flutter-ffmpeg#234]
It's more a question than an issue :

**Description**
Is there a way to know if an async execution is complete or has failed ?

**Expected behavior**
If I switch to executeAsync, will I be able to handle return code correctly as I would like to ? (couldn't find an example in the repo)

**Current behavior**
At the moment in my app, I have an ffmpeg command going through that copy a video, and in another page I can select a video and read informations about this video (even create a thumbnail).
These operations can be run simulteanously but whenever i'm copying a huge video (0,9gb) the copy process ends with an error 255, when I guess, there is too much things for the phone to handle.
I consider switching to executeAsync but I don't see how to get return code from the executionId.

**Logs**
https://ghostbin.co/paste/cy84w

**Comment by tanersener** [comment]
When you call `executeAsync` the seconds parameter `ExecuteCallback` is called when the execution is completed. Have you tried using it?

**Comment by Extazx2** [comment]
I saw it in the code, but didn't really notice how it worked.

You should consider adding it to the readme / pub page
