### ISSUE TITLE
iOS full-gpl not working

### ISSUE THREAD

**Issue by maxsap** [tanersener/flutter-ffmpeg#236]
**Description**
Cannot get full-gpl to work on iOS, getting linking errors.
I tried with 'full' version which works, I have tried with 'https-lts' which both work but it seems all the 'gpl' variants are failing.
I need a 'gpl' version as I would like to encode the video using h264.

**Expected behaviour**
Get FFmpeg with full-gpl modules installed.
I have tried the same code on Android and it works as expected but I cannot get it to even deploy on iOS

**Current behaviour**
When I try to deploy using VSCode it gets stuck to "installing and launching".
I have tried opening the project on XCode, there it is successful builds but when the app starts I get:
`dyld: Library not loaded: @rpath/libwebp.framework/libwebp
  Referenced from: /private/var/containers/Bundle/Application/4124DA56-28FF-442C-8186-8DFA8DB68E97/Runner.app/Frameworks/video_thumbnail.framework/video_thumbnail
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/4124DA56-28FF-442C-8186-8DFA8DB68E97/Runner.app/Frameworks/libwebp.framework/libwebp: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A
	/private/var/containers/Bundle/Application/4124DA56-28FF-442C-8186-8DFA8DB68E97/Runner.app/Frameworks/libwebp.framework/libwebp: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A
	/private/var/containers/Bundle/Application/4124DA56-28FF-442C-8186-8DFA8DB68E97/Runner.app/Frameworks/libwebp.framework/libwebp: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A
	/private/var/containers/Bundle/Application/4124DA56-28FF-442C-8186-8DFA8DB68E97/Runner.app/Frameworks/libwebp.framework/libwebp: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A
	/private/var/containers/Bundle/Application/4124DA56-28FF-442C-8186-8DFA8DB68E97/Runner.app/Frameworks/libwebp.framework/libwebp: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A
	/private/var/containers/Bundle/Application/4124DA56-28FF-442C-8186-8DFA8DB68E97/Runner.app/Frameworks/libwebp.framework/libwebp: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb) `

`dyld__abort_with_payload:
    0x107ca13e0 <+0>:  mov    x16, #0x209
    0x107ca13e4 <+4>:  svc    #0x80
->  0x107ca13e8 <+8>:  b.lo   0x107ca1404               ; <+36>
    0x107ca13ec <+12>: stp    x29, x30, [sp, #-0x10]!
    0x107ca13f0 <+16>: mov    x29, sp
    0x107ca13f4 <+20>: bl     0x107c9f9e8               ; cerror_nocancel
    0x107ca13f8 <+24>: mov    sp, x29
    0x107ca13fc <+28>: ldp    x29, x30, [sp], #0x10
    0x107ca1400 <+32>: ret    
    0x107ca1404 <+36>: ret    `

**Other**
Seems similar to [this issue](https://github.com/tanersener/flutter-ffmpeg/issues/231) but also affects full-gpl.
My Podfile looks like:

`
  plugins_file = File.join(ios_application_path, '..', '.flutter-plugins-dependencies')
  plugin_pods = flutter_parse_plugins_file(plugins_file)
  plugin_pods.each do |plugin_hash|
    plugin_name = plugin_hash['name']
    plugin_path = plugin_hash['path']
    if (plugin_name && plugin_path)
      symlink = File.join(symlink_plugins_dir, plugin_name)
      File.symlink(plugin_path, symlink)

      if plugin_name == 'flutter_ffmpeg'
          pod 'flutter_ffmpeg/full-gpl', :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      else
          pod plugin_name, :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      end
    end
  end
end
`

**Comment by tanersener** [comment]
Where is that `video_thumbnail.framework` coming from? According to your logs `video_thumbnail.framework` and `libwebp.framework` linked from it has some issues.

**Comment by BesartLaci** [comment]
@maxsap which XCode version do you use because there are some changes since version 12  which requires to force ios version in podfile
  
```shell  
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (4 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4
```
We are using ffmpeg 0.2.10 full-gpl and our pod file looks like
  
```pod  
# we use ios 11 becaues FFmpeg Full-LPG requiered
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # required for FFmpeg pod install https://pub.dev/packages/flutter_ffmpeg
  def flutter_install_ios_plugin_pods(ios_application_path = nil)

    # defined_in_file is set by CocoaPods and is a Pathname to the Podfile.
    ios_application_path ||= File.dirname(defined_in_file.realpath) if self.respond_to?(:defined_in_file)
    raise 'Could not find iOS application path' unless ios_application_path

    # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
    # referring to absolute paths on developers' machines.

    symlink_dir = File.expand_path('.symlinks', ios_application_path)
    system('rm', '-rf', symlink_dir) # Avoid the complication of dependencies like FileUtils.

    symlink_plugins_dir = File.expand_path('plugins', symlink_dir)
    system('mkdir', '-p', symlink_plugins_dir)

    plugins_file = File.join(ios_application_path, '..', '.flutter-plugins-dependencies')
    plugin_pods = flutter_parse_plugins_file(plugins_file)
    plugin_pods.each do |plugin_hash|
      plugin_name = plugin_hash['name']
      plugin_path = plugin_hash['path']
      if (plugin_name && plugin_path)
        symlink = File.join(symlink_plugins_dir, plugin_name)
        File.symlink(plugin_path, symlink)

        if plugin_name == 'flutter_ffmpeg'
            pod 'flutter_ffmpeg/full-gpl', :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
        else
            pod plugin_name, :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
        end
      end
    end
  end

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# we have to set the deployment target manually becaues new Xcode version 12 does not support ios8 any more
# https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```
