### ISSUE TITLE
Incorrect XCode Support mentioned in README

### ISSUE THREAD

**Issue by devxpy** [tanersener/flutter-ffmpeg#238]
Hey!
Thanks for the arduous work on this great plugin.

I tried to use the Main Release (with `mobile-ffmpeg == 4.4`), using `XCode 11.3`, but it refused to build. 

As it stands, `mobile-ffmpeg` no longer supports `XCode < 12`  - https://github.com/tanersener/mobile-ffmpeg/issues/419

Do you think its reasonable to have Xcode Support as 12.x in the [Main Release column](https://github.com/tanersener/flutter-ffmpeg#23-lts-releases) of the README?

**Comment by tanersener** [comment]
I don't agree. Have you tried using one of the LTS packages? They use `mobile-ffmpeg 4.4.LTS` and can be used under Xcode < 12.

Additionally, if you use `Xcode 11.3` you should be able to use the previous version of `flutter_ffmpeg`, `v0.2.10` with Main Releases as well. I suggest trying it.

**Comment by devxpy** [comment]
Ok, your call.

To be clear, the LTS packages have been working great for me, I was simply suggesting to update the main release column since the latest version of `flutter_ffmpeg` didn't work for me.

**Comment by devxpy** [comment]
Just for reference, here's the error I get when building with `flutter_ffmpeg == 0.3.0` (default package) and `XCode == 11.3.1` -

```
    Undefined symbols for architecture arm64:
      "___darwin_check_fd_set_overflow", referenced from:
          _read_key in mobileffmpeg(libmobileffmpeg_la-fftools_ffmpeg.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by AppDev95** [comment]
Hey 

I am facing a issue while dealing with the ffmpeg , I am using this  pod 'mobile-ffmpeg-full', '4.4.LTS' version

And my xcode version is 10.1 

 And i want to compress the 1080p video  as mp4, and want to keep the size as reduced but dimension should be same .. 
 So I was using the following command in ios ffmpeg :
 
MobileFFmpeg execute: @"-i input.mp4 -c:v libx264 -crf 28 -c:a copy output.MP4"

I am getting the fatal libx264 unknown encoder 

Please help me Suggest me what should i do ??
