### ISSUE TITLE
No such filter: 'drawtext'

### ISSUE THREAD

**Issue by MeitanteiAshour** [tanersener/flutter-ffmpeg#241]
**Description :**
I tried running this on Android Pixel api 27 :
 ```
  String _addText =
        '-i $dbPath -vf "drawtext=fontfile=$fontPath:text=hello:fontcolor=white:fontsize=24:x=(w-text_w)/2:y=(h-text_h)/2" -codec:a copy $outputPath';

    _config.setFontDirectory(fontPath, null);

    await _flutterFFmpeg.execute(_addText);
```
**Expected behavior**
It should work and convert to the desired output.mp4 path

**Current behavior**
ERROR : No such filter : 'draw text '

**Logs**
https://ghostbin.co/paste/msvnxas

**Environment**
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-6.0.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.0)
[✓] Connected device (4 available)

• No issues found!

**Comment by MeitanteiAshour** [comment]
Fixed it by adding in gradle (Android)
`  ext {
      flutterFFmpegPackage  = "full-gpl"
  }`

**Comment by reverie-ss** [comment]
what did u set for font-path?
