### ISSUE TITLE
Cocoa Pods couldn't find compatible version for pod "flutter_ffmpeg/https"

### ISSUE THREAD

**Issue by hayashi-tz** [tanersener/flutter-ffmpeg#243]
I am using flutter_ffmpeg: ^0.3.0 and when I run on iOS, the build execute output "Cocoa Pods couldn't find compatible version for pod "flutter_ffmpeg/https" "

Complete Output was below

> [!] CocoaPods could not find compatible versions for pod "flutter_ffmpeg/https":
>   In Podfile:
>     flutter_ffmpeg (from `.symlinks/plugins/flutter_ffmpeg/ios`) was resolved to 0.3.0, which depends on
>       flutter_ffmpeg/https (= 0.3.0)

**Comment by tanersener** [comment]
Are you sure this is the complete output? 

CocoaPods usually prints more detail after `CocoaPods could not find compatible versions for pod ` message.

**Comment by hayashi-tz** [comment]
Hi Mr.@tanersener, 

I am sorry, I created a duplicate issue #225.
and I had already solved it. 

Thank you very much for supporting.
