### ISSUE TITLE
Can't convert set of images into a video

### ISSUE THREAD

**Issue by cmd-dev** [tanersener/flutter-ffmpeg#244]
**Description**
I am trying to convert a set of images taken after a lapse of 41ms (24fps) into a video but keep on getting errors.
This is the code:
`      final FlutterFFmpeg _flutterFFmpeg = new FlutterFFmpeg();
      await _flutterFFmpeg
          .executeAsync(
              "ffmpeg -framerate 24 -i $path/videoframe_%04d.jpg $path/Project.mp4",
              (a, b) {})
          .then((rc) => print("FFmpeg process exited with rc $rc"));
`

**Expected behavior**
Images to be converted into a Video with 24 FPS
**Current behavior**
Function returns with rc=3002
**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.
I/flutter (25343): FFmpeg process exited with rc 3002
I/mobile-ffmpeg(25343): ffmpeg version v4.4-dev-416
I/mobile-ffmpeg(25343):  Copyright (c) 2000-2020 the FFmpeg developers
I/mobile-ffmpeg(25343): 
I/mobile-ffmpeg(25343):   built with Android (6454773 based on r365631c2) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489587874b2a325e7a516b99d838599c6f) (based on LLVM 9.0.8svn)
I/mobile-ffmpeg(25343):   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --extra-libs='-L/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-gmp --enable-gnutls --enable-iconv --disable-sdl2 --enable-zlib --enable-mediacodec
I/mobile-ffmpeg(25343):   libavutil      56. 55.100 / 56. 55.100
I/mobile-ffmpeg(25343):   libavcodec     58. 96.100 / 58. 96.100
I/mobile-ffmpeg(25343):   libavformat    58. 48.100 / 58. 48.100
I/mobile-ffmpeg(25343):   libavdevice    58. 11.101 / 58. 11.101
I/mobile-ffmpeg(25343):   libavfilter     7. 87.100 /  7. 87.100
I/mobile-ffmpeg(25343):   libswscale      5.  8.100 /  5.  8.100
I/mobile-ffmpeg(25343):   libswresample   3.  8.100 /  3.  8.100
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
W/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] Found EOI before any SOF, ignoring
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
W/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] Found EOI before any SOF, ignoring
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 136 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 108 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] dqt: len 23479 is too large
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 114 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 114 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] dqt: len 25694 is too large
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 17 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] dqt: len 22198 is too large
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] dqt: len 50486 is too large
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 34 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] [IMGUTILS @ 0x7a31dfa628] Picture size 38024x55166 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 195 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 98 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 118 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 188 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] dqt: len 26041 is too large
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 57 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 105 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 85 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
W/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] Found EOI before any SOF, ignoring
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 1 line
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 218 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 2 lines
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 222 is invalid
W/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] Found EOI before any SOF, ignoring
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] dqt: len 24252 is too large
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 209 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 1 line
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 60 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 177 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
W/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] Found EOI before any SOF, ignoring
I/flutter (25343): 292
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 165 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 130 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 187 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 162 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 177 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 3 lines
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 4 lines
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 149 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 149 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 1 line
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 33 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 159 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 96 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 61 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 144 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 222 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 61 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 124 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 119 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
W/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] Found EOI before any SOF, ignoring
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 188 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 1 line
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 81 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 45 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 250 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 29 is invalid
I/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] Changing bps from 4 to 5
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] [IMGUTILS @ 0x7a31dfa628] Picture size 12515x64285 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 18 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 3 lines
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
I/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] Changing bps from 5 to 2
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] [IMGUTILS @ 0x7a31dfa628] Picture size 56261x35558 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 19 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] dqt: len 63253 is too large
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 120 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
I/flutter (25343): 292
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 17 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 87 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 250 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 233 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 35 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
W/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] Found EOI before any SOF, ignoring
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 185 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 1 line
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] dqt: len 10627 is too large
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] unable to decode APP fields: Invalid data found when processing input
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
I/chatty  (25343): uid=11225(com.gigatapp.aipix) Thread-4 identical 1 line
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] bits 252 is invalid
E/mobile-ffmpeg(25343): [mjpeg @ 0x7a339eec00] No JPEG data found in image
I/mobile-ffmpeg(25343): [image2 @ 0x7a409e0e00] decoding for stream 0 failed
W/mobile-ffmpeg(25343): [image2 @ 0x7a409e0e00] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown), lossless): unspecified size
W/mobile-ffmpeg(25343): Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
I/mobile-ffmpeg(25343): Input #0, image2, from '/storage/emulated/0/Android/data/com.gigatapp.aipix/files/videoframe_%04d.jpg':
I/mobile-ffmpeg(25343):   Duration: 
I/mobile-ffmpeg(25343): 00:00:11.83
I/mobile-ffmpeg(25343): , start: 
I/mobile-ffmpeg(25343): 0.000000
I/mobile-ffmpeg(25343): , bitrate: 
I/mobile-ffmpeg(25343): N/A
I/mobile-ffmpeg(25343): 
I/mobile-ffmpeg(25343):     Stream #0:0
I/mobile-ffmpeg(25343): : Video: mjpeg, none(bt470bg/unknown/unknown), lossless
I/mobile-ffmpeg(25343): , 
I/mobile-ffmpeg(25343): 24 fps, 
I/mobile-ffmpeg(25343): 24 tbr, 
I/mobile-ffmpeg(25343): 24 tbn, 
I/mobile-ffmpeg(25343): 24 tbc
I/mobile-ffmpeg(25343): 
E/mobile-ffmpeg(25343): [NULL @ 0x7a409e1400] Unable to find a suitable output format for 'ffmpeg'
E/mobile-ffmpeg(25343): ffmpeg: Invalid argument
**Environment**
Flutter doctor output
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (8 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

-

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at C:\Users\tanma\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • ANDROID_HOME = C:\Users\tanma\AppData\Local\Android\Sdk\platform-tools;
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • POCO F1 (mobile) • 192.168.1.65:5555 • android-arm64 • Android 9 (API 28)

• No issues found!

**Other**
    final dir = await getExternalStorageDirectory();
    final path = dir.path;
   this is the path variable 
Example input file path: 
/storage/emulated/0/Android/data/com.domain.package_name/files/videoframe_0000.jpg

**Comment by ljmatan** [comment]
You need to remove ffmpeg from the function string. 

Such as: 
```
await _flutterFFmpeg.execute(
      '-framerate 20 -i $_directory/image%d.png $_directory/out.mp4',
    );
```
