### ISSUE TITLE
Does it support xfade or other animation feature?

### ISSUE THREAD

**Issue by ming0520** [tanersener/flutter-ffmpeg#247]
Hi I need to add some transition effect for each trim of video. May I know is it support for any transition effect such as xfade or any other suggestion? Is it same as the Windows version ffmpeg?

I'm looking any way to build a crossfade tansition for each jointing of video.

**Comment by tanersener** [comment]
Technically xfade is there as other `ffmpeg` filters. But I haven't tested it. It may not be as fast as it is on other non-mobile platforms. You need to test it yourself.

**Comment by ming0520** [comment]
Thank you for the declaration, I will try it out.
