### ISSUE TITLE
Duplicate record returned by the statistics callback

### ISSUE THREAD

**Issue by rgb1380** [tanersener/flutter-ffmpeg#248]
**Description**
The first record returned to the statistics callback when a new execution starts is the same as the last record that was returned for the previous execution. Here is an example, note the bold lines where execution Id changes but the stats for the new execution are from one that had completed. 
**Logs**
I/flutter (26877): Statistics: executionId: 3022, time: 88541, size: 0, bitrate: 0.0, speed: 9.96, videoFrameNumber: 2125, videoQuality: 0.0, videoFps: 238.95
I/flutter (26877): Statistics: executionId: 3022, time: 5574, size: 0, bitrate: 0.0, speed: 11.14, videoFrameNumber: 127, videoQuality: 0.0, videoFps: 238.95
I/flutter (26877): Statistics: executionId: 3022, time: 9475, size: 0, bitrate: 0.0, speed: 9.44, videoFrameNumber: 220, videoQuality: 0.0, videoFps: 219.27
I/flutter (26877): Statistics: executionId: 3022, time: 14073, size: 0, bitrate: 0.0, speed: 9.36, videoFrameNumber: 331, videoQuality: 0.0, videoFps: 220.15
I/flutter (26877): Statistics: executionId: 3022, time: 17672, size: 0, bitrate: 0.0, speed: 8.78, videoFrameNumber: 417, videoQuality: 0.0, videoFps: 207.12
I/flutter (26877): Statistics: executionId: 3022, time: 22246, size: 0, bitrate: 0.0, speed: 8.8, videoFrameNumber: 527, videoQuality: 0.0, videoFps: 208.53
I/flutter (26877): Statistics: executionId: 3022, time: 27215, size: 0, bitrate: 0.0, speed: 8.99, videoFrameNumber: 646, videoQuality: 0.0, videoFps: 213.37
I/flutter (26877): Statistics: executionId: 3022, time: 32510, size: 0, bitrate: 0.0, speed: 9.18, videoFrameNumber: 773, videoQuality: 0.0, videoFps: 218.29
I/flutter (26877): Statistics: executionId: 3022, time: 37293, size: 0, bitrate: 0.0, speed: 9.23, videoFrameNumber: 888, videoQuality: 0.0, videoFps: 219.68
I/flutter (26877): Statistics: executionId: 3022, time: 41983, size: 0, bitrate: 0.0, speed: 9.24, videoFrameNumber: 1001, videoQuality: 0.0, videoFps: 220.36
I/flutter (26877): Statistics: executionId: 3022, time: 47533, size: 0, bitrate: 0.0, speed: 9.43, videoFrameNumber: 1133, videoQuality: 0.0, videoFps: 224.66
I/flutter (26877): Statistics: executionId: 3022, time: 52665, size: 0, bitrate: 0.0, speed: 9.5, videoFrameNumber: 1257, videoQuality: 0.0, videoFps: 226.75
I/flutter (26877): Statistics: executionId: 3022, time: 57471, size: 0, bitrate: 0.0, speed: 9.51, videoFrameNumber: 1372, videoQuality: 0.0, videoFps: 227.01
I/flutter (26877): Statistics: executionId: 3022, time: 62417, size: 0, bitrate: 0.0, speed: 9.52, videoFrameNumber: 1491, videoQuality: 0.0, videoFps: 227.46
I/flutter (26877): Statistics: executionId: 3022, time: 67641, size: 0, bitrate: 0.0, speed: 9.58, videoFrameNumber: 1616, videoQuality: 0.0, videoFps: 228.85
I/flutter (26877): Statistics: executionId: 3022, time: 73168, size: 0, bitrate: 0.0, speed: 9.67, videoFrameNumber: 1749, videoQuality: 0.0, videoFps: 231.26
I/flutter (26877): Statistics: executionId: 3022, time: 77858, size: 0, bitrate: 0.0, speed: 9.65, videoFrameNumber: 1862, videoQuality: 0.0, videoFps: 230.67
I/flutter (26877): Statistics: executionId: 3022, time: 82804, size: 0, bitrate: 0.0, speed: 9.66, videoFrameNumber: 1980, videoQuality: 0.0, videoFps: 230.92
I/flutter (26877): Statistics: executionId: 3022, time: 87402, size: 0, bitrate: 0.0, speed: 9.63, videoFrameNumber: 2089, videoQuality: 0.0, videoFps: 230.21
**I/flutter (26877): Statistics: executionId: 3022, time: 88541, size: 0, bitrate: 0.0, speed: 9.45, videoFrameNumber: 2125, videoQuality: 0.0, videoFps: 226.82
I/flutter (26877): Statistics: executionId: 3023, time: 88541, size: 0, bitrate: 0.0, speed: 9.45, videoFrameNumber: 2125, videoQuality: 0.0, videoFps: 226.82**
I/flutter (26877): Statistics: executionId: 3023, time: 2593, size: 0, bitrate: 0.0, speed: 5.18, videoFrameNumber: 77, videoQuality: 0.0, videoFps: 226.82
I/flutter (26877): Statistics: executionId: 3023, time: 4299, size: 0, bitrate: 0.0, speed: 4.29, videoFrameNumber: 132, videoQuality: 0.0, videoFps: 131.8
I/flutter (26877): Statistics: executionId: 3023, time: 6198, size: 0, bitrate: 0.0, speed: 4.12, videoFrameNumber: 191, videoQuality: 0.0, videoFps: 127.09
I/flutter (26877): Statistics: executionId: 3023, time: 7563, size: 0, bitrate: 0.0, speed: 3.77, videoFrameNumber: 238, videoQuality: 0.0, videoFps: 118.64
I/flutter (26877): Statistics: executionId: 3023, time: 9462, size: 0, bitrate: 0.0, speed: 3.76, videoFrameNumber: 294, videoQuality: 0.0, videoFps: 116.97
I/flutter (26877): Statistics: executionId: 3023, time: 11361, size: 0, bitrate: 0.0, speed: 3.77, videoFrameNumber: 354, videoQuality: 0.0, videoFps: 117.34
I/flutter (26877): Statistics: executionId: 3023, time: 13067, size: 0, bitrate: 0.0, speed: 3.72, videoFrameNumber: 409, videoQuality: 0.0, videoFps: 116.29
I/flutter (26877): Statistics: executionId: 3023, time: 14902, size: 0, bitrate: 0.0, speed: 3.71, videoFrameNumber: 468, videoQuality: 0.0, videoFps: 116.39
I/flutter (26877): Statistics: executionId: 3023, time: 17057, size: 0, bitrate: 0.0, speed: 3.77, videoFrameNumber: 529, videoQuality: 0.0, videoFps: 117.0
I/flutter (26877): Statistics: executionId: 3023, time: 18678, size: 0, bitrate: 0.0, speed: 3.72, videoFrameNumber: 584, videoQuality: 0.0, videoFps: 116.23
I/flutter (26877): Statistics: executionId: 3023, time: 20747, size: 0, bitrate: 0.0, speed: 3.75, videoFrameNumber: 646, videoQuality: 0.0, videoFps: 116.91
I/flutter (26877): Statistics: executionId: 3023, time: 22838, size: 0, bitrate: 0.0, speed: 3.79, videoFrameNumber: 708, videoQuality: 0.0, videoFps: 117.49
I/flutter (26877): Statistics: executionId: 3023, time: 24673, size: 0, bitrate: 0.0, speed: 3.78, videoFrameNumber: 764, videoQuality: 0.0, videoFps: 117.05
I/flutter (26877): Statistics: executionId: 3023, time: 26891, size: 0, bitrate: 0.0, speed: 3.83, videoFrameNumber: 830, videoQuality: 0.0, videoFps: 118.08
I/flutter (26877): Statistics: executionId: 3023, time: 28406, size: 0, bitrate: 0.0, speed: 3.68, videoFrameNumber: 851, videoQuality: 0.0, videoFps: 110.3

**Comment by tanersener** [comment]
Have you tried calling `resetStatistics` method before running a new command? It should fix this error.

**Comment by rgb1380** [comment]
> Have you tried calling `resetStatistics` method before running a new command? It should fix this error.

Thanks. It does fix the problem. It is still strange that one needs to call this and ffmpeg does not reset automatically.
