### ISSUE TITLE
[Question] Error during compiling iOS App - fatal error: 'mobileffmpeg/LogDelegate.h' file not found

### ISSUE THREAD

**Issue by kkdlau** [tanersener/flutter-ffmpeg#249]
**Description**
I know that there is similar issue on this, I still decide to open an issue(well, actually is a question) because I have tried the solution but I still cannot fix that.

I tried to run my iOS app, but during compilation, it said:
```
fatal error: 'mobileffmpeg/LogDelegate.h' file not found
    #include <mobileffmpeg/LogDelegate.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/dannylau/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.0/ios/Classes/FlutterExecuteDelegate.m:20:
    /Users/dannylau/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.0/ios/Classes/FlutterExecuteDelegate.h:21:9: fatal error: 'mobileffmpeg/ExecuteDelegate.h' file not found
    #import <mobileffmpeg/ExecuteDelegate.h>
```

I have tried solutions discussed in other similar issues (e.g. set iOS target to >= 9.3, cocopad install, etc), but still fail to solve the bug. And I have confirmed inside `iOS/Pods`, there is folder namely `mobile-ffmpeg-https`. And the folder structure of `mobile-ffmpeg-https` looks like below:

![](https://i.ibb.co/jvL6PvQ/Screenshot-2020-12-31-at-5-13-46-PM.png)

So, the header files do exits, but for some reasons xcode cannot find that. May I know how to solve the bug?

(I know it may feel annoying for keep asking this kind of question, but again I really need help)

**Comment by kkdlau** [comment]
Below is the content of Podfile:
```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

**Comment by dilberx** [comment]
how did you solve?

**Comment by dilberx** [comment]
@kkdlau

**Comment by kkdlau** [comment]
> @kkdlau

I didn’t remember how exactly I solved the bug, but I remembered that it actually had two problems:
1. I didn’t specify which package I use
2. I copied the setup function improperly (especially the indentation)


So you may need to check this two and see if you made the mistake I made

**Comment by kkdlau** [comment]
> @kkdlau

I didn’t remember how exactly I solved the bug, but I remembered that it actually had two problems:
1. I didn’t specify which package I use
2. I copied the setup function improperly (especially the indentation)


So you may need to check this two and see if you made the mistake I made

**Comment by dilberx** [comment]
1.where didn't u specify?podfile?
2.let me try that

**Comment by dilberx** [comment]
2. no hope
