### ISSUE TITLE
Unknown encoder 'libmp3lame'

### ISSUE THREAD

**Issue by ming0520** [tanersener/flutter-ffmpeg#254]
**Description**
I try to enable full-gpl-lts package. I install the flutter_ffmpeg by including the name of dependencies in pubspec.yml. version is ^0.3.0. But it just keep showing Unknown encoder 'libmp3lame'

mp3 format also not work
` -y -i /storage/emulated/0/Download/exampleLQ.mp4 -c:a libmp3lame -b:a 16k -ac 1 -ar 16000 -vn /storage/emulated/0/Android/data/com.zhongming.autoedit/files/exampleLQ.wav`

**Expected behavior**
Enable convert mp4 to mp3 by using libmp3lame

**Current behavior**
Unknown encoder 'libmp3lame'

**Screenshots**
Dependencies:
![image](https://user-images.githubusercontent.com/31769920/106386744-79771100-6411-11eb-9341-484443eb3ca4.png)

android/build.gradle
![image](https://user-images.githubusercontent.com/31769920/106386775-94e21c00-6411-11eb-84cc-649ec3be3a4e.png)

problem
![image](https://user-images.githubusercontent.com/31769920/106386790-a4616500-6411-11eb-8d24-2fd496ce7b1d.png)

**Logs**

**Environment**
flutter doctor summary 
![image](https://user-images.githubusercontent.com/31769920/106386719-577d8e80-6411-11eb-9f76-14152b90f792.png)

**Comment by tanersener** [comment]
I guess you're setting `ext.flutterFFmpegPackage` in the wrong `build.gradle` file. Please take a look at `build.gradle` files of the test application under the `example` folder. They enable `full` package in [this line](https://github.com/tanersener/flutter-ffmpeg/blob/master/example/android/build.gradle#L28).

**Comment by ming0520** [comment]
Thanks it solve the problem.
