### ISSUE TITLE
One problem found when using mobilevlckit + mobileffmpeg in combination

### ISSUE THREAD

**Issue by idompolo** [tanersener/flutter-ffmpeg#255]
You cannot play videos with flv extension.

It also gets bounced off of memory errors.

There seems to be a conflict between the ffmpeg version used by mobilevlckit and the specific library version used by the mobile_ffmpeg version.
Guess -> avformat_OpenDemux in avformat.c file used by mobilevlckit seems to crash..

Is there a solution?

I will provide a sample below.
https://github.com/idompolo/vlc_ffmpeg_test

**Comment by tanersener** [comment]
You have two `ffmpeg` implementations in your app. One comes from `flutter_ffmpeg`. Another one comes from `mobilevlckit`. The details are explained in this wiki page, https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application of `mobile-ffmpeg`, parent project of `flutter_ffmpeg`. I suggest applying solutions listed there.
