### ISSUE TITLE
Width/height problem 

### ISSUE THREAD

**Issue by febg11** [tanersener/flutter-ffmpeg#26]
**Description**
The width and height are occasionally flipped. I have noticed
"rotate" -> "90" and "displaymatrix" -> "rotation of -90.00 degrees" are present in the meta data returned.

**Expected behavior**
Is this a bug? if it is, is there a short term bug free method of using the rotate/display matrix to determine the true width/height of the video? 

**Current behavior**
The width and the height are sometimes opposite.

**Comment by tanersener** [comment]
Actually, `"displaymatrix" -> "rotation of -90.00 degrees"` is a `Side data`. Current versions do not have a `Side data` block, so `Side block` properties are stored in `Metadata` block. A new `Side data` block will be introduced in the upcoming releases.

Regarding your question, if `rotate` and/or `displaymatrix` properties are present for your file this means that your photo/video is rotated. But I don't know if having these properties means that width and height should be flipped or not. Maybe you should ask this question to [ffmpeg-user@ffmpeg.org](ffmpeg-user@ffmpeg.org) mailing list.

Besides, you can run your file with `ffprobe` if you want and see if its output is different than what you get from `mobile-ffmpeg`.

**Comment by febg11** [comment]
Hi tanersener,

Sorry I am only just replying but I ended up putting in some hacky code that used the rotate value to determine whether to compare with width < height or height < width to check whether the video was portrait or landscape. Then forgot about this problem. 

I remember running the ffprobe commands on windows as you suggested and the output was the same as android. So this is not a bug. I also emailed my question to ffmpeg-user@ffmpeg.org  but received no reply.

After all of this I now have another problem which may be a bug/missing feature. I have ran my code on an IOS device and when it gets to my portrait check the rotation key/value is not present in any of the  data returned like it is with android. I have tested this on ffprobe on windows with the same video and 90 degrees is returned in the side data.

Is there a reason why this is missing on IOS devices and will it be added in a update alongside the side data block in the near future? 

Thanks for your help.

**Comment by tanersener** [comment]
> I also emailed my question to [ffmpeg-user@ffmpeg.org](mailto:ffmpeg-user@ffmpeg.org) but received no reply.
> 

I can't see your e-mail on [ffmpeg-user archives](http://ffmpeg.org/pipermail/ffmpeg-user). Unfortunately, you must subscribe to the mailing list before posting a message. I guess you didn't subscribe before posting.

> Is there a reason why this is missing on IOS devices and will it be added in a update alongside the side data block in the near future?
> 
> Edit: I just thought could this be a problem with me not including a required package? Im not really sure how they work.

No, you don't need to include a package for this. 

There are two issues created about parsing in the parent project: tanersener/mobile-ffmpeg/issues/122 and tanersener/mobile-ffmpeg/issues/123. I think tanersener/mobile-ffmpeg/issues/122 is causing this. It is a bug and it is fixed in the development branch. Next planned release will include the fix for it. It will be published in the first week of July.
