### ISSUE TITLE
How to render with srt file?

### ISSUE THREAD

**Issue by ming0520** [tanersener/flutter-ffmpeg#261]
**Description**
i try to use
`ffmpeg -i example.mp4 -vf subtitles=sub.srt -c:a copy outfile.mp4`
to render with srt file, but the output video show nothing just the video. May i know what should i looking for and what i missing up?

Error Message
`I/flutter (23153): [Parsed_ass_0 @ 0x7957d79100] No usable fontconfig configuration file found, using fallback.
I/flutter (23153): [Parsed_ass_0 @ 0x7957d79100] 
I/flutter (23153): [Parsed_ass_0 @ 0x7957d79100] Using font provider fontconfig`

configuration
`onfiguration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android21-clang --cxx=aarch64-linux-android21-clang++ --extra-libs='-L/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-s`

**Expected behavior**
Subtitle shown in video

**Current behavior**
Subtitle does not show in video but it render successfully

**Comment by ming0520** [comment]
`I/flutter (23153): ffmpeg version v4.4-dev-416
I/flutter (23153):  Copyright (c) 2000-2020 the FFmpeg developers
I/flutter (23153): 
I/flutter (23153):   built with Android (6454773 based on r365631c2) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489587874b2a325e7a516b99d838599c6f) (based on LLVM 9.0.8svn)
I/flutter (23153):   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android21-clang --cxx=aarch64-linux-android21-clang++ --extra-libs='-L/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-s
I/flutter (23153):   libavutil      56. 55.100 / 56. 55.100
I/flutter (23153):   libavcodec     58. 96.100 / 58. 96.100
I/flutter (23153):   libavformat    58. 48.100 / 58. 48.100
I/flutter (23153):   libavdevice    58. 11.101 / 58. 11.101
I/flutter (23153):   libavfilter     7. 87.100 /  7. 87.100
I/flutter (23153):   libswscale      5.  8.100 /  5.  8.100
I/flutter (23153):   libswresample   3.  8.100 /  3.  8.100
D/flutter-ffmpeg(23153): FFmpeg exited with rc: 0
I/flutter (23153): Input #0, srt, from '/storage/emulated/0/Android/data/com.zhongming.autoedit/files/sub.srt':
I/flutter (23153):   Duration: 
I/flutter (23153): N/A
I/flutter (23153): , bitrate: 
I/flutter (23153): N/A
I/flutter (23153): 
I/flutter (23153):     Stream #0:0
I/flutter (23153): : Subtitle: subrip
I/flutter (23153): 
I/flutter (23153): Output #0, ass, to '/storage/emulated/0/Android/data/com.zhongming.autoedit/files/sub.ass':
I/flutter (23153):   Metadata:
I/flutter (23153):     encoder         : 
I/flutter (23153): Lavf58.48.100
I/flutter (23153): 
I/flutter (23153):     Stream #0:0
I/flutter (23153): : Subtitle: ass (ssa)
I/flutter (23153): 
I/flutter (23153):     Metadata:
I/flutter (23153):       encoder         : 
I/flutter (23153): Lavc58.96.100 ssa
I/flutter (23153): 
I/flutter (23153): Stream mapping:
I/flutter (23153):   Stream #0:0 -> #0:0
I/flutter (23153):  (subrip (srt) -> ass (ssa))
I/flutter (23153): 
I/flutter (23153): Press [q] to stop, [?] for help
I/flutter (23153): Statistics: executionId: 0, time: 15680, size: 685, bitrate: 97.86, speed: 4.19, videoFrameNumber: 471, videoQuality: 29.0, videoFps: 180.76
I/flutter (23153): size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    
I/flutter (23153): Statistics: executionId: 0, time: 13800, size: 1079, bitrate: 0.63, speed: 9949.53, videoFrameNumber: 471, videoQuality: 29.0, videoFps: 180.76
I/flutter (23153): size=       1kB time=00:00:13.80 bitrate=   0.6kbits/s speed=9.95e+03x    
I/flutter (23153): video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:1kB muxing overhead: 
I/flutter (23153): 213.662796%
I/flutter (23153): 
D/flutter-ffmpeg(23153): Running FFmpeg with arguments: [-y, -i, /storage/emulated/0/Android/data/com.zhongming.autoedit/files/exampleLQ_EDITED_4_temp.mp4, -vf, subtitles=/storage/emulated/0/Android/data/com.zhongming.autoedit/files/sub.srt, /storage/emulated/0/Android/data/com.zhongming.autoedit/files/exampleLQ_EDITED_4.mp4].
I/flutter (23153): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/Android/data/com.zhongming.autoedit/files/exampleLQ_EDITED_4_temp.mp4':
I/flutter (23153):   Metadata:
I/flutter (23153):     major_brand     : 
I/flutter (23153): isom
I/flutter (23153): 
I/flutter (23153):     minor_version   : 
I/flutter (23153): 512
I/flutter (23153): 
I/flutter (23153):     compatible_brands: 
I/flutter (23153): isomiso2avc1mp41
I/flutter (23153): 
I/flutter (23153):     encoder         : 
I/flutter (23153): Lavf58.48.100
I/flutter (23153): 
I/flutter (23153):   Duration: 
I/flutter (23153): 00:00:15.69
I/flutter (23153): , start: 
I/flutter (23153): 0.000000
I/flutter (23153): , bitrate: 
I/flutter (23153): 97 kb/s
I/flutter (23153): 
I/flutter (23153):     Stream #0:0
I/flutter (23153): (und)
I/flutter (23153): : Audio: aac (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 70 kb/s
I/flutter (23153):  (default)
I/flutter (23153): 
I/flutter (23153):     Metadata:
I/flutter (23153):       handler_name    : 
I/flutter (23153): SoundHandler
I/flutter (23153): 
I/flutter (23153):     Stream #0:1
I/flutter (23153): (und)
I/flutter (23153): : Video: h264 (avc1 / 0x31637661), yuv420p, 384x288 [SAR 4:3 DAR 16:9], 18 kb/s
I/flutter (23153): , 
I/flutter (23153): 30 fps, 
I/flutter (23153): 30 tbr, 
I/flutter (23153): 15360 tbn, 
I/flutter (23153): 60 tbc
I/flutter (23153):  (default)
I/flutter (23153): 
I/flutter (23153):     Metadata:
I/flutter (23153):       handler_name    : 
I/flutter (23153): VideoHandler
I/flutter (23153): 
I/flutter (23153): Stream mapping:
I/flutter (23153):   Stream #0:1 -> #0:0
I/flutter (23153):  (h264 (native) -> h264 (libx264))
I/flutter (23153): 
I/flutter (23153):   Stream #0:0 -> #0:1
I/flutter (23153):  (aac (native) -> aac (native))
I/flutter (23153): 
I/flutter (23153): Press [q] to stop, [?] for help
I/flutter (23153): [Parsed_subtitles_0 @ 0x7925bff280] Shaper: FriBidi 1.0.9 (SIMPLE)
I/flutter (23153): [Parsed_subtitles_0 @ 0x7925bff280] 
I/flutter (23153): [Parsed_subtitles_0 @ 0x7925bff280] No usable fontconfig configuration file found, using fallback.
I/flutter (23153): [Parsed_subtitles_0 @ 0x7925bff280] 
I/flutter (23153): [Parsed_subtitles_0 @ 0x7925bff280] Using font provider fontconfig
I/flutter (23153): [Parsed_subtitles_0 @ 0x7925bff280] 
I/flutter (23153): [graph 0 input from stream 0:1 @ 0x7925bff700] sws_param option is deprecated and ignored
I/flutter (23153): [libx264 @ 0x79255fb500] using SAR=4/3
I/flutter (23153): [libx264 @ 0x79255fb500] using cpu capabilities: ARMv8 NEON
I/flutter (23153): [libx264 @ 0x79255fb500] profile High, level 2.1, 4:2:0, 8-bit
I/flutter (23153): [libx264 @ 0x79255fb500] 264 - core 160 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=9 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
I/flutter (23153): Output #0, mp4, to '/storage/emulated/0/Android/data/com.zhongming.autoedit/files/exampleLQ_EDITED_4.mp4':
I/flutter (23153):   Metadata:
I/flutter (23153):     major_brand     : 
I/flutter (23153): isom
I/flutter (23153): 
I/flutter (23153):     minor_version   : 
I/flutter (23153): 512
I/flutter (23153): 
I/flutter (23153):     compatible_brands: 
I/flutter (23153): isomiso2avc1mp41
I/flutter (23153): 
I/flutter (23153):     encoder         : 
I/flutter (23153): Lavf58.48.100
I/flutter (23153): 
I/flutter (23153):     Stream #0:0
I/flutter (23153): (und)
I/flutter (23153): : Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 384x288 [SAR 4:3 DAR 16:9], q=-1--1
I/flutter (23153): , 
I/flutter (23153): 30 fps, 
I/flutter (23153): 15360 tbn, 
I/flutter (23153): 30 tbc
I/flutter (23153):  (default)
I/flutter (23153): 
I/flutter (23153):     Metadata:
I/flutter (23153):       handler_name    : 
I/flutter (23153): VideoHandler
I/flutter (23153): 
I/flutter (23153):       encoder         : 
I/flutter (23153): Lavc58.96.100 libx264
I/flutter (23153): 
I/flutter (23153):     Side data:
I/flutter (23153):       
I/flutter (23153): cpb: 
I/flutter (23153): bitrate max/min/avg: 0/0/0 buffer size: 0 
I/flutter (23153): vbv_delay: N/A
I/flutter (23153): 
I/flutter (23153):     Stream #0:1
I/flutter (23153): (und)
I/flutter (23153): : Audio: aac (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 69 kb/s
I/flutter (23153):  (default)
I/flutter (23153): 
I/flutter (23153):     Metadata:
I/flutter (23153):       handler_name    : 
I/flutter (23153): SoundHandler
I/flutter (23153): 
I/flutter (23153):       encoder         : 
I/flutter (23153): Lavc58.96.100 aac
I/flutter (23153): 
I/flutter (23153): Statistics: executionId: 0, time: 1749, size: 48, bitrate: 0.22, speed: 3.71, videoFrameNumber: 46, videoQuality: 29.0, videoFps: 180.76
I/flutter (23153): frame=   46 fps=0.0 q=0.0 size=       0kB time=00:00:01.74 bitrate=   0.2kbits/s speed=3.71x    
I/flutter (23153): Statistics: executionId: 0, time: 4885, size: 48, bitrate: 0.08, speed: 5.01, videoFrameNumber: 140, videoQuality: 29.0, videoFps: 180.76
I/flutter (23153): frame=  140 fps=0.0 q=29.0 size=       0kB time=00:00:04.88 bitrate=   0.1kbits/s speed=5.01x    
I/flutter (23153): Statistics: executionId: 0, time: 8896, size: 48, bitrate: 0.04, speed: 6.02, videoFrameNumber: 260, videoQuality: 29.0, videoFps: 176.01
I/flutter (23153): frame=  260 fps=176 q=29.0 size=       0kB time=00:00:08.89 bitrate=   0.0kbits/s speed=6.02x    
I/flutter (23153): Statistics: executionId: 0, time: 12714, size: 48, bitrate: 0.03, speed: 6.43, videoFrameNumber: 375, videoQuality: 29.0, videoFps: 189.56
I/flutter (23153): frame=  375 fps=190 q=29.0 size=       0kB time=00:00:12.71 bitrate=   0.0kbits/s speed=6.43x    
I/flutter (23153): Statistics: executionId: 0, time: 15680, size: 192298, bitrate: 98.11, speed: 6.02, videoFrameNumber: 470, videoQuality: 29.0, videoFps: 180.4
I/flutter (23153): frame=  470 fps=180 q=-1.0 Lsize=     188kB time=00:00:15.68 bitrate=  98.1kbits/s speed=6.02x    
I/flutter (23153): video:34kB audio:136kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
I/flutter (23153): 10.622264%
I/flutter (23153): 
I/flutter (23153): [libx264 @ 0x79255fb500] frame I:2     Avg QP: 9.15  size:  1101
D/flutter-ffmpeg(23153): FFmpeg exited with rc: 0
I/flutter (23153): [libx264 @ 0x79255fb500] frame P:141   Avg QP:12.06  size:   123
I/flutter (23153): [libx264 @ 0x79255fb500] frame B:327   Avg QP:15.22  size:    44
I/flutter (23153): [libx264 @ 0x79255fb500] consecutive B-frames:  3.4%  7.2% 12.8% 76.6%
I/flutter (23153): [libx264 @ 0x79255fb500] mb I  I16..4: 95.8%  0.0%  4.2%
I/flutter (23153): [libx264 @ 0x79255fb500] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  0.6%  0.4%  0.3%  0.0%  0.0%    skip:98.6%
I/flutter (23153): [libx264 @ 0x79255fb500] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  0.7%  0.2%  0.1%  direct: 0.1%  skip:98.9%  L0:45.4% L1:52.3% BI: 2.3%
I/flutter (23153): [libx264 @ 0x79255fb500] 8x8 transform intra:1.5% inter:29.0%
I/flutter (23153): [libx264 @ 0x79255fb500] coded y,uvDC,uvAC intra: 5.8% 10.4% 8.3% inter: 0.2% 0.5% 0.3%
I/flutter (23153): [libx264 @ 0x79255fb500] i16 v,h,dc,p: 92%  3%  6%  0%
I/flutter (23153): [libx264 @ 0x79255fb500] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12% 34% 38%  2%  0%  4%  2%  5%  4%
I/flutter (23153): [libx264 @ 0x79255fb500] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 14% 30%  3%  5%  5%  2%  6%  3%
I/flutter (23153): [libx264 @ 0x79255fb500] i8c dc,h,v,p: 92%  4%  4%  0%
I/flutter (23153): [libx264 @ 0x79255fb500] Weighted P-Frames: Y:0.7% UV:0.7%
I/flutter (23153): [libx264 @ 0x79255fb500] ref P L0: 62.4%  6.2% 21.0% 10.3%  0.2%
I/flutter (23153): [libx264 @ 0x79255fb500] ref B L0: 77.9% 17.3%  4.8%
I/flutter (23153): [libx264 @ 0x79255fb500] ref B L1: 93.6%  6.4%
I/flutter (23153): [libx264 @ 0x79255fb500] kb/s:17.29
I/flutter (23153): [aac @ 0x7924c94100] Qavg: 476.792`

**Comment by MahmoudAshours** [comment]
Anyone solved this issue?
