### ISSUE TITLE
How to extract frames from a video?

### ISSUE THREAD

**Issue by piyushchauhan** [tanersener/flutter-ffmpeg#262]
**Description**
There is no provision to extract frames from a video.

**Expected behavior**
I should be able to extract each frame from the video.

**Current behavior**
I could not find anything that gives me a stream of frames from the video.

**Use case**
I want to process each frame of the video and pass it into a TF Lite model and gather results.

**Comment by ming0520** [comment]
Are you trying split the video into individual image for each frame?

**Comment by piyushchauhan** [comment]
> Are you trying split the video into individual image for each frame?

Yes

**Comment by piyushchauhan** [comment]
I am still in need of this feature

**Comment by tanersener** [comment]
This plugin is `react-native` port of `ffmpeg`. It allows you to run `ffmpeg` commands in your `react-native` application. 

There are a lot of resources to `extract frames using ffmpeg` on the web. Please google them and try running commands given there using this plugin.
