### ISSUE TITLE
the app crash

### ISSUE THREAD

**Issue by ming0520** [tanersener/flutter-ffmpeg#263]
**Description**
It successfully running in debug mode, but the app crash in release mode. but it work well in debug mode

**Version**
flutter_ffmpeg: ^0.3.0
ext { flutterFFmpegPackage = "full-gpl" }

**Expected behavior**
convert video to wav audio by using mp3 codec

**Logs**
I/flutter (20744): Loading flutter-ffmpeg.
E/AndroidRuntime(20744): FATAL EXCEPTION: main
E/AndroidRuntime(20744): Process: com.ming.autoedit, PID: 20744
E/AndroidRuntime(20744): java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/com.ming.autoedit-BhmRGwpcTTB1n-Q7Wir0Pg==/lib/arm64/libmobileffmpeg.so": 0
E/AndroidRuntime(20744): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
E/AndroidRuntime(20744): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime(20744): 	at java.lang.System.loadLibrary(System.java:1668)
E/AndroidRuntime(20744): 	at com.arthenica.mobileffmpeg.Config.<clinit>(Unknown Source:148)
E/AndroidRuntime(20744): 	at com.arthenica.mobileffmpeg.Config.a(Unknown Source:0)
E/AndroidRuntime(20744): 	at d.a.a.a.d.a(Unknown Source:323)
E/AndroidRuntime(20744): 	at f.a.c.a.j$a.a(Unknown Source:17)
E/AndroidRuntime(20744): 	at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
E/AndroidRuntime(20744): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/AndroidRuntime(20744): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(20744): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/AndroidRuntime(20744): 	at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(20744): 	at android.app.ActivityThread.main(ActivityThread.java:8349)
E/AndroidRuntime(20744): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20744): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(20744): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Environment**
![image](https://user-images.githubusercontent.com/31769920/108629034-035a4d00-7499-11eb-92e6-ab32c664a781.png)

I'm still trying to solve the issues
related topic
https://github.com/tanersener/flutter-ffmpeg/issues/257
https://github.com/tanersener/flutter-ffmpeg#5-tips
https://github.com/tanersener/flutter-ffmpeg/issues/237

**Comment by kamalgayan** [comment]
I faced the same issue. I fix this by following this steps -->

1. Make targetSdkVersion  to 28
             
       if still not worked than try this steps


1.under app level build gradle add this

android {
    packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
    }
}

2. Add this to your proguard-rules.pro -->
 
-keep class com.arthenica.mobileffmpeg.Config {
      native <methods>;
      void log(int, byte[]);
      void statistics(int, float, float, long , int, double, double);
  }

**Comment by 76765357** [comment]
also crash on android, using above method not work :(
same problem

**Comment by viral-sangani** [comment]
I am having the same issue for past 5 days. Above solution does not work for me.
Does anyone have any other solution.

**Comment by tanersener** [comment]
If you have issues on Android release mode, please read [Tips](https://github.com/tanersener/flutter-ffmpeg#5-tips) or have a look at the solution posted in #237. And do not forget to clean your `gradle` cache before testing it. If that doesn't work you then I suggest creating another issue and providing details about the error you see.
