### ISSUE TITLE
Lossless Compression

### ISSUE THREAD

**Issue by rupamking1** [tanersener/flutter-ffmpeg#265]
Please add Lossless Compression feature.

**Comment by thegrxp** [comment]
It's your job to set the right command for your needs

**Comment by rupamking1** [comment]
please tell me commend

**Comment by thegrxp** [comment]
You can find basic explanation here
https://ostechnix.com/20-ffmpeg-commands-beginners/

And then the documentation will help you set the right command for your needs
https://ffmpeg.org/ffmpeg.html

**Comment by rupamking1** [comment]
no
