### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by Sulisong** [tanersener/flutter-ffmpeg#266]
would be great to have null safety enabled early

**Comment by tanersener** [comment]
I plan to support it when it is enabled in `stable` channel.

**Comment by szymonmazanik** [comment]
Hello,
@tanersener as of yesterday the null safety is in stable channel. Could we kindly ask for migration? 

Thanks!

**Comment by tanersener** [comment]
Will do when I find time. Feel free to submit PRs for it.

**Comment by zigyshop** [comment]
This will be awesome because of the release of Flutter 2.0.  Right now, when using 2.0, the flutter package selection is impossible to override.

**Comment by nukes** [comment]
can  version 0.3.1 run correctly with flutter 2.0 ? I cannot setup compilation on ios.

**Comment by tanersener** [comment]
@nukes yes, you can use it on Flutter 2.0. If you're using packages see #268

**Comment by shofizone** [comment]
Waiting for sound null safety !

**Comment by Sulisong** [comment]
linked a pull request that will close this issue
#275

**Comment by tanersener** [comment]
Thanks to @ibedek's PR, this is implemented in the `v0.4.0`.
