### ISSUE TITLE
I want to get the belief information of the video, what I passed in was an mp4, but what I got was audio

### ISSUE THREAD

**Issue by maskletter** [tanersener/flutter-ffmpeg#267]
**Description**
I want to get the belief information of the video, what I passed in was an mp4, but what I got was audio
The videos from weixin(china 微信) are all like this

**Logs**
```
{r_frame_rate: 0/0, start_pts: 0, channel_layout: stereo, duration_ts: 229376, duration: 5.201270, bit_rate: 128001, codec_tag_string: mp4a, avg_frame_rate: 0/0, nb_frames: 224, codec_long_name: unknown, time_base: 1/44100, profile: 1, index: 0, max_bit_rate: 133680, codec_name: aac, tags: {creation_time: 2021-02-02T03:44:41.000000Z, language: und}, start_time: 0.000000, disposition: {dub: 0, karaoke: 0, default: 1, original: 0, visual_impaired: 0, forced: 0, attached_pic: 0, timed_thumbnails: 0, comment: 0, hearing_impaired: 0, lyrics: 0, clean_effects: 0}, codec_tag: 0x6134706d, sample_rate: 44100, channels: 2, sample_fmt: fltp, codec_time_base: 1/44100, bits_per_sample: 0, 
codec_type: audio}
```

**Environment**
flutter_ffmpeg: ^0.3.1
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (3 months ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Other**
![image](https://user-images.githubusercontent.com/15777183/109824533-e2051800-7c73-11eb-8aa9-2c4e41d1c522.png)

**Comment by maskletter** [comment]
Sorry, I tried again, not all of them，The video shot through WeChat will look like this

**Comment by tanersener** [comment]
Would you mind explaining which `flutter_ffmpeg` method you call? What are the parameters used? If you can share one of those `.mp4` files that would be great too.

**Comment by maskletter** [comment]
Sorry to reply so late，

```
_flutterFFprobe.getMediaInformation(file.path).then((value) {
      var stream = value.getAllProperties()['streams'][0];
      if (stream['codec_type'] == 'auido') {
        Tool.toast('error');
        return;
      }
      videoSize = Size(stream['width'].toDouble(), stream['height'].toDouble());
      print(videoSize);
 });
```

[video.mp4](https://github.com/maskletter/element-ts-admin/blob/master/public/1614784141762.mp4)

**Comment by tanersener** [comment]
There are two streams in your file. The first one is an `audio` stream and the second one is a `video` stream. You are getting the first one and not checking the second one. Use `['streams'][1]` to get it.

```
Stream index: 0
Stream type: audio
Stream codec: aac
Stream full codec: unknown
Stream bitrate: 65100
Stream sample rate: 44100
Stream sample format: fltp
Stream channel layout: mono
Stream average frame rate: 0/0
Stream real frame rate: 0/0
Stream time base: 1/44100
Stream codec time base: 1/44100
Stream tag: creation_time:2021-03-03T15:08:55.000000Z
Stream tag: language:und
---
Stream index: 1
Stream type: video
Stream codec: h264
Stream full codec: unknown
Stream format: yuv420p
Stream width: 464
Stream height: 960
Stream bitrate: 1615080
Stream average frame rate: 157500/6571
Stream real frame rate: 24000/1001
Stream time base: 1/90000
Stream codec time base: 6571/315000
Stream tag: encoder:JVT/AVC Coding
Stream tag: creation_time:2021-03-03T15:08:55.000000Z
Stream tag: language:und

```

**Comment by maskletter** [comment]
Sorry, will this streams return multiple values with codec_type=video?

**Comment by maskletter** [comment]
Sorry, will streams return multiple codec_type = video?

**Comment by maskletter** [comment]
> 您的文件中有两个流。第一个是`audio`流，第二个是`video`流。您正在获取第一个，而不检查第二个。请使用`['streams'][1]`它。
> 
> ```
> Stream index: 0
> Stream type: audio
> Stream codec: aac
> Stream full codec: unknown
> Stream bitrate: 65100
> Stream sample rate: 44100
> Stream sample format: fltp
> Stream channel layout: mono
> Stream average frame rate: 0/0
> Stream real frame rate: 0/0
> Stream time base: 1/44100
> Stream codec time base: 1/44100
> Stream tag: creation_time:2021-03-03T15:08:55.000000Z
> Stream tag: language:und
> ---
> Stream index: 1
> Stream type: video
> Stream codec: h264
> Stream full codec: unknown
> Stream format: yuv420p
> Stream width: 464
> Stream height: 960
> Stream bitrate: 1615080
> Stream average frame rate: 157500/6571
> Stream real frame rate: 24000/1001
> Stream time base: 1/90000
> Stream codec time base: 6571/315000
> Stream tag: encoder:JVT/AVC Coding
> Stream tag: creation_time:2021-03-03T15:08:55.000000Z
> Stream tag: language:und
> ```

Sorry, will streams return multiple codec_type = video?

**Comment by tanersener** [comment]
No, two streams. One has audio type and the other has video type. See my output.

```
Stream type: audio
...
Stream type: video
```

**Comment by maskletter** [comment]
Thanks for your answer
