### ISSUE TITLE
Unrecognized option 'preset' error in upgraded Flutter version 2.0.1

### ISSUE THREAD

**Issue by ffriande** [tanersener/flutter-ffmpeg#270]
**Description**
When upgrading Flutter to version 2.0.1, now I get the following error logs when trying to run on iOS

> 2021-03-09 11:51:39.068999+0000 Runner[651:77167] flutter: Loaded flutter-ffmpeg-ios-arm64.
2021-03-09 11:51:39.069900+0000 Runner[651:77167] flutter: Unrecognized option 'preset'.
2021-03-09 11:51:39.070805+0000 Runner[651:77167] flutter: Error splitting the argument list:
2021-03-09 11:51:39.071713+0000 Runner[651:77167] flutter: Option not found
2021-03-09 11:51:39.072642+0000 Runner[651:77167] flutter: FFmpeg process exited with rc 1

I'm using /min-gpl-lts but I've also tried with /min-gpl and the command I'm running is 

`"-loglevel error -y -i ${video.path} -vcodec libx264 -vprofile high -preset veryfast -b:v 1000k -maxrate 1000k -bufsize 1000k -vf \"pad=ceil(iw/2) * 2:ceil(ih/2)*2\" -threads 1 -b:a 128k ${outputPath}"`

I also followed the instructions from [this issue](https://github.com/tanersener/flutter-ffmpeg/issues/268#issuecomment-791526747)  for upgrading Podfile.

[My Podfile here](https://ghostbin.co/paste/j6nh5p)

**Expected behavior**
Command should run successfully like it did before, on Flutter version 1.22.6

**Current behavior**
Unrecognized option 'preset' error is thrown

**Logs**
Logs are stated above

> [✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale
    en-PT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

**Comment by ffriande** [comment]
I am using flutter_ffmpeg version 0.4.0 by the way. I can't seem to solve this problem by any means... 
Can anyone help?

**Comment by tanersener** [comment]
There is a test application under the `example` folder which uses `audio-lts` package and runs successfully on `Flutter 2.x`. I suggest looking at it.

**Comment by ffriande** [comment]
Still no luck, I have updated my [Podfile](https://pastebin.com/G0c246BZ) to look more like the one on the `example` folder and, still, same error occurs. Any other thoughts?

**Comment by ffriande** [comment]
> There is a test application under the `example` folder which uses `audio-lts` package and runs successfully on `Flutter 2.x`. I suggest testing it and comparing its `Podfile` file with yours.

I did not only compare it, I also ran the ```example``` project, placed videos in the container and tried running the command below on those videos

> -loglevel error -y -i ${video.path} -vcodec libx264 -vprofile high -preset veryfast -b:v 1000k -maxrate 1000k -bufsize 1000k -vf \"pad=ceil(iw/2) * 2:ceil(ih/2)*2\" -threads 1 -b:a 128k ${outputPath}

Still, I had the same problem: ```Unrecognized option 'preset'.``` as, the command fails.

I remind you that this is preventing me to upgrade my app to flutter 2.x, please help...

**Comment by ffriande** [comment]
@tanersener Any idea why this command is not working?

**Comment by ffriande** [comment]
I haven't read carefully enough the fix [in this issue](https://github.com/tanersener/flutter-ffmpeg/issues/268#issuecomment-791526747). It's solved now
