### ISSUE TITLE
Plugin size increased by twice the previous size.

### ISSUE THREAD

**Issue by Kabilan21** [tanersener/flutter-ffmpeg#274]
After the release of flutter 2.0 , the flutter ffmpeg in min-gpl version is almost twice the size before.

**Comment by MoacirSchmidt** [comment]
I also would really like to see an answer for this question! That also happened here

**Comment by Kabilan21** [comment]
I solved the problem by reducing the build gradle to 'com.android.tools.build:gradle:3.5.0' in project level build.gradle file.
