### ISSUE TITLE
Protocol 'https' not on whitelist 'concat,file,subfile'!

### ISSUE THREAD

**Issue by rdcoder33** [tanersener/flutter-ffmpeg#278]
I am trying to convert network images to a video using flutter_ffmpeg. But I get following error:

```
final gifOutputFile = gifDirectory.path +
                      '/' +
                      DateTime.now().millisecondsSinceEpoch.toString() +
                      '.mp4';
                  _flutterFFmpeg
                      .execute(
                          "-i concat:https://cnet1.cbsistatic.com/img/9ZWP41CYVU8-yWvmNPBR3LBWLLA=/1200x630/2020/08/18/b7168aea-9f7e-47bb-9f31-4cb8ad92fbc7/lg-note-20-ultra-5g-iphone-11-se-google-pixel-4a-lg-velvet-6133.jpg | https://i.ytimg.com/vi/aeQnQ-vjtuY/maxresdefault.jpg|https://s3b.cashify.in/gpro/uploads/2020/08/11220706/top-10-non-china-smartphones.jpg|https://cdn57.androidauthority.net/wp-content/uploads/2020/07/Google-Pixel-4a-upper-half-of-display-with-apps-1200x675.jpg | https://www.tipsclear.in/wp-content/uploads/2020/11/1605643715_How-to-Choose-a-Smartphone-by-Brand-Carrier-or-Features.jpg | https://www.ephotozine.com/articles/18-things-to-look-out-for-in-a-smartphone-camera--31055/images/highres-Samsung-Galaxy-S8-vs-Google-Pixel-2-XL-vs-Galaxy-S9-Plus-3_1522064639.jpg mp4 $gifOutputFile")
                      .then((rc) => print("FFmpeg process exited with rc $rc"));
```
---------------------------------------------------------------------------------------------------------

I/mobile-ffmpeg( 4453):   libavutil      56. 55.100 / 56. 55.100
I/mobile-ffmpeg( 4453):   libavcodec     58. 96.100 / 58. 96.100
I/mobile-ffmpeg( 4453):   libavformat    58. 48.100 / 58. 48.100
I/mobile-ffmpeg( 4453):   libavdevice    58. 11.101 / 58. 11.101
I/mobile-ffmpeg( 4453):   libavfilter     7. 87.100 /  7. 87.100
I/mobile-ffmpeg( 4453):   libswscale      5.  8.100 /  5.  8.100
I/mobile-ffmpeg( 4453):   libswresample   3.  8.100 /  3.  8.100
E/UIFirst ( 4453): failed to open /proc/4453/stuck_info, No such file or directory
D/flutter-ffmpeg( 4453): FFmpeg exited with rc: 1

**Comment by g7i** [comment]
@rdcoder33 Use `-protocol_whitelist file,http,https,tcp,tls,crypto` in the very beginning of your command. 
E.g. - `
    .execute(
                          "-protocol_whitelist file,http,https,tcp,tls,crypto -i concat.....
`

**Comment by rdcoder33** [comment]
> @rdcoder33 Use `-protocol_whitelist file,http,https,tcp,tls,crypto` in the very beginning of your command.
> E.g. - `.execute( "-protocol_whitelist file,http,https,tcp,tls,crypto -i concat.....`

Thanks for the reply but still getting the error:

`Protocol 'concat' not on whitelist 'file,http,https,tcp,tls,crypto'!`

Is there any other way in FFmpeg to make a video from network files?

**Comment by g7i** [comment]
Then add `concat` as well in protocols.
Eg - `-protocol_whitelist concat,file,http,https,tcp,tls,crypto`

**Comment by rdcoder33** [comment]
> Then add `concat` as well in protocols.
> Eg - `-protocol_whitelist concat,file,http,https,tcp,tls,crypto`

Yeah this works!
