### ISSUE TITLE
Crashes when downloaded from Play Store

### ISSUE THREAD

**Issue by sakofchit** [tanersener/flutter-ffmpeg#283]
**Description**
The plugin works fine for me on both iOS + Android and if I create a release and debug APK for android the plugin works as intended. However, when I create an app bundle, upload it to Google Play, and install it from there, the plugin causes the app to crash and I can't quite figure out why. This happens when I try importing a song from my local library.

**Current behavior**
App crashes when trying to import song from local library.

**Expected Behavior**
Import song from local library

**Logs**
```
FATAL EXCEPTION: AsyncTask #2
Process: co.retro.app, PID: 12532
java.lang.RuntimeException: An error occurred while executing doInBackground()
 at android.os.AsyncTask$3.done(AsyncTask.java:354)
 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
 at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
 at java.util.concurrent.FutureTask.run(FutureTask.java:271)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/co.retro.app-mdH127k4dZAYVcSAELFpbg==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmobileffmpeg.so": 0
 at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
 at java.lang.System.loadLibrary(System.java:1669)
 at com.arthenica.mobileffmpeg.Config.<clinit>(Unknown Source:148)
 at com.arthenica.mobileffmpeg.Config.nativeFFprobeExecute(Native Method)
 at com.arthenica.mobileffmpeg.f.a(Unknown Source:0)
 at com.arthenica.mobileffmpeg.f.b(Unknown Source:0)
 at com.arthenica.mobileffmpeg.f.a(Unknown Source:48)
 at c.a.a.a.c.a(Unknown Source:21)
 at c.a.a.a.c.doInBackground(Unknown Source:2)
 at android.os.AsyncTask$2.call(AsyncTask.java:333)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 ... 3 more
```

**Environment**
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.4 19E2265 x86_64, locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/sakun/Developer/flutter
    • Framework revision 198df796aa (5 months ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sakun/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

 
[✓] Connected device (3 available)            
    • G5 (mobile)      • 7040018020066448 • android-arm64  • Android 9 (API 28)
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

```

**Other**
For context, I'm using this plugin to fetch local audio for a music player app. I added mavenCentral() before jcenter() and I'm still getting the same error. (Using v0.3 btw)

I already saw the tips section and other issues with the same error, but nothing seems to work for me :(

Would appreciate any help cause I'm stumped. I did see the proguard workaround––is using proguard necessary? I'm not using proguard in my app.

**Comment by tanersener** [comment]
- Sometimes adding `mavenCentral()` before `jcenter()` is not enough. You may still have an old binary in your cache. I suggest deleting your `gradle` and `flutter` caches as well. The fix for `Bad JNI version returned from JNI_OnLoad` error is published on `2021`. So, if you have the fixed release the following string will be printed on console. See the date in the end, `20210207`. If your application prints something starting with `2020` you're still using an old version which has the bug inside.

    ```
    Loaded mobile-ffmpeg-full-x86-4.4-lts-20210207.
    ```

- `Bad JNI version returned from JNI_OnLoad` error is received because of a bug about `proguard`. You may not use `proguard` in your app but libraries that `flutter_ffmpeg` depends on use it. So, I suggest trying the workaround if cleaning the cache doesn't work for you.

**Comment by AbhishekDoshi26** [comment]
@tanersener today I also faced this issue and it pretty solves by adding proguard file. Hence, I have created a PR stating instruction and content for the file.

PR: https://github.com/tanersener/flutter-ffmpeg/pull/284

**Comment by sakofchit** [comment]
Thanks guys! Turns out it was because I forgot to clear my gradle cache.
