### ISSUE TITLE
the time in StatisticsCallback is bigger than video duration

### ISSUE THREAD

**Issue by saviourdog** [tanersener/flutter-ffmpeg#291]
**Description**
the time in StatisticsCallback is bigger than video duration

**Expected behavior**
the video duration is 2:29,and the time of last line of output should be 2:29
![image](https://user-images.githubusercontent.com/22761043/114829550-ca39bb80-9dfd-11eb-9bbb-80f387b80f07.png)
![image](https://user-images.githubusercontent.com/22761043/114829584-d6257d80-9dfd-11eb-82ce-62e5819ea13e.png)

**Current behavior**
callback`s duration bigger than video duration
![image](https://user-images.githubusercontent.com/22761043/114829836-200e6380-9dfe-11eb-9526-55c5eabdc8b8.png)

my code,best regards!
![image](https://user-images.githubusercontent.com/22761043/114830474-d1ad9480-9dfe-11eb-8682-b8126809a705.png)

**Comment by tanersener** [comment]
I don't get what your screenshots show? Can you write them in text please?

**Comment by saviourdog** [comment]
sorry,my bad

```
final FlutterFFmpeg ffm = FlutterFFmpeg();
    final FlutterFFprobe ffp = FlutterFFprobe();
    FlutterFFmpegConfig ffc = FlutterFFmpegConfig();
    final doc = await getApplicationDocumentsDirectory();
    var dir = Directory(doc.path + '/cover');
    if (!dir.existsSync()) {
      dir.createSync();
    }
    if (tmpVideo != null && covers.value.length == 0) {
      var info = await ffp.getMediaInformation(tmpVideo.path);
      var duration = info.getMediaProperties()['duration'];
      print("info.getMediaProperties()['duration'] $duration");
      ffm
          .execute(
              '-i ${tmpVideo.path} -r ${10 / double.parse(duration)} -vf "crop=ih*1.8:ih:(iw-ih*1.8)/2:0" ${dir.path}/%2d.jpg')
          .then((rc) {
        print("FFmpeg process exited with rc $rc");
        covers.value = dir.listSync().toList();
      });
      ffc.enableStatisticsCallback((statistics) {
        print(
            "Statistics: executionId: ${statistics.executionId}, time: ${statistics.time}, size: ${statistics.size}, bitrate: ${statistics.bitrate}, speed: ${statistics.speed}, videoFrameNumber: ${statistics.videoFrameNumber}, videoQuality: ${statistics.videoQuality}, videoFps: ${statistics.videoFps}");
      });
    }
```

**Comment by tanersener** [comment]
`2:29` is the duration of your input video. And the time reported by `StatisticsCallback` is the time calculated for the output of your command. They cannot always be the same. Output can be longer or shorter depending on your command and the options used.

In your case, the time value coming from `StatisticsCallback` is bigger than the time of your input video. But I also see that your output is not a video, it is a series of images. So, time for your command won't have a meaningful value. You should try using other fields returned from `StatisticsCallback`.

**Comment by saviourdog** [comment]
thank you a lot

**Comment by saviourdog** [comment]
so this command can not get progress,right?

**Comment by tanersener** [comment]
No, `ffmpeg` can not give you the progress. You need to calculate it yourself using statistics.

**Comment by saviourdog** [comment]
thanks a lot
