### ISSUE TITLE
Android App Crash in release mode

### ISSUE THREAD

**Issue by herrmayr** [tanersener/flutter-ffmpeg#297]
**Description**
The Android app exits (crashes) completely when the ffmpeg.execute command is triggered. This only happens when the app runs in release mode, in debug mode, I cannot reproduce the error. In release mode, I tested with an Android 10 and 11 device. 

**Expected behavior**
ffmpeg command is executed, app does not crash

**Current behavior**
The app runs well until the ffmpeg command is triggered.

**Logs**

> java.lang.RuntimeException: An error occurred while executing doInBackground()
> at android.os.AsyncTask$4.done(AsyncTask.java:399)
> at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
> at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
> at java.util.concurrent.FutureTask.run(FutureTask.java:271)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:919)
> Caused by: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/de.herrmayr.hyfeecloud.hyfeecloud-9UhNjASg3Vt_3kOiI4hCJA==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmobileffmpeg.so": 0
> at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
> at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
> at java.lang.System.loadLibrary(System.java:1667)
> at com.arthenica.mobileffmpeg.Config.<clinit>(Unknown Source:146)
> at com.arthenica.mobileffmpeg.Config.f(Unknown Source:0)
> at com.arthenica.mobileffmpeg.c.d(Unknown Source:2)
> at c.a.a.a.a.a(Unknown Source:31)
> at c.a.a.a.a.doInBackground(Unknown Source:2)
> at android.os.AsyncTask$3.call(AsyncTask.java:378)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> ... 3 more

**Environment**

> [✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-arm, locale
>     de-DE)
>     • Flutter version 2.0.5 at /Users/christianmayr/development/flutter
>     • Framework revision adc687823a (2 weeks ago), 2021-04-16 09:40:20 -0700
>     • Engine revision b09f014e96
>     • Dart version 2.12.3
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/christianmayr/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.5, Build version 12E262
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.55.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.21.0
> 
> [✓] Connected device (1 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
> 
> • No issues found!

Is there a bug in the package or could I do something wrong in code which I don't see right now?
On iOS, it works perfectly in debug and release.

**Comment by herrmayr** [comment]
What is this issue a duplicate of? And is there something I can do differently to prevent this from happening?

**Comment by tanersener** [comment]
This issue was reported before. If you search the issues for the exception string, you can find previously created issues.

The solution is given in [Tips](https://github.com/tanersener/flutter-ffmpeg#5-tips).
