### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "flutter_ffmpeg"

### ISSUE THREAD

**Issue by iOSForLiHua** [tanersener/flutter-ffmpeg#30]
[!] CocoaPods could not find compatible versions for pod "flutter_ffmpeg":
  In Podfile:
    flutter_ffmpeg (from `.symlinks/plugins/flutter_ffmpeg/ios`)

Specs satisfying the `flutter_ffmpeg (from `.symlinks/plugins/flutter_ffmpeg/ios`)` dependency were found, but they required a higher minimum deployment target.

Xode10.1

**Comment by tanersener** [comment]
See [Always fill the issue template](https://github.com/tanersener/flutter-ffmpeg/issues/25).
