### ISSUE TITLE
Example Request: Watermark Video

### ISSUE THREAD

**Issue by jtkeyva** [tanersener/flutter-ffmpeg#301]
**Description**
Cannot figure out how to watermark a video. I've tried over and over so many different methods and stackoverflow ffmpeg commands but can't get any of them to work in context. Would be super helpful to see a fully working example just like the other examples.

**Expected behavior**
Use asset image.png to watermark asset.mp4 and output watermarkedvideo.mp4

**Current behavior**
Crashes hard. Debugger brings up _isolates_io.dart. Also having issues with Cannot load asset...

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.1 20D74 darwin-arm, locale en-US)
    • Flutter version 2.0.4 at /Users/jt/development/flutter
    • Framework revision b1395592de (6 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jt/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

**Other**
Seems like a simple operation, but spent hours and keep hitting a wall

Thanks!

**Comment by suli1** [comment]
```
int result = await _ffmpeg.executeWithArguments([
      '-i',
      srcPath,
      '-max_muxing_queue_size',
      '1024',
      '-b:v',
      '${_mediaInfo.bitrate}k',
      '-vf',
      'movie=$watermarkPath,scale=${scale * watermarkSize.width}:${scale * watermarkSize.height}[watermask];[in] [watermask] $overlay [out]',
      targetPath,
    ]);
```

**Comment by jtkeyva** [comment]
> int result = await _ffmpeg.executeWithArguments([
>       '-i',
>       srcPath,
>       '-max_muxing_queue_size',
>       '1024',
>       '-b:v',
>       '${_mediaInfo.bitrate}k',
>       '-vf',
>       'movie=$watermarkPath,scale=${scale * watermarkSize.width}:${scale * watermarkSize.height}[watermask];[in] [watermask] $overlay [out]',
>       targetPath,
>     ]);

thanks! cant wait to try. i will report back
