### ISSUE TITLE
fatal error: 'mobileffmpeg/LogDelegate.h' file not found

### ISSUE THREAD

**Issue by eugrro** [tanersener/flutter-ffmpeg#303]
I am running into this issue in the title when running: flutter build ios --release
```  
2 warnings generated.
    In file included from
    /Users/eugene/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.4.0
    /ios/Classes/EmptyLogDelegate.m:20:
    /Users/eugene/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.4.0
    /ios/Classes/EmptyLogDelegate.h:20:10: fatal error: 'mobileffmpeg/LogDelegate.h' file
    not found
    #include <mobileffmpeg/LogDelegate.h>
```
Ive seen the following:
https://github.com/tanersener/flutter-ffmpeg/issues/210
https://github.com/tanersener/flutter-ffmpeg/issues/212
Ive tried 
```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install
flutter build ios --release
```
None of it has worked and I am not sure why its not working. Any insight would be helpful

**Comment by ClaudeChey** [comment]
same issue  after upgrade to Flutter 2.2.0

**Comment by fauzipadlaw** [comment]
same issue on my machine:

```
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-arm, locale
    en-ID)
    • Flutter version 2.2.0 at /Users/efzet/SDKs/flutter
    • Framework revision b22742018b (4 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/efzet/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/efzet/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave
      Browser

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 56.0.3
    • Dart plugin version 203.8173

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 34465855-802A-4D1E-AF3E-9F0FFC936150 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Brave Browser 90.1.24.85

• No issues found!
```

**Comment by frankyvij** [comment]
Have we been able to find a solution for this? Please update the ticket if you have.. Thanks..

**Comment by tanersener** [comment]
Could you please try running the example app? 

Also make sure that you are using the latest version of `cocoapods`. Some versions have issues with newer `xcframework` bundles.

**Comment by frankyvij** [comment]
Example app is fine! The issue started to happen when I upgraded to flutter 2.2.0. Android does not have any problem. Upgraded cocoapods, cleared cache, tried all the steps above! :(

**Comment by frankyvij** [comment]
Ok so, people! Follow the installation instructions in the package description for Flutter version >= 2.x.

Use this in your PodFile:

`
  # "fork" of method flutter_install_plugin_pods (in fluttertools podhelpers.rb) to get lts version of ffmpeg
  def flutter_install_plugin_pods(application_path = nil, relative_symlink_dir, platform)
    # defined_in_file is set by CocoaPods and is a Pathname to the Podfile.
    application_path ||= File.dirname(defined_in_file.realpath) if self.respond_to?(:defined_in_file)
    raise 'Could not find application path' unless application_path

    # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
    # referring to absolute paths on developers' machines.

    symlink_dir = File.expand_path(relative_symlink_dir, application_path)
    system('rm', '-rf', symlink_dir) # Avoid the complication of dependencies like FileUtils.

    symlink_plugins_dir = File.expand_path('plugins', symlink_dir)
    system('mkdir', '-p', symlink_plugins_dir)

    plugins_file = File.join(application_path, '..', '.flutter-plugins-dependencies')
    plugin_pods = flutter_parse_plugins_file(plugins_file, platform)
    plugin_pods.each do |plugin_hash|
      plugin_name = plugin_hash['name']
      plugin_path = plugin_hash['path']
      if (plugin_name && plugin_path)
        symlink = File.join(symlink_plugins_dir, plugin_name)
        File.symlink(plugin_path, symlink)

        if plugin_name == 'flutter_ffmpeg'
          pod 'flutter_ffmpeg/<package name>', :path => File.join(relative_symlink_dir, 'plugins', plugin_name, platform)
        else
          pod plugin_name, :path => File.join(relative_symlink_dir, 'plugins', plugin_name, platform)
        end
      end
    end
  end
`

**Comment by abahnj** [comment]
This doesn't help it still throws the exact same error

**Comment by JoeMan97** [comment]
Yeah, same error. I'll downgrade to version 2.0.6 of flutter.

**Comment by hernantz** [comment]
Seeing the same on Flutter 2.2.0, not sure if it's because I'm using the M1 Mac...

**Comment by fauzipadlaw** [comment]
> Seeing the same on Flutter 2.2.0, not sure if it's because I'm using the M1 Mac...

I'm using M1 too

**Comment by JoeMan97** [comment]
> Seeing the same on Flutter 2.2.0, not sure if it's because I'm using the M1 Mac...

I don't have an M1, that shouldn't be related

**Comment by abahnj** [comment]
Why has there been no response or attempted resolution for this bug

**Comment by tanersener** [comment]
@abahnj because:
1. This plugin was tested on `flutter 2.2.0` and no issues were found
2. This issue does not fill out issue template fields. And issues that don't fill out issue template are ignored. See #25
3. I responded to this thread [here](https://github.com/tanersener/flutter-ffmpeg/issues/303#issuecomment-845443846) and suggested two things that can help you to pinpoint the issue. As far as I see only one person saw my message and tried to run the test app. The same person also said that he fixed his issue by updating package description in the `Podfile`. I don't see any other messages from people that tried my suggestions. So, I don't make any comments.

**Comment by abahnj** [comment]
@tanersener Thanks a lot for all your effort, I opened a new issue following the template and added more explanations, if there is anything I can do to make this easier to fix or more reproducible please let me know. I've tried all I can and I'm at my wits end trying to figure this out

**Comment by ClaudeChey** [comment]
I solved this problem by reinstalling Pod

**Comment by chainzhang** [comment]
I had the same problem. It seems that the function `flutter_install_ios_plugin_pods` was changed to `flutter_install_plugin_pods` in new version.

I fixed this issue by replace lines:

```
def flutter_install_ios_plugin_pods(ios_application_path = nil)
↓
def flutter_install_plugin_pods(application_path = nil, relative_symlink_dir, platform)
```

```
plugin_pods = flutter_parse_plugins_file(plugins_file)
↓
plugin_pods = flutter_parse_plugins_file(plugins_file, platform)
```

Good luck.

**Comment by abahnj** [comment]
So a couple of things I realized.
I realized that changing from min to min-lts fixed the issue for me. So maybe try other versions of the package
Also if none of your dependencies require use_frameworks! and/or use_modular_headers! remove them one at a time.

**Comment by eugrro** [comment]
I'm not sure what the fix is. I ended up using fastlane to build the ipa. Maybe try that.

**Comment by kishanmundha** [comment]
I'm using MacBook Pro with M1 and getting the same issue. I tried all way also create a fresh project and add only "flutter-ffmpeg" then this issue happen and not able to resolve.

**Comment by tanersener** [comment]
@kishanmundha This plugin doesn't support arm64 simulator architecture of iOS. I suggest using another architecture for testing.

**Comment by kishanmundha** [comment]
https://github.com/tanersener/flutter-ffmpeg#212-ios-flutter--2x helped me and after changing in pod file, this worked for me. Also, change the property of XCode "Open using Rosetta" help to run as intel x86_64 and resolve other error too.

**Comment by kisakyamukama** [comment]
was having this issue , and mine is most likely to have resulted from not calling the function in Runner 

`target 'Runner' do
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end`
