### ISSUE TITLE
Android app crashing in Release mode when initialising FlutterFFmpegConfig()

### ISSUE THREAD

**Issue by spiderion** [tanersener/flutter-ffmpeg#306]
**Description**
version  flutter_ffmpeg: ^0.4.0
Android app crashing in Release mode when initializing FlutterFFmpegConfig()
Works fine in debug mode
Works fine in release mode if not using FlutterFFmpegConfig()

**Expected behavior**
Not to crash

**Current behavior**
The app is crashing on initialization of FlutterFFmpegConfig

**Logs**
I/flutter (16806): Loading flutter-ffmpeg.
E/AndroidRuntime(16806): FATAL EXCEPTION: main
E/AndroidRuntime(16806): Process: com.myapp.app, PID: 16806
E/AndroidRuntime(16806): java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/~~GUfqLfDuuuI1waBLi_xP7A==/com.remboxbo.lyve-GDXb6VXYtoZXnDFr1e2e2w==/base.apk!/lib/arm64-v8a/libmobileffmpeg.so": 0
E/AndroidRuntime(16806): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
E/AndroidRuntime(16806): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/AndroidRuntime(16806): 	at java.lang.System.loadLibrary(System.java:1664)
E/AndroidRuntime(16806): 	at com.arthenica.mobileffmpeg.Config.<clinit>(Unknown Source:146)
E/AndroidRuntime(16806): 	at com.arthenica.mobileffmpeg.Config.c(Unknown Source:0)
E/AndroidRuntime(16806): 	at e.a.a.a.d.C(Unknown Source:323)
E/AndroidRuntime(16806): 	at h.a.c.a.j$a.a(Unknown Source:17)
E/AndroidRuntime(16806): 	at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
E/AndroidRuntime(16806): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/AndroidRuntime(16806): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(16806): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(16806): 	at android.os.Looper.loop(Looper.java:206)
E/AndroidRuntime(16806): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AndroidRuntime(16806): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16806): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(16806): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Environment**
Flutter doctor output
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by arbile26** [comment]
The same issue with me!

**Comment by AnAnD4T1** [comment]
https://github.com/tanersener/mobile-ffmpeg/issues/616#issuecomment-740501984 i tried this solution and it worked
