### ISSUE TITLE
man.png: No such file or directory

### ISSUE THREAD

**Issue by rdcoder33** [tanersener/flutter-ffmpeg#31]
I am new to FFmpeg and Flutter, I am trying to execute a cmd to overlap two images:

```
import 'package:flutter/material.dart';
import 'package:flutter_ffmpeg/flutter_ffmpeg.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final FlutterFFmpeg _flutterFFmpeg = new FlutterFFmpeg();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
          home: Scaffold(
        body: Container(
          child: Center(
              child: RaisedButton(
            onPressed: overlapImages,
            child: Text('Click Me'),
          )),
        ),
      ),
    );
  }

  overlapImages() {
    _flutterFFmpeg
        .execute(
            "-i man.png -i graduation.png -filter_complex 'overlay' out.png")
        .then((onValue) {
      print(onValue);
    });
  }
}
```

The file man.png and decoration.png are in assets folder at the project level. There is no documentation on how to make these assets available to flutter_ffmpeg package and where the output.png will be saved? I did look example file but being new to both Android Market and mobile ffmpeg I didn't get anything.

Can you just help me in setting this up?

**Comment by tanersener** [comment]
> The file man.png and decoration.png are in assets folder at the project level. There is no documentation on how to make these assets available to flutter_ffmpeg package and where the output.png will be saved? 

`flutter_ffmpeg` is a `flutter` plugin and uses file system paths. It does not know what an `assets` folder or `project` folder is, so you can't use resources on those folders directly, you need to provide full paths of those resources.

Additionally, `flutter_ffmpeg` does not define a folder structure, if you don't use full path in output file, location of output file is unpredictable.

> I did look example file but being new to both Android Market and mobile ffmpeg I didn't get anything.
> 

`example` application uses images inside `assets` folder. There is a [prepareAssets](https://github.com/tanersener/flutter-ffmpeg/blob/master/example/lib/flutter_ffmpeg_example.dart#L144) method to prepare assets and an [assetPath](https://github.com/tanersener/flutter-ffmpeg/blob/master/example/lib/flutter_ffmpeg_example.dart#L65) method to access full path of an asset. Please take a look at them.

**Comment by rdcoder33** [comment]
Following your advice, I read the example file again (actually 15-20 times) and I did get some of the code:

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_ffmpeg/flutter_ffmpeg.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final FlutterFFmpeg _flutterFFmpeg = new FlutterFFmpeg();
  Directory tempDirectory;
  String assetPath;

  @override
  void initState() {
    super.initState();
    getImagesDirectory();
    prepareAssetsPath();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          child: Center(
              child: RaisedButton(
            onPressed: overlapImages,
            child: Text('Click Me'),
          )),
        ),
      ),
    );
  }

  getImagesDirectory() async {
    tempDirectory = await getTemporaryDirectory();
    setFontconfigConfigurationPath(tempDirectory.path);
    print(tempDirectory.path);
  }

  getImagePath(String assetName) {
    return join(tempDirectory.path, assetName);
  }

  Future<File> copyFileAssets(String assetName, String localName) async {
    final ByteData assetByteData = await rootBundle.load(assetName);

    final List<int> byteList = assetByteData.buffer
        .asUint8List(assetByteData.offsetInBytes, assetByteData.lengthInBytes);

    final String fullTemporaryPath = join(tempDirectory.path, localName);

    return File(fullTemporaryPath)
        .writeAsBytes(byteList, mode: FileMode.writeOnly, flush: true);
  }

  String ffmpegCode() {
    String path1 = getImagePath('1.png');
    String path2 = getImagePath('2.png');
    String output = getImagePath('out.png');
    return "-i $path1 -i $path2 -filter_complex 'overlay' $output";
  }

  Future<void> setFontconfigConfigurationPath(String path) async {
    return await _flutterFFmpeg.setFontconfigConfigurationPath(path);
  }

  prepareAssetsPath() {
    copyFileAssets('assets/man.png', '1.png')
        .then((path) => print('Loaded asset $path.'));
    copyFileAssets('assets/graduation.png', '2.png')
        .then((path) => print('Loaded asset $path.'));
  }

  overlapImages() {
    _flutterFFmpeg.execute(ffmpegCode()).then((code) {
      if (code == 0) {
        print('Done!');
      }
    });
  }
}
```
 Though its working now(may be), but how can I see` output.png`? The result of ffmpeg cmd.

```
Launching lib\main.dart on RMX1801 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter ( 7290): Loading flutter-ffmpeg.
I/mobile-ffmpeg( 7290): Loading mobile-ffmpeg.
I/mobile-ffmpeg( 7290): Loaded mobile-ffmpeg-https-arm64-v8a-4.2.1-20190402.
D/mobile-ffmpeg( 7290): Callback thread started.
I/flutter ( 7290): Loaded flutter-ffmpeg-android-arm64-v8a.
I/flutter ( 7290): /data/user/0/com.example.logo_test/cache
I/flutter ( 7290): Loaded asset File: '/data/user/0/com.example.logo_test/cache/2.png'.
I/flutter ( 7290): Loaded asset File: '/data/user/0/com.example.logo_test/cache/1.png'.
I/Choreographer( 7290): Skipped 3 frames!  The application may be doing too much work on its main thread.
D/flutter-ffmpeg( 7290): Running FFmpeg command: -i /data/user/0/com.example.logo_test/cache/1.png -i /data/user/0/com.example.logo_test/cache/2.png -filter_complex 'overlay' /data/user/0/com.example.logo_test/cache/out.png with delimiter  .
I/flutter ( 7290): ffmpeg version v4.2-dev-1156
I/flutter ( 7290):  Copyright (c) 2000-2019 the FFmpeg developers
I/flutter ( 7290):
I/flutter ( 7290):   built with Android (5058415 based on r339409) clang version 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec746213857d083c0e8b0abb568790) (https://android.googlesource.com/toolchain/llvm 7a6618d69e7e8111e1d49dc9e7813767c5ca756a) (based on LLVM 8.0.2svn)
I/flutter ( 7290):   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disa
I/flutter ( 7290):   libavutil      56. 26.100 / 56. 26.100
I/flutter ( 7290):   libavcodec     58. 47.106 / 58. 47.106
I/flutter ( 7290):   libavformat    58. 26.101 / 58. 26.101
I/flutter ( 7290):   libavdevice    58.  7.100 / 58.  7.100
I/flutter ( 7290):   libavfilter     7. 48.100 /  7. 48.100
I/flutter ( 7290):   libswscale      5.  4.100 /  5.  4.100
I/flutter ( 7290):   libswresample   3.  4.100 /  3.  4.100
I/flutter ( 7290): Input #0, png_pipe, from '/data/user/0/com.example.logo_test/cache/1.png':
I/flutter ( 7290):   Duration:
I/flutter ( 7290): N/A
I/flutter ( 7290): , bitrate:
I/flutter ( 7290): N/A
I/flutter ( 7290):
I/flutter ( 7290):     Stream #0:0
I/flutter ( 7290): : Video: png, rgba(pc), 512x512 [SAR 9225:9225 DAR 1:1]
I/flutter ( 7290): ,
I/flutter ( 7290): 25 tbr,
I/flutter ( 7290): 25 tbn,
I/flutter ( 7290): 25 tbc
I/flutter ( 7290):
I/flutter ( 7290): Input #1, png_pipe, from '/data/user/0/com.example.logo_test/cache/2.png':
I/flutter ( 7290):   Duration:
I/flutter ( 7290): N/A
I/flutter ( 7290): , bitrate:
I/flutter ( 7290): N/A
I/flutter ( 7290):
I/flutter ( 7290):     Stream #1:0
I/flutter ( 7290): : Video: png, rgba(pc), 512x512 [SAR 2835:2835 DAR 1:1]
I/flutter ( 7290): ,
I/flutter ( 7290): 25 tbr,
I/flutter ( 7290): 25 tbn,
I/flutter ( 7290): 25 tbc
I/flutter ( 7290):
I/flutter ( 7290): Stream mapping:
I/flutter ( 7290):   Stream #0:0 (png) -> overlay:main
I/flutter ( 7290):
I/flutter ( 7290):   Stream #1:0 (png) -> overlay:overlay
D/flutter-ffmpeg( 7290): FFmpeg exited with rc: 0
I/flutter ( 7290):
I/flutter ( 7290):   overlay
I/flutter ( 7290):  -> Stream #0:0 (png)
I/flutter ( 7290): Press [q] to stop, [?] for help
I/flutter ( 7290): [swscaler @ 0x7074958000]
I/flutter ( 7290): No accelerated colorspace conversion found from yuva420p to rgba.
I/flutter ( 7290): Output #0, image2, to '/data/user/0/com.example.logo_test/cache/out.png':
I/flutter ( 7290):   Metadata:
I/flutter ( 7290):     encoder         :
I/flutter ( 7290): Lavf58.26.101
I/flutter ( 7290):
I/flutter ( 7290):     Stream #0:0
I/flutter ( 7290): : Video: png, rgba, 512x512 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s
I/flutter ( 7290): ,
I/flutter ( 7290): 25 fps,
I/flutter ( 7290): 25 tbn,
I/flutter ( 7290): 25 tbc
I/flutter ( 7290):  (default)
I/flutter ( 7290):
I/flutter ( 7290):     Metadata:
I/flutter ( 7290):       encoder         :
I/flutter ( 7290): Lavc58.47.106 png
I/flutter ( 7290):
I/flutter ( 7290): frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=0.374x
I/flutter ( 7290): video:28kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead:
I/flutter ( 7290): unknown
I/flutter ( 7290):
I/flutter ( 7290): Done!
W/IInputConnectionWrapper( 7290): getExtractedText on inactive InputConnection

```

**Comment by tanersener** [comment]
You can use `Image.file` constructor to display your output file: `new Image.file(new File(output));`

**Comment by shubham12387** [comment]
Errors:

Syncing files to device vivo Y21L...
I/flutter (21932): Loading flutter-ffmpeg.
I/OpenGLRenderer(21932): Initialized EGL, version 1.4
I/mobile-ffmpeg(21932): Loading mobile-ffmpeg.
W/linker  (21932): libmobileffmpeg-abidetect.so: unused DT entry: type 0x6ffffffe arg 0x694
W/linker  (21932): libmobileffmpeg-abidetect.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker  (21932): libcpufeatures.so: unused DT entry: type 0x6ffffffe arg 0x7d0
W/linker  (21932): libcpufeatures.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker  (21932): libmobileffmpeg-armv7a-neon.so: unused DT entry: type 0x6ffffffe arg 0x6290
W/linker  (21932): libmobileffmpeg-armv7a-neon.so: unused DT entry: type 0x6fffffff arg 0xa
W/linker  (21932): libc++_shared.so: unused DT entry: type 0x6ffffffe arg 0x2b994
W/linker  (21932): libc++_shared.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker  (21932): libavcodec.so: unused DT entry: type 0x6ffffffe arg 0x6538
W/linker  (21932): libavcodec.so: unused DT entry: type 0x6fffffff arg 0x4
W/linker  (21932): libavfilter.so: unused DT entry: type 0x6ffffffe arg 0x44f4
W/linker  (21932): libavfilter.so: unused DT entry: type 0x6fffffff arg 0x7
W/linker  (21932): libswscale.so: unused DT entry: type 0x6ffffffe arg 0xe94
W/linker  (21932): libswscale.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker  (21932): libavformat.so: unused DT entry: type 0x6ffffffe arg 0x7414
W/linker  (21932): libavformat.so: unused DT entry: type 0x6fffffff arg 0x4
W/linker  (21932): libavutil.so: unused DT entry: type 0x6ffffffe arg 0x6d84
W/linker  (21932): libavutil.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker  (21932): libswresample.so: unused DT entry: type 0x6ffffffe arg 0xe2c
W/linker  (21932): libswresample.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker  (21932): libavdevice.so: unused DT entry: type 0x6ffffffe arg 0x1448
W/linker  (21932): libavdevice.so: unused DT entry: type 0x6fffffff arg 0x5
I/mobile-ffmpeg(21932): Loaded mobile-ffmpeg-https-arm-v7a-neon-4.2-lts.
I/flutter (21932): Loaded flutter-ffmpeg-android-arm-v7a-neon.
D/mobile-ffmpeg(21932): Callback thread started.
D/flutter-ffmpeg(21932): Running FFmpeg command: -i File: '/storage/emulated/0/video_5.mp4'.mp4 -ss 00:00:01.000 -vframes 1 recordedImage.jpg with delimiter  .
I/Timeline(21932): Timeline: Activity_idle id: android.os.BinderProxy@38869914 time:113811921
D/flutter-ffmpeg(21932): FFmpeg exited with rc: 1
F/art     (21932): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI NewByteArray called with pending exception 'java.lang.RuntimeException' thrown in unknown throw location
F/art     (21932): art/runtime/check_jni.cc:65]     in call to NewByteArray





My Code:

 void _pickVideo() async {
    ImagePicker.pickVideo(source: ImageSource.gallery)
        .then((File recordedVideo) {
      if (recordedVideo != null && recordedVideo.path != null) {
        setState(() {
          secondButtonText = 'saving in progress...';
          File recordedImage;
          _flutterFFmpeg
              .execute(
                  "-ss 00:1:45 -i $recordedVideo -vframes 1 -q:v 2 $recordedImage.jpg")
              .then((rc) => print("FFmpeg process exited with rc $rc"));
          GallerySaver.saveImage(recordedImage.path).then((path) {
            setState(() {
              firstButtonText = 'image saved!';
            });
          });
        });
        GallerySaver.saveVideo(recordedVideo.path).then((path) {
          setState(() {
            secondButtonText = 'video saved!';
          });
        });
      }
    });
  }

Sir I am using ffmpeg package in my testapp project
I want to select a video from my phone storage and extract one frame at a given time from it and save it to my phone storage. I am using Gallery Saver package it works for saving photos and video but for my specific task it does this error shows in output
Every time i run the code rc exited : 1 comes and then the above error.
App directly crashes after that. 
Please Help me Sir!!

**Comment by tanersener** [comment]
@shubham12387 Please create a new issue next time. You error does not have any similarities with the issue in this thread.

The following error causes the crash. It is received when you are doing something wrong like calling `_flutterFFmpeg.execute` in wrong thread or doing something unexpected in `logCallback` or `statisticsCallback` functions. Can you please check them?

`JNI DETECTED ERROR IN APPLICATION: JNI NewByteArray called with pending exception 'java.lang.RuntimeException' thrown in unknown throw location`

**Comment by shubham12387** [comment]
Okay Sir let me look again
