### ISSUE TITLE
How to use arnndn (Recurrent Neural Network Models) in the execution script

### ISSUE THREAD

**Issue by aytunch** [tanersener/flutter-ffmpeg#310]
Hi Taner,
 I am trying to feed ffmpeg with a neural model filter for audio speech de-noising.
 
I have searched but did not come up with any examples or issues in here or in `mobile-ffmpeg`
I am getting the neural model data from: https://github.com/GregorR/rnnoise-models
I add the model file (mp.rnnn) into `assets/ml_models/`
I also added the same file under assets in pubspec.yaml
and run the script:

> "-y -i ${detail.sourceFilePath} -af arnndn=m=assets/ml_models/mp.rnnn  -c:v libx264 -preset fast -crf 28 -c:a aac -b:a 44100 ${detail.encodedFilePath}"

But I get the following error:
```
I/flutter ( 9493): [AVFilterGraph @ 0x6fd74ecda0] Error initializing filter 'arnndn'
I/flutter ( 9493): [AVFilterGraph @ 0x6fd74ecda0]  with args 'm=assets/ml_models/mp.rnnn'
I/flutter ( 9493): [AVFilterGraph @ 0x6fd74ecda0]
I/flutter ( 9493): Error reinitializing filters!
I/flutter ( 9493): Failed to inject frame into filter network: Invalid argument
I/flutter ( 9493): Error while processing the decoded data for stream #0:1
I/flutter ( 9493): Conversion failed!
```

 
There are xx.hdf5.xz files present in the models repository. Am I supposed to add them to the assets folder too? But there is no field to enter that file for `arnndn` looking at the docs.

<img width="229" alt="Screen Shot 2021-05-31 at 22 00 52" src="https://user-images.githubusercontent.com/6442915/120232186-b508d700-c25b-11eb-83a3-c71e0d52d229.png">

**Comment by tanersener** [comment]
Hmm, I don't know. I'm not familiar with `arnndn` filter. By the way, have you tried providing the full path of the `mp.rnnn` file? As you know `flutter_ffmpeg` doesn't work well with relative paths.

**Comment by aytunch** [comment]
@tanersener I have tried as you have suggested to use the absolute path. Unfortunately I got the same error.
Can you think of any other suggestions? No matter how much I searched, I can't find any hints for using rnn in Flutter.

**Comment by tanersener** [comment]
I believe your issue is not about `flutter`. Have you searched for using `arnndn` filter with `ffmpeg` on the web? I found [this](https://www.amirsharif.com/using-ffmpeg-to-reduce-background-noise/) web page. It takes the same approach as you as far as I see.
