### ISSUE TITLE
Pipe image frames to ffmpeg to create a video

### ISSUE THREAD

**Issue by yaizudamashii** [tanersener/flutter-ffmpeg#325]
I would like to create a video from images drawn from Flutter side by piping it into flutter_ffmpeg.
The images would come in form of `Uint8List` or `List<int>`.
The example provided by @tanersener has a pipe tab that reads from `.png` files and pipes bytes and immediately closes the pipe by creating a Dart `File` with pipe path using `.writeOnly` option.  

Is there a way to continuously feed image frames to an executing `ffmpeg` process?

I've scoured StackOverflow but there are very few questions about flutter_ffmpeg.

My theories are as follows:
1. Using `image2pipe` it seems that we can pipe into ffmpeg from stdin.  However, [Flutter's stdin](https://api.flutter.dev/flutter/dart-io/Stdin-class.html) seems to only support write, not sure if that can be done.
2. Using `-i` option as in the example.  But then I'm unsure how to use the `File` in Flutter to pipe image frames rather than simply adding bytes to the already open pipe.  If we `registerNewFFmpegPipe` does flutter_ffmpeg know that new chunks of bytes is a new frame?  If so what would be a minimal command to execute so we can pipe images?

If anyone has every encountered and solved this problem, please guide me.  Thank you.

**Comment by yaizudamashii** [comment]
Closing for now

**Comment by kartik1225** [comment]
Hey did you find a solution for this?
