### ISSUE TITLE
#include <mobileffmpeg/LogDelegate.h>              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~     1 error generated.

### ISSUE THREAD

**Issue by xixixx** [tanersener/flutter-ffmpeg#327]
#include <mobileffmpeg/LogDelegate.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by bdw9005** [comment]
同问，我的是在iphone8 ios 11.4模拟器中出现的这个问题，配置的 pod 'flutter_ffmpeg/video'出现下面的问题：
flutter-2.2.3/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_ffmpeg-0.4.2/ios/Classes/EmptyLogDelegate.h:20:10: fatal error: 'mobileffmpeg/LogDelegate.h' file not found
    #include <mobileffmpeg/LogDelegate.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
flutter-2.2.3/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_ffmpeg-0.4.2/ios/Classes/FlutterExecuteDelegate.h:21:9: fatal error: 'mobileffmpeg/ExecuteDelegate.h' file not found
    #import <mobileffmpeg/ExecuteDelegate.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
