### ISSUE TITLE
Converting MP4 to HLS return RC 1

### ISSUE THREAD

**Issue by kiloki-official** [tanersener/flutter-ffmpeg#331]
**Description**
I try to convert MP4 videos into HLS using the code below:

`final arguments = '-y -i "$videoPath" ' +
      '-preset ultrafast -g 48 -sc_threshold 0 ' +
      '-map 0:0 -map 0:1 -map 0:0 -map 0:1 ' +
      '-c:v:0 libx264 -b:v:0 2000k ' +
      '-c:v:1 libx264 -b:v:1 365k ' +
      '-c:a copy ' +
      '-var_stream_map "v:0,a:0 v:1,a:1" ' +
      '-master_pl_name master.m3u8 ' +
      '-f hls -hls_time 6 -hls_list_size 0 ' +
      '-hls_segment_filename "$outDirPath/%v_fileSequence_%d.ts" ' +
      '$outDirPath/%v_playlistVariant.m3u8';

  final int rc = await _encoder.execute(arguments)`

**Expected behavior**
It only converts MPEG to HLS 40% of the time. When it does, the RC is equal to 0. I want it to work 100% of the time. 

**Current behavior**
60% of the time, I get the following problem: FFmpeg exited with rc: 1

**Environment**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_CA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (2 available)

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).
