### ISSUE TITLE
 /home/joshua/company/tiktok/assets/video.mp4: No such file or directory

### ISSUE THREAD

**Issue by joshuajennysibbu** [tanersener/flutter-ffmpeg#333]
I'm getting this error "E/mobile-FFmpeg(12819): /home/joshua/company/tiktok/assets/video.mp4: No such file or directory"
I need to merge video and audio. I give the exact location of the two files. That two file is inside flutter project
This is my code

    audioVideo() {
         String videoP = '/home/joshua/company/assets/video.mp4';
        String audioP = '/home/joshua/company/assets/audio.mp3';
    String outputP = '/home/joshua/company/assets/v.mp3';
    _flutterFFmpeg
        .execute("-i $videoP -i $audioP -c $outputP")
        .then((returncode) => print("Return code $returncode"));
      }

and also I get this error: W/mobile-FFmpeg(12819): Trailing option(s) found in the command: may be ignored.
I don't know what this means.

**Comment by iamaryanshandilya** [comment]
can you please tell me how did u solve this. I am having some similar problems, despite the fact that the two input files that I am trying to provide exist on the given location, I am getting an error can you tell me how you were able to solve this.

**Comment by joshuajennysibbu** [comment]
@iamaryanshandilya 
your input files must inside your app location. Not on another location.
