### ISSUE TITLE
Can I include the only the ffmpeg plugins that I need?

### ISSUE THREAD

**Issue by benwinding** [tanersener/flutter-ffmpeg#334]
**Description**
Is it possible to only include specific plugins in the build?

**Situtation**
Currently I'm only using the image-2-video conversion of ffmpeg. Below is the only call I'm making to the library:

``` dart
    final arguments = [
      "-r",
      "10",
      "-f",
      "image2",
      "-i",
      imagesPath,
      outPath
    ];
    await _flutterFFmpeg.executeWithArguments(arguments);
```
- The only package that works is `"full"`, which adds `100mb` to the build

Is there a way to select the absolute minimum to fulfil my use case?

**Comment by tanersener** [comment]
A similar question was asked before. See my response [there](https://github.com/tanersener/flutter-ffmpeg/issues/228#issuecomment-754658550).
