### ISSUE TITLE
Will flutter-ffmpeg be based on the new ffmpeg-kit instead of ffmpeg-mobile?

### ISSUE THREAD

**Issue by aytunch** [tanersener/flutter-ffmpeg#339]
I just saw [ffmpeg-kit](https://github.com/tanersener/ffmpeg-kit) and I think it will be the new library used for Applications. So I was wondering if flutter-ffmpeg be based on it in the future?

Also what will change if this ever happens? Will it be more performant? Or will we be able to run Flutter apps using ffmpeg on more platforms/devices natively?

@tanersener thanks for your contributions bro :)

**Comment by tanersener** [comment]
The plan is to combine and maintain all `ffmpeg` projects under `ffmpeg-kit`. `flutter_ffmpeg` won't start using `ffmpeg-kit`. It will be replaced with the `flutter` plugin of `ffmpeg-kit`. 

And as you guessed, one of the main reasons is to support non-mobile platforms as well.

**Comment by aytunch** [comment]
Do you have any estimates on when the `flutter` plugin of `ffmpeg-kit` be available for us to start testing?

**Comment by tanersener** [comment]
If everything goes as planned, in a few weeks time.
