### ISSUE TITLE
Need 10 bit version

### ISSUE THREAD

**Issue by ibrahimdevs** [tanersener/flutter-ffmpeg#343]
Hi @tanersener,

Firstly, thank you for this great work!

HDR video creation and view is getting more since iPhone 12. One of our project, I need to convert video HDR to SDR. So I need "yuv420p10le" but it gives me error: 
Incompatible pixel format 'yuv420p10le' for codec 'libx265', auto-selecting format 'yuv420p'

It gives this error because of it built on 8 bit versions. (build info [Mac OS X][clang 11.0.3][32 bit][noasm] 8bit)

Can you provide 10 bir version alternative?

Thanks,

**Comment by tanersener** [comment]
Hi, thanks for creating this issue. Could you share more details about your environment, the command you're running? So that we can reproduce this issue.

**Comment by ibrahimdevs** [comment]
I'm using flutter_ffmpeg 0.4.2 and testing on iPhone X(iOS 14). Here is HDR video which I tried: https://drive.google.com/file/d/12plWrjPfp1Hh1G7LHHTBXaOAi8ki7m5d/view?usp=sharing

Also, here is ffmpeg code:
-i hdr_video.MOV -map 0:0 -map 0:1 -map 0:2 -map 0:3 -c:a copy -c:s copy -c:v libx265 -crf 21 -preset veryfast -color_primaries bt2020 -color_trc smpte2084 -colorspace bt2020nc -profile:v main10 -pix_fmt yuv420p10le -max_muxing_queue_size 9999 output.mp4

Thanks,

**Comment by tanersener** [comment]
Well, I don't remember exactly why 10-bit support is not enabled in `x265`. Enabling the library was quite painful, I remember that. And I couldn't enable everything I wanted, i.e. asm is disabled. But for 10-bit support, I'm not sure why it's not there.

Anyway, we need to investigate if enabling 10-bit support is possible in `x265`. I assume then you will be able to use the `yuv420p10le` format.

**Comment by tanersener** [comment]
We will retire the project and continue with [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).

Created https://github.com/tanersener/ffmpeg-kit/issues/187 to work on this issue there.
