### ISSUE TITLE
Use lts version on from minsdk 19

### ISSUE THREAD

**Issue by vlada3003** [tanersener/flutter-ffmpeg#35]
**Description**
I have a project that supports minsdk 19 and would like to use this library. Is there a reason why minsdk for LTS is 21? Can I build it for minsdk 19 and how?

**Comment by tanersener** [comment]
Some of the Android API functions used in this project are introduced in API Level 21. This is why minSDK for LTS release is set to 21.

In two weeks time, a new LTS release will be published. This new release plans to support API Level 16. If you don't want to wait you can build the `development` branch of parent the [mobile-ffmpeg](https://github.com/tanersener/mobile-ffmpeg) project and integrate it with `flutter_ffmpeg`. But it is not tested yet and I'm not %100 sure that it is compatible with current `flutter_ffmpeg` versions.

**Comment by vlada3003** [comment]
Thanks! I'll wait for that version and use another plugin in the meantime for android.
