### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by gerry05** [tanersener/flutter-ffmpeg#45]
I'm having this error when I run  **flutter build ios**
![nxplayer bin_f7bqN1swA1](https://user-images.githubusercontent.com/26299783/60758815-25962180-a04e-11e9-9909-bfbe1b91bf2d.png)

**Comment by tanersener** [comment]
32 bit architectures are supported by LTS releases. Can you please install one of the LTS packages? [Packages](https://github.com/tanersener/flutter-ffmpeg#21-packages) section of README includes necessary instructions.

**Comment by gerry05** [comment]
I'm stuck with this. Can you check if my syntax is correct?   What is LTS?  

![nxplayer bin_vIPWpqEPWR](https://user-images.githubusercontent.com/26299783/60759272-f505b600-a054-11e9-89aa-78e6ea606d0a.png)

**Comment by tanersener** [comment]
Well, you need to replace `<package_name>`  with a package name. `flutter_ffmpeg` has 8 different packages,  they are all listed [Features](https://github.com/tanersener/flutter-ffmpeg#1-features) section.

**Comment by gerry05** [comment]
Thank you! @tanersener
