### ISSUE TITLE
Priority support and e-mail support available through Patreon

### ISSUE THREAD

**Issue by tanersener** [tanersener/flutter-ffmpeg#46]
I do my best to help you about your issues. But eventually I have limited time and sometimes I can’t respond to all your questions. If I miss your issue or you need a faster response, please consider backing me on [Patreon](https://www.patreon.com/tanersener). 

Patrons get **Priority Support** and **E-mail Support** for their issues.

**Comment by craftmusic** [comment]
Hey, we have a question for you about ffmpeg. I contributed on OpenCollective but it doesn’t give me your email address.

**Comment by tanersener** [comment]
Hi @craftmusic, thanks for backing me on OpenCollective. 

You can contact me from `tanersener@gmail.com`.

**Comment by lifenautjoe** [comment]
Hi @tanersener , we're long time users and patrons and buymeacoffee sponsors of you. We're currently experiencing some issues related to GIF to mp4 conversion suddenly no longer working. We've reached out on Patreon DMs on this. Hoping you can have some time to help us out 🙏
