### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by gerry05** [tanersener/flutter-ffmpeg#48]
The app is crashing sometimes in iOS when I call **getMediaInformation(path)**. And it has no error message, it just totally crash. It's working fine in android.

```
Future<Map<dynamic, dynamic>> getMediaInformation(String path) async {
    return await _flutterFFmpeg.getMediaInformation(path);
  }
```

**Comment by tanersener** [comment]
There must be a log or stack trace somewhere. Did you try running your application inside Xcode?

**Comment by tanersener** [comment]
@gerry05 Can you please provide other issue template fields, like architecture, package, version?

**Comment by gerry05** [comment]
> 
> 
> @gerry05 Can you please provide other issue template fields, like architecture, package, version?

I'm using  iPhone XR simulator and iPad mini 3. flutter_ffmpeg_audio_lts  v0.2.5   
I tried also the other package and it still crashes.
![nxplayer bin_tboggrS7aY](https://user-images.githubusercontent.com/26299783/60905151-0e9e3c00-a2a7-11e9-8e57-e8e39166fef3.png)

**Comment by tanersener** [comment]
Unfortunately, I can't reproduce this case on my local tests. Do you have the same issue when you run `getMediaInformation()` with `.wav` file you've used in your test? Additionally can your share your `.caf` file with me?

**Comment by gerry05** [comment]
Yes I tried with `.wav`, same issue.    Here's the [.caf file](https://ufile.io/hnsv2p7f)

**Comment by tanersener** [comment]
Tested your source code and `.caf` file. They worked for me too. 

Did you try running your application inside Xcode?

**Comment by gerry05** [comment]
This is what I got when I run the application in Xcode.
![nxplayer bin_sr4T8eecXw](https://user-images.githubusercontent.com/26299783/60956589-b5c9b480-a335-11e9-9535-4b81c44a908d.png)

**Comment by tanersener** [comment]
Thanks. Can you share the stack trace of the thread from the debug navigator?

<img src="https://answers.unity.com/storage/temp/76881-screenshot-at-aug-25-09-47-55.png" width="640">

**Comment by gerry05** [comment]
![nxplayer bin_RkbmSC529a](https://user-images.githubusercontent.com/26299783/60968932-d8b59200-a350-11e9-8ab9-eb75d4dc744c.png)

**Comment by tanersener** [comment]
Thanks. Unfortunately, debug navigator doesn't include much detail.

Well, there are different things we can try but they will take time. Do you have a chance to share your application with me? So I can test it on my test environment.

**Comment by gerry05** [comment]
I found an alternative solution to what I need for the app and it's not related to this plugin.  Thank you very much for the help.

**Comment by tanersener** [comment]
I'm sorry to hear that. I'd be great if we could understand the cause of your issue. I'll be here to help if you decide to use this plugin later.

**Comment by lukepighetti** [comment]
Just ran into this same issue. Trying to get MediaInformation from a file in iOS media library. Unfortunately the stack trace doesn't seem to be very helpful.

<img width="1867" alt="Screen Shot 2019-09-30 at 10 39 33 AM" src="https://user-images.githubusercontent.com/666539/65889509-5e087b80-e36f-11e9-8bfc-bfd876e09e58.png">

**Comment by tanersener** [comment]
@lukepighetti Could you please share the steps to reproduce this issue?

If issue is specific to a file, can you share that file by sending me a private message on [flutter-ffmpeg gitter channel](https://gitter.im/flutter-ffmpeg)?

**Comment by lukepighetti** [comment]
Just sent you the file to reproduce on gitter

**Comment by tanersener** [comment]
@lukepighetti Tried to reproduce this case with your file but unfortunately it works on my local tests. Is it possible to share your project with me?

**Comment by lukepighetti** [comment]
Sorry my project has evolved beyond this example. Will reach out if I run into it again.
