### ISSUE TITLE
Converted mp3 file not being read by any Music Player in the device

### ISSUE THREAD

**Issue by aj019** [tanersener/flutter-ffmpeg#51]
**Description**
 I was able to convert an mp4 file to mp3 file using the following command
-i file1.mp4 -f mp3 -ab 192000 -acodec libmp3lame file2.mp3
But for some reason the converted mp3 file is not being read by any of the music player on my phone device. Do you have any idea , why that might be happening ? And have you faced the same issue ?

**Expected behavior**
The converted mp3 file should be readable by the music players

**Current behavior**
The converted mp3 file is not being read by the music players

**Other**
The weird thing is if i search for the mp3 file in my file manager it doesn't show up . But if i go the folder the file is there . And clicking on it plays the file.

**Environment**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.12.6 16G1510, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.27.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
➜  downloader git:(master) ✗ flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.12.6 16G1510, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.27.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by tanersener** [comment]
Can you please fill issue template fields?

**Comment by aj019** [comment]
@tanersener  I have updated the issue template fields . Is there any their any other field that you require me to fill ?

**Comment by tanersener** [comment]
@aj019 thanks, can you add your command output please? 

I can see what you're trying to do but I don't know what `ffmpeg` has done? I need to see the logs to confirm that `ffmpeg` encoded your file correctly.

Meantime, what happens when you don't specify bitrate with `-ab 192000` or specify it as `-ab 192k`?
