### ISSUE TITLE
Unable to make video  from images in Nokia 6 phone.

### ISSUE THREAD

**Issue by Ronakgadhia** [tanersener/flutter-ffmpeg#54]
**Description**
I am trying to make video from images but it is not working in Nokia 6 ophone. It is working fine  in motoroal phone. Can you please help me to fix this problem?

It returns rc code 1 and nothing happens.

**Comment by tanersener** [comment]
Did you check the output from `_flutterFFmpeg.getLastCommandOutput()`?

**Comment by Ronakgadhia** [comment]
> Did you check the output from `_flutterFFmpeg.getLastCommandOutput()`?

I am checking...

**Comment by Ronakgadhia** [comment]
> Did you check the output from `_flutterFFmpeg.getLastCommandOutput()`?

I have checked. Below is my log.

D/flutter-ffmpeg(26892): Running FFmpeg with arguments: [-hide_banner, -y, -loop, 1, -i, /storage/emulated/0/Pictures/image-cac52d28-b422-48b3-be28-b3450577aba6.jpg, -loop, 1, -i, /storage/emulated/0/Pictures/image-f3755e50-e3f2-4b5f-a5f2-b378be810a1b.jpg, -loop, 1, -i, /storage/emulated/0/Pictures/image-834fd6bd-8438-4b8c-a460-619858165d2a.jpg, -filter_complex, [0:v]setpts=PTS-STARTPTS,scale=w='if(gte(iw/ih,640/427),min(iw,640),-1)':h='if(gte(iw/ih,640/427),-1,min(ih,427))',scale=trunc(iw/2)*2:trunc(ih/2)*2,setsar=sar=1/1,split=2[stream1out1][stream1out2];[1:v]setpts=PTS-STARTPTS,scale=w='if(gte(iw/ih,640/427),min(iw,640),-1)':h='if(gte(iw/ih,640/427),-1,min(ih,427))',scale=trunc(iw/2)*2:trunc(ih/2)*2,setsar=sar=1/1,split=2[stream2out1][stream2out2];[2:v]setpts=PTS-STARTPTS,scale=w='if(gte(iw/ih,640/427),min(iw,640),-1)':h='if(gte(iw/ih,640/427),-1,min(ih,427))',scale=trunc(iw/2)*2:trunc(ih/2)*2,setsar=sar=1/1,split=2[stream3out1][stream3out2];[stream1out1]pad=width=640:height=427:x=(640-iw)/2:y=(427-ih)/2:color=#00000000,trim=duration=3,select=lte(n\,90)[stream1overlaid];[stream1out2]pad=width=640:height=427:x=(640-iw)/2:y=(427-ih)/2:color=#00000000,trim=duration=1,select=lte(n\,30)[stream1ending];[stream2out1]pad=width=640:height=427:x=(640-iw)/2:y=(427-ih)/2:color=#00000000,trim=duration=2,select=lte(n\,60)[stream2overlaid];[stream2out2]pad=width=640:height=427:x=(640-iw)/2:y=(427-ih)/2:color=#00000000,trim=duration=1,select=lte(n\,30),split=2[stream2starting][stream2ending];[stream3out1]pad=width=640:height=427:x=(640-iw)/2:y=(427-ih)/2:color=#00000000,trim=duration=2,select=lte(n\,60)[stream3overlaid];[stream3out2]pad=width=640:height=427:x=(640-iw)/2:y=(427-ih)/2:color=#00000000,trim=duration=1,select=lte(n\,30)[stream3starting];[stream2starting][stream1ending]blend=all_expr='if(gte(X,(W/2)*T/1)*lte(X,W-(W/2)*T/1),B,A)':shortest=1[stream2blended];[stream3starting][stream2ending]blend=all_expr='if(gte(X,(W/2)*T/1)*lte(X,W-(W/2)*T/1),B,A)':shortest=1[stream3blended];[stream1overlaid][stream2blended][stream2overlaid][stream3blended][stream3overlaid]concat=n=5:v=1:a=0,scale=w=640:h=424,format=yuv420p[video], -map, [video], -vsync, 2, -async, 1, -c:v, mpeg4, -r, 30, /sdcard/Pictures/output.mp4].

D/flutter-ffmpeg(26892): FFmpeg exited with rc: 1
I/flutter (26892): Last statistics
I/flutter (26892): Statistics: time: 0, size: 0, bitrate: 0.0, speed: 0.0, videoFrameNumber: 0, videoQuality: 0.0, videoFps: 0.0

**Comment by Ronakgadhia** [comment]
> Did you check the output from `_flutterFFmpeg.getLastCommandOutput()`?

Here is the last command result.

 Last command result >> Input #0, image2, from '/storage/emulated/0/Pictures/image-5810d56d-0772-4699-b871-6831f8a9bf00.jpg':
I/flutter (28511):   Duration: 00:00:00.04, start: 0.000000, bitrate: 1403457 kb/s
I/flutter (28511):     Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 3456x4608, 25 tbr, 25 tbn, 25 tbc
I/flutter (28511): Input #1, image2, from '/storage/emulated/0/Pictures/image-f3755e50-e3f2-4b5f-a5f2-b378be810a1b.jpg':
I/flutter (28511):   Duration: 00:00:00.04, start: 0.000000, bitrate: 1429818 kb/s
I/flutter (28511):     Stream #1:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 3456x4608, 25 tbr, 25 tbn, 25 tbc
I/flutter (28511): Input #2, image2, from '/storage/emulated/0/Pictures/image-834fd6bd-8438-4b8c-a460-619858165d2a.jpg':
I/flutter (28511):   Duration: 00:00:00.04, start: 0.000000, bitrate: 1320954 kb/s
I/flutter (28511):     Stream #2:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 3456x4608, 25 tbr, 25 tbn, 25 tbc
I/flutter (28511): /sdcard/Pictures/output.mp4: Permission denied

**Comment by tanersener** [comment]
> I/flutter (28511): /sdcard/Pictures/output.mp4: Permission denied

This is the error you need to fix. You don't have permissions to write on that folder.

**Comment by Ronakgadhia** [comment]
Ok. But the permission is already granted. Could you please give me any suggestions?

**Comment by tanersener** [comment]
Your issue is about writing into `/sdcard` folder, not about loading images from gallery. And it is not an issue about the library. It's an `Android` issue.

There are a lot of things that can cause this. I suspect it is a [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider) limitation but I'm not % 100 sure. Please take a look at [Permissions @ SAF](https://developer.android.com/guide/topics/providers/document-provider#permissions) guide.

**Comment by Ronakgadhia** [comment]
Okay. Thank you for your reply. I expect that you will provide gallery image multi picker example to ffmpeg Video (Multiple images to video) in upcoming days.

**Comment by tanersener** [comment]
> I expect that you will provide gallery image multi picker example to ffmpeg Video (Multiple images to video) in upcoming days.

I already have an example which uses multiple images as input and produces a video. Why should I need to do that?
