### ISSUE TITLE
Parameter to access device camera

### ISSUE THREAD

**Issue by gbaski** [tanersener/flutter-ffmpeg#55]
What's the ffmpeg parameter to access device camera on android and IOS?
Use-case: Input device camera, output to `rtmp://` url.

**Comment by tanersener** [comment]
Please take a look at [this guide](https://github.com/tanersener/mobile-ffmpeg/wiki/Camera-Support) in the parent project `mobile-ffmpeg`. Everything in that document is valid for `flutter_ffmpeg` too.

**Comment by gbaski** [comment]
> Please take a look at [this guide](https://github.com/tanersener/mobile-ffmpeg/wiki/Camera-Support) in the parent project `mobile-ffmpeg`. Everything in that document is valid for `flutter_ffmpeg` too.

Glanced through it, I need an insight for my use-case. I'm looking at using this plugin for live broadcasting. I want to ingest rtmp:// into Media Server for the purpose of broadcasting to audience.

What's the possibility with flutter-ffmpeg?
How can i go about the playback?

**Comment by tanersener** [comment]
Please take a look at [this](https://trac.ffmpeg.org/wiki/StreamingGuide) guide about streaming. Unfortunately this library doesn't support playback, you need to use another library for that.

**Comment by gbaski** [comment]
Thanks a lot, i found https://github.com/tcking/GPlayer for playback. :smile:

**Comment by carlosandres555** [comment]
Hi,  how use a ffmpeg for a stream a server rtsp?.

Thanks
