### ISSUE TITLE
ffmpeg execute returns 1 error code

### ISSUE THREAD

**Issue by huzeyfecoskun** [tanersener/flutter-ffmpeg#56]
-i [absolute-path-in.mp4] -vf "crop=in_h" [absolute-path-out.mp4]

gives error code : 1

bir türlü çalıştıramadım video yu 1:1 ölçeğinde croplayamıyorum.

**Comment by huzeyfecoskun** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/673053/63302470-cf233080-c2e5-11e9-8d53-dd0173356eef.jpg)
in windows command is working as i expected

**Comment by tanersener** [comment]
I need to see the output of `_flutterFFmpeg.getLastCommandOutput()` to understand the cause of the failure.

By the way, you don't need to use quotes to define video filter in your command.

**Comment by huzeyfecoskun** [comment]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/user/0/com.mekteply.app/app_flutter/Movies/mekteply/1566602155881.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-08-23T23:16:00.000000Z
    com.android.version: 9
  Duration: 00:00:03.78, start: 0.000000, bitrate: 6179 kb/s
    Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p(tv, unknown/bt470bg/unknown), 2280x1080, 6171 kb/s, SAR 1:1 DAR 19:9, 29.45 fps, 29.58 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2019-08-23T23:16:00.000000Z
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 12 kb/s (default)
    Metadata:
      creation_time   : 2019-08-23T23:16:00.000000Z
      handler_name    : SoundHandle
Not overwriting - exiting

**Comment by huzeyfecoskun** [comment]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/user/0/com.mekteply.app/app_flutter/Movies/mekteply/1566603240612.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-08-23T23:34:04.000000Z
    com.android.version: 9
  Duration: 00:00:02.95, start: 0.000000, bitrate: 6240 kb/s
    Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p(tv, unknown/bt470bg/unknown), 2280x1080, 6239 kb/s, SAR 1:1 DAR 19:9, 29.60 fps, 29.58 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2019-08-23T23:34:04.000000Z
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 12 kb/s (default)
    Metadata:
      creation_time   : 2019-08-23T23:34:04.000000Z
      handler_name    : SoundHandle
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mpeg4 (native))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[Parsed_crop_0 @ 0x7d1f8a2b00] Invalid too big or non positive size for width '2280' or height '2280'
[Parsed_crop_0 @ 0x7d1f8a2b00] Failed to configure input pad on Parsed_crop_0
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!

**Comment by tanersener** [comment]
> Invalid too big or non positive size for width '2280' or height '2280'

You need to fix this error. It looks like `trim` filter tries to crop your video to `2280x2280` and fails.
