### ISSUE TITLE
Stream audio from phone's mic

### ISSUE THREAD

**Issue by aslanyi** [tanersener/flutter-ffmpeg#58]
I streamed mic with camera but i want to stream mic only. How can i ?

**Comment by tanersener** [comment]
Can you provide the command you've used?

**Comment by aslanyi** [comment]
I used this command.
`_flutterFFmpeg.execute('-f android_camera -i 0:0 -ab 32k -ac 1 -f flv rtmp://0.0.0.0/myapp/test'`

**Comment by tanersener** [comment]
I haven't tested recording audio before and it looks like you can't record audio using `android_camera` device. 

Do you have a documentation reference that says recording audio is possible?

**Comment by aslanyi** [comment]
Yes, your mobile_ffmpeg documentation says android camera recording audio.

**Comment by tanersener** [comment]
Can you show me where?

**Comment by aslanyi** [comment]
it is [in 2.1.6](https://github.com/tanersener/mobile-ffmpeg/blob/master/README.md#21-android)

**Comment by tanersener** [comment]
Thanks. That reference was wrong, it is fixed now. Do you a reference on official `ffmpeg` documentation?

**Comment by aslanyi** [comment]
I used arecord for streaming mic in linux system.
`arecord -f cd -D plughw:1,0 | ffmpeg -re -i - -ab 32k -ac 1 -f flv rtmp://0.0.0.0/myapp/test` like this.
But i didnt find library like this in the flutter.

**Comment by tanersener** [comment]
You can use [audio_recorder](https://pub.dev/packages/audio_recorder) to record audio but `flutter_ffmpeg` does not support pipes. So it won't help you with `flutter_ffmpeg`.

**Comment by aslanyi** [comment]
Okey, thank you

**Comment by lukepighetti** [comment]
@tanersener is it because pipes are not implemented or is there a technical blocker for implementing them?

**Comment by tanersener** [comment]
@lukepighetti When you execute `arecord -f cd -D plughw:1,0 | ffmpeg -re -i - -ab 32k -ac 1 -f flv rtmp://0.0.0.0/myapp/test` in an `Unix` terminal, `bash` redirects the output of `arecord` to `ffmpeg`.

Unfortunately, in `flutter_ffmpeg` we don't have `bash`. We need to implement a stack which reads the output of process 1 and redirects it as the input for process 2. It is not an easy task, especially for iOS/tvOS.
