### ISSUE TITLE
提取视频的每一帧的图片

### ISSUE THREAD

**Issue by wswww** [tanersener/flutter-ffmpeg#60]
你好,请问如何利用fluent-ffmpeg将视频转换成图片呢?比如:60帧视频10秒钟,转成图片应该是600张.备注:不是通过命令行的形式,是通过nodejs调用api的方式.谢谢!
Hello, how to use fluent-ffmpeg to convert video into pictures? For example, 60 frames of video in 10 seconds should be converted into 600 pictures. Note: not through the command line, but through nodejs to call the api. Thank you!

**Comment by tanersener** [comment]
`flutter-ffmpeg` is different than the `fluent-ffmpeg`. I think you need to ask this question to [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg).

**Comment by lukepighetti** [comment]
Honestly man I think you can probably close this. I don't think anyone would hold it against you. :)

**Comment by tanersener** [comment]
@lukepighetti I prefer to close it after 30 days of inactivity
