### ISSUE TITLE
xcode Archive file not armv7 impl

### ISSUE THREAD

**Issue by davewang** [tanersener/flutter-ffmpeg#62]
![image](https://user-images.githubusercontent.com/555195/65399872-ae249280-ddf1-11e9-9377-a544c0266d5b.png)

      Showing All Messages
        "_OBJC_CLASS_$_MobileFFmpegConfig", referenced from:
            objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
        "_OBJC_CLASS_$_MobileFFmpeg", referenced from:
            objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
        "_OBJC_CLASS_$_ArchDetect", referenced from:
            objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      ld: symbol(s) not found for architecture armv7
      clang: error: linker command failed with exit code 1 (use -v to see invocation)

xcode run to real device(eg.iPad4) is ok,but build->Generic iOS Device is error.

**Comment by tanersener** [comment]
Please see #45
