### ISSUE TITLE
Flutter-FFmpeg: Build Fail in new app after adding flutter_ffmpeg with exit code 1

### ISSUE THREAD

**Issue by rdcoder33** [tanersener/flutter-ffmpeg#64]
So, I just created a new app and only dependency, I added is f`lutter_ffmpeg: ^0.2.7`.
But when I tried to run debug build got this error: 

```
Launching lib\main.dart on RMX1801 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not download mobile-ffmpeg-https.aar (com.arthenica:mobile-ffmpeg-https:4.2.2)
   > Could not get resource 'https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.2.2/mobile-ffmpeg-https-4.2.2.aar'.
      > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 32s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)


```
I haven't written even a single line of code, it's just default incrementation app comes with every flutter project. I didn't even imported the package yet!

> Min Sdk Version has been changed to 24 still getting the same error.

**Comment by tanersener** [comment]
> Could not get resource 'https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.2.2/mobile-ffmpeg-https-4.2.2.aar'.
      > Connection reset

This error looks like a connection failure. 

Can you access https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.2.2/mobile-ffmpeg-https-4.2.2.aar ?

**Comment by rdcoder33** [comment]
> ```
> > Could not get resource 'https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.2.2/mobile-ffmpeg-https-4.2.2.aar'.
>   > Connection reset
> ```
> 
> This error looks like a connection failure.
> 
> Can you access https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.2.2/mobile-ffmpeg-https-4.2.2.aar ?

What exactly you mean by "Can you access"? I tried to Open the line and a .aar file got downloaded. What should I do next?

**Comment by tanersener** [comment]
> What exactly you mean by "Can you access"? I tried to Open the line and a .aar file got downloaded. What should I do next?

I mean `get` or `download`. 

Your `gradle` error says that it can't download the .aar file. If you can download the file from the browser this means that something stops `gradle` from downloading the file. A lot of different things can cause this. Can you download the same file from bash?

**Comment by rdcoder33** [comment]
@tanersener Well it was internet issue, it requires a very good internet speed for the first run so that It can download those File.
I just wanna say thanks for being so active with this Plugin, this is something which will help a lot of developers. My only request is a few tutorials on how to use popular FFmpeg commands with this plugin.
Good Job Man!

**Comment by jj-gh** [comment]
I'm also having the same issue. The resource url is returning 403 in the browser.

```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.arthenica:mobile-ffmpeg-<flutter ffmpeg full>:4.4.LTS.
     Required by:
         project :app > project :flutter_ffmpeg
      > Could not resolve com.arthenica:mobile-ffmpeg-<flutter ffmpeg full>:4.4.LTS.
         > Could not get resource 'https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-%3Cflutter%20ffmpeg%20full%3E/4.4.LTS/mobile-ffmpeg-%3Cflutter%20ffmpeg%20full%3E-4.4.LTS.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-%3Cflutter%20ffmpeg%20full%3E/4.4.LTS/mobile-ffmpeg-%3Cflutter%20ffmpeg%20full%3E-4.4.LTS.pom'. Received status code 400 from server: Bad Request
```

**Comment by tanersener** [comment]
@jj-gh The latest versions of `flutter_ffmpeg` doesn't depend on `jcenter`. Please make sure that `mavenCentral()` is defined as a repository in your `build.gradle` and it is listed before `jcenter()`.

**Comment by jj-gh** [comment]
i don't have jcenter in my build.gradle

```
buildscript {
    ext.kotlin_version = '1.3.50'
    ext.flutterFFmpegPackage  = "<flutter ffmpeg full-lts>"
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by tanersener** [comment]
@jj-gh This is not a valid package name `<flutter ffmpeg full>`. Please try with one of the packages listed in the README.

**Comment by jj-gh** [comment]
Oops, sorry I got confused. I thought it was supposed to be in XML tag format due to the text color formatting in the readme. Thanks for the help!
