### ISSUE TITLE
Flutter FFmpeg isaround 8 mb in size.How to reduce size by using only relevant libraries.

### ISSUE THREAD

**Issue by Sjosh-cronJ** [tanersener/flutter-ffmpeg#65]
Is there any way to reduce size of the app using this plugin. Its very big in size also i need only media metadata information thats the only reason I use this plugin.

**Comment by tanersener** [comment]
> I want to extract video creation date-time but FFmpeg is giving creation date-time as date-time of the video when the video is picked not actual creation date-time.

Could you please provide logs about this case?

> Also is there any way to reduce size of the app using this plugin. Its very big in size also i need only media metadata information thats the only reason I use this plugin.

Which package do you use? Can you try installing `min` package?

**Comment by Sjosh-cronJ** [comment]
I use default https package

**Comment by Sjosh-cronJ** [comment]
i tried using min package but in podfile it is giving me an error.

**Comment by tanersener** [comment]
Why don't you share the error? `min` package is the smallest package available. You must install it if you want to reduce the size. However I can't guarantee that `min` package will be small enough in size.

**Comment by Sjosh-cronJ** [comment]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find androidx.appcompat:appcompat:27.0.0.                
     Searched in the following locations:                               
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/google/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/google/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/android/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/android/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - https://jcenter.bintray.com/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - https://jcenter.bintray.com/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - https://maven.google.com/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - https://maven.google.com/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - https://google.bintray.com/exoplayer/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - https://google.bintray.com/exoplayer/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
     Required by:                                                       
         project :app                                                   
   > Could not find androidx.appcompat:appcompat:27.0.0.                
     Searched in the following locations:                               
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/google/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/google/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/android/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - file:/Users/sudhansujoshi/Library/Android/sdk/extras/android/m2repository/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - https://jcenter.bintray.com/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - https://jcenter.bintray.com/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - https://maven.google.com/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - https://maven.google.com/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
       - https://google.bintray.com/exoplayer/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.pom
       - https://google.bintray.com/exoplayer/androidx/appcompat/appcompat/27.0.0/appcompat-27.0.0.jar
     Required by:                                                       
         project :app > project :flutter_ffmpeg > com.arthenica:mobile-ffmpeg-min:4.2.2

**Comment by Sjosh-cronJ** [comment]
```
buildscript {
     ext {
       compileSdkVersion = 28                
       targetSdkVersion = 28               
       playServicesLocationVersion = "16.0.0"
       supportLibVersion = "27.0.0"
       buildToolsVersion = "25.0.2"
   }
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}
// configurations.all {
// resolutionStrategy {
//     force 'com.android.support:support-v4:27.1.0'
// }}
configurations {
    all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}
rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

ext.flutterFFmpegPackage = 'min'


task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by Sjosh-cronJ** [comment]
Above is my android/build.gradle file

**Comment by tanersener** [comment]
Can you share your `android/app/build.gradle` file?

**Comment by Sjosh-cronJ** [comment]
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}
def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {                      
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}
configurations.all {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == "com.android.support") {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion "26.+"
                }
            }
        }
        all*.exclude group: 'com.google.guava', module: 'listenablefuture'
    }
def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '11'
}
def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '5.1.0'
}
apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
     // Reduce your application size with this configuration
    // aaptOptions {
    //     ignoreAssetsPattern "!x86:!*ffprobe"
    // }
    compileSdkVersion 28
    compileOptions {
         sourceCompatibility JavaVersion.VERSION_1_8
         targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.xx.xxxapp"
        minSdkVersion 24
        targetSdkVersion 28
        versionCode 11
        versionName '5.1'
         ndk {
            abiFilters = []
            abiFilters.addAll(ABI_FILTERS.split(';').collect{it as String})
        }
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    splits {
        // Configures multiple APKs based on ABI.
        abi {
            // Enables building multiple APKs per ABI.
            enable true
            // By default all ABIs are included, so use reset() and include to specify that we only
            // want APKs for armeabi-v7a and arm64-v8a.

            // Resets the list of ABIs that Gradle should create APKs for to none.
            reset()

            // Specifies a list of ABIs that Gradle should create APKs for.
            // include "armeabi-v7a", "arm64-v8a"

            // Specifies that we do not want to also generate a universal APK that includes all ABIs.
            universalApk false
        }
    }
    
    signingConfigs {
    release {
        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile file(keystoreProperties['storeFile'])
        storePassword keystoreProperties['storePassword']
    }
   }
   buildTypes {
       release {
           signingConfig signingConfigs.release
           minifyEnabled true
           useProguard true
           proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
       }
   }
}
flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    def supportLibVersion = rootProject.ext.supportLibVersion
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'  
    implementation "androidx.appcompat:appcompat:$supportLibVersion"
    implementation 'com.google.firebase:firebase-messaging:19.0.1'
}
apply plugin: 'com.google.gms.google-services'

**Comment by tanersener** [comment]
`implementation "androidx.appcompat:appcompat:$supportLibVersion"` dependency is wrong. You have `supportLibVersion = "27.0.0"` in your parent `build.gradle`. That converts

`implementation "androidx.appcompat:appcompat:$supportLibVersion"`

to 

`implementation "androidx.appcompat:appcompat:27.0.0"`

Unfortunately `androidx.appcompat:appcompat` package doesn't have a version `27.0.0`. You need to fix that.

**Comment by Sjosh-cronJ** [comment]
Thanks for quick replies. 
Size is reduced from 52 Mb to 43 Mb.
Is there any other way to reduce size since I need the only library that provides flutterFFmpeg.getMediaInformation() functionality. Is there any way to only keep lib that has this functionality and removing rest.

**Comment by tanersener** [comment]
You can use the following block in your `build.gradle` to exclude an .so library.

```
android {
    packagingOptions {
        exclude 'lib/x86/<library>'
        exclude 'lib/x86_64/<library>'
        exclude 'lib/armeabi-v7a/<library>'
        exclude 'lib/arm64-v8a/<library>'
    }
}
```

In your case, excluding some of the following .so files may help you to decrease application size. Unfortunately, I'm not sure which .so files are mandatory for `getMediaInformation` and which are not. So you need to test excluding each .so file one by one and exclude all unused libraries in the end.

```
libavcodec.so
libavdevice.so
libavfilter.so
libavformat.so
libavutil.so
libswresample.so
libswscale.so
```

**Comment by Sjosh-cronJ** [comment]
What about ios.

**Comment by tanersener** [comment]
> What about ios.

I don't have an easy solution for `ios`. 

> And after excluding any of these package project is not compiling

It is not possible to comment without understanding at which step compilation fails or seeing the error message.
