### ISSUE TITLE
Can't use flutter-ffmpeg in Android 6 

### ISSUE THREAD

**Issue by pullatjunaid** [tanersener/flutter-ffmpeg#69]
error while running 

Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 23 cannot be smaller than version 24 declared in library [:flutter_ffmpeg]

How can i use this plugin in Android 6 or 5.
Thanks in advance.

**Comment by tanersener** [comment]
See #20

**Comment by pullatjunaid** [comment]
I solved this issue by 
Adding 
```
ext {
    flutterFFmpegPackage  = "<package name>"
}
```

To
`android/build.gradle`

![Capture](https://user-images.githubusercontent.com/50260600/66265634-7f69db80-e837-11e9-9227-f368164f0985.PNG)
