### ISSUE TITLE
Unknown encoder 'libmp3lame'

### ISSUE THREAD

**Issue by gaojuanjuan** [tanersener/flutter-ffmpeg#74]
ffmpeg -y -i /Users/develop1/vocal.wav -i /Users/develop1/instrumental.m4a -filter_complex "[0:0][1:0] amix=inputs=2:duration=longest" -c:a libmp3lame /Users/develop1/test/audio.mp3

**Comment by tanersener** [comment]
`lame` encoder is only available in `audio`, `full` and `full-gpl` packages. Please install one of these using instructions in [2.1 Packages](https://github.com/tanersener/flutter-ffmpeg#21-packages).

**Comment by gaojuanjuan** [comment]
Thank you
