### ISSUE TITLE
I combined the two audios and one video into one video, but the last video I got was only the first input audio, and the second audio was not merged.

### ISSUE THREAD

**Issue by gaojuanjuan** [tanersener/flutter-ffmpeg#75]
I combined the two audios and one video into one video, but the last video I got was only the first input audio, and the second audio was not merged.

ffmpeg -i /Users/develop1/sheng.mp4 -i /Users/develop1/vocal.wav -i /Users/develop1/strumental.wav -c copy -map 0:v:0 -map 1:a:0 -map 2:a:0 /Users/develop1/test/output.mp4

**Comment by tanersener** [comment]
Can you please try your command on desktop `ffmpeg`? In this way, we can understand if it is an issue about `ffmpeg` itself.

**Comment by gaojuanjuan** [comment]
> Can you please try your command on desktop `ffmpeg`? In this way, we can understand if it is an issue about `ffmpeg` itself.

Sorry, it is my inaccuracy, my order is on the desktop.

**Comment by tanersener** [comment]
Well, I'm not sure about the reason. Can you ask this questions to [ffmpeg-user](https://ffmpeg.org/mailman/listinfo/ffmpeg-user) mailing list?
