### ISSUE TITLE
Compressing video Files by flutter ffmpeg. #Question

### ISSUE THREAD

**Issue by kunaljosh369** [tanersener/flutter-ffmpeg#77]
@flutterFFmped
Description of what the issue is about.

Trying to compress video file but its not working also i am unable to get enough info from Readme

``` 
int compressedFile = await _flutterFFmpeg.executeWithArguments(
        ["-i", file.path, "-c:v", "mpeg4", 'c' + file.path]);
    print(compressedFile);
```

I want to:-
1.Compress video file
2. Delete the old file and replaced it with the new one.

**Comment by tanersener** [comment]
Did you check last return code and last command output? README includes examples for these two commands.
