### ISSUE TITLE
enableStatisticsCallback returning previous values on next run

### ISSUE THREAD

**Issue by esDotDev** [tanersener/flutter-ffmpeg#79]
**Description**
When running multiple ffmpeg tasks, the ffmpeg.enableStatisticsCallback returns the value of the previous task, the first time that it fires. 

**Expected behavior**
When starting a new execution, time=0 in the first received stats callback.

**Current behavior**
When starting a new execution, time = the ending value of the previous execution.

For example, if I cancel an execution at 10s, and run a new execution. The first call to statsCallback, will have a time value of 10000, rather than 0.

**Environment**
[√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.418], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.39.2)
[√] Connected device (1 available)

**Comment by tanersener** [comment]
You are right. Do you see an improvement if you execute `_flutterFFmpeg.resetStatistics();` before starting a new execution?

**Comment by esDotDev** [comment]
That seems to fix it :)

**Comment by tanersener** [comment]
Great 👍
