### ISSUE TITLE
Unknown "x265"

### ISSUE THREAD

**Issue by pepealonso95** [tanersener/flutter-ffmpeg#86]
Cant run with codec x265. 

Already tried installing package https-gpl as android package in android/build.gradle

`
ext{
    flutterFFmpegPackage  = "https-gpl"
}
`

**Comment by pepealonso95** [comment]
Loading flutter-ffmpeg.
I/mobile-ffmpeg( 7779): Loading mobile-ffmpeg.
E/flutter ( 7779): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: dlopen failed: library "libcpufeatures.so" not found
E/flutter ( 7779): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
E/flutter ( 7779): 	at java.lang.System.loadLibrary(System.java:1669)
E/flutter ( 7779): 	at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:40)
E/flutter ( 7779): 	at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
E/flutter ( 7779): 	at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:113)
E/flutter ( 7779): 	at com.arthenica.mobileffmpeg.Config.enableLogCallback(Config.java:207)
E/flutter ( 7779): 	at com.arthenica.flutter.ffmpeg.FlutterFFmpegPlugin.onMethodCall(FlutterFFmpegPlugin.java:169)
E/flutter ( 7779): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter ( 7779): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter ( 7779): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/flutter ( 7779): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 7779): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter ( 7779): 	at android.os.Looper.loop(Looper.java:160)
E/flutter ( 7779): 	at android.app.ActivityThread.main(ActivityThread.java:6898)
E/flutter ( 7779): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7779): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/flutter ( 7779): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 7779):
F/flutter ( 7779): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).

**Comment by tanersener** [comment]
`https-gpl` package is already tested and verified. Can you delete your `build` folder and try again?

**Comment by pepealonso95** [comment]
i have run flutter clean a couple of times but it didnt fix the problem

**Comment by pepealonso95** [comment]
I get the same error trying every other package.

This is a snippet of the code I run:

```
flutterFFmpeg.execute("-i ${widget.path} -c:v x264 $newPath").then((rc){
print(rc);
});
```

**Comment by tanersener** [comment]
Your error is not about the package or the command you're trying to run. 

You have a more general error. You can not load the library due to the following UnsatisfiedLinkError. Are you using the the latest `flutter_ffmpeg` version?

```
E/flutter ( 7779): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: dlopen failed: library "libcpufeatures.so" not found
```

**Comment by pepealonso95** [comment]
Yes i am using the latest version

```
I/ACodec  (25640): codec does not support config priority (err -2147483648)
I/ACodec  (25640): codec does not support config operating rate (err -2147483648)
I/ACodec  (25640): codec does not support config priority (err -2147483648)
I/ACodec  (25640): codec does not support config operating rate (err -2147483648)
W/ExtendedACodec(25640): Failed to get extension for extradata parameter
```

**Comment by pepealonso95** [comment]
`I/flutter (25640): Unknown encoder 'x264'`

**Comment by pepealonso95** [comment]
I figured my error could be on my android/build.gradle as the rest, but i think i followed instructions thoroughly:

```
buildscript {

    ext {
        compileSdkVersion   = 28                // or higher
        targetSdkVersion    = 28                // or higher
        minSdkVersion = 24
        supportLibVersion   = "1.0.2"           // or higher
       // playServicesLocationVersion = "16.0.0"
        kotlin_version = '1.3.10'  // or higher
 
    }
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.0'
        classpath 'io.fabric.tools:gradle:1.31.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext{
    flutterFFmpegPackage  = 'https-gpl'
}
```

**Comment by pepealonso95** [comment]
just to be clear, the compressor works fine when i use mpeg4

**Comment by pepealonso95** [comment]
got it, the coded reference should be "libx256" not "x265"

**Comment by tanersener** [comment]
Yes, it should be `libx265` but you stated that you have the following error. So I was concentrated on fixin it first. Anyway, great news 👍

`
E/flutter ( 7779): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: dlopen failed: library "libcpufeatures.so" not found
`

**Comment by pepealonso95** [comment]
maybe a flutter clean helped, it would be very useful if the package had a guide "for dummies". Anyways great work man!
