### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION in ffmpeg flutter

### ISSUE THREAD

**Issue by shubham12387** [tanersener/flutter-ffmpeg#89]
Errors:

Syncing files to device vivo Y21L...
I/flutter (21932): Loading flutter-ffmpeg.
I/OpenGLRenderer(21932): Initialized EGL, version 1.4
I/mobile-ffmpeg(21932): Loading mobile-ffmpeg.
W/linker (21932): libmobileffmpeg-abidetect.so: unused DT entry: type 0x6ffffffe arg 0x694
W/linker (21932): libmobileffmpeg-abidetect.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker (21932): libcpufeatures.so: unused DT entry: type 0x6ffffffe arg 0x7d0
W/linker (21932): libcpufeatures.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker (21932): libmobileffmpeg-armv7a-neon.so: unused DT entry: type 0x6ffffffe arg 0x6290
W/linker (21932): libmobileffmpeg-armv7a-neon.so: unused DT entry: type 0x6fffffff arg 0xa
W/linker (21932): libc++_shared.so: unused DT entry: type 0x6ffffffe arg 0x2b994
W/linker (21932): libc++_shared.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker (21932): libavcodec.so: unused DT entry: type 0x6ffffffe arg 0x6538
W/linker (21932): libavcodec.so: unused DT entry: type 0x6fffffff arg 0x4
W/linker (21932): libavfilter.so: unused DT entry: type 0x6ffffffe arg 0x44f4
W/linker (21932): libavfilter.so: unused DT entry: type 0x6fffffff arg 0x7
W/linker (21932): libswscale.so: unused DT entry: type 0x6ffffffe arg 0xe94
W/linker (21932): libswscale.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker (21932): libavformat.so: unused DT entry: type 0x6ffffffe arg 0x7414
W/linker (21932): libavformat.so: unused DT entry: type 0x6fffffff arg 0x4
W/linker (21932): libavutil.so: unused DT entry: type 0x6ffffffe arg 0x6d84
W/linker (21932): libavutil.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker (21932): libswresample.so: unused DT entry: type 0x6ffffffe arg 0xe2c
W/linker (21932): libswresample.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker (21932): libavdevice.so: unused DT entry: type 0x6ffffffe arg 0x1448
W/linker (21932): libavdevice.so: unused DT entry: type 0x6fffffff arg 0x5
I/mobile-ffmpeg(21932): Loaded mobile-ffmpeg-https-arm-v7a-neon-4.2-lts.
I/flutter (21932): Loaded flutter-ffmpeg-android-arm-v7a-neon.
D/mobile-ffmpeg(21932): Callback thread started.
D/flutter-ffmpeg(21932): Running FFmpeg command: -i File: '/storage/emulated/0/video_5.mp4'.mp4 -ss 00:00:01.000 -vframes 1 recordedImage.jpg with delimiter .
I/Timeline(21932): Timeline: Activity_idle id: android.os.BinderProxy@38869914 time:113811921
D/flutter-ffmpeg(21932): FFmpeg exited with rc: 1
F/art (21932): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI NewByteArray called with pending exception 'java.lang.RuntimeException' thrown in unknown throw location
F/art (21932): art/runtime/check_jni.cc:65] in call to NewByteArray

My Code:

void _pickVideo() async {
ImagePicker.pickVideo(source: ImageSource.gallery)
.then((File recordedVideo) {
if (recordedVideo != null && recordedVideo.path != null) {
setState(() {
secondButtonText = 'saving in progress...';
File recordedImage;
_flutterFFmpeg
.execute(
"-ss 00:1:45 -i $recordedVideo -vframes 1 -q:v 2 $recordedImage.jpg")
.then((rc) => print("FFmpeg process exited with rc $rc"));
GallerySaver.saveImage(recordedImage.path).then((path) {
setState(() {
firstButtonText = 'image saved!';
});
});
});
GallerySaver.saveVideo(recordedVideo.path).then((path) {
setState(() {
secondButtonText = 'video saved!';
});
});
}
});
}

Sir I am using ffmpeg package in my testapp project
I want to select a video from my phone storage and extract one frame at a given time from it and save it to my phone storage. I am using Gallery Saver package it works for saving photos and video but for my specific task it does this error shows in output
Every time i run the code rc exited : 1 comes and then the above error.
App directly crashes after that.
Please Help me Sir!!

**Comment by tanersener** [comment]
As I recommended in #31, please check and see if you like calling `_flutterFFmpeg.execute` in wrong thread or doing something unexpected in `logCallback` or `statisticsCallback` functions.

**Comment by shubham12387** [comment]
Thanks Sir it is working now
But i am getting error not file not found

**Comment by shubham12387** [comment]
Thanks Sir that problem is solved now.. But


I/flutter (29924): File:: Protocol not found
I/flutter (29924): Did you mean file:File:?
I/flutter (29924): FFmpeg process exited with rc 1
Lost connection to device.

File not found what can i do in my code to?

**Comment by tanersener** [comment]
You don't need to include `File:` prefix in your file paths.

**Comment by shubham12387** [comment]
Sir this ffmpeg library requires min sdk version 24 
I am getting this error:

Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [:flutter_ffmpeg] F:\Folder for flutter projects\testflow\build\flutter_ffmpeg\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 21
  	Suggestion: use a compatible library with a minSdk of at most 21,
  		or increase this project's minSdk version to at least 24,
  		or use tools:overrideLibrary="com.arthenica.flutter.ffmpeg" to force usage (may lead to runtime failures)

**Comment by tanersener** [comment]
Please install LTS variant of the library using instruction given in [2.3 LTS Releases](https://github.com/tanersener/flutter-ffmpeg#23-lts-releases). LTS variant supports API Level 16+.

**Comment by shubham12387** [comment]
Apologize Sir I am not able to get how to install it

![33](https://user-images.githubusercontent.com/29892678/71270246-252ce100-2377-11ea-8510-85012fe38079.PNG)
![222](https://user-images.githubusercontent.com/29892678/71270247-252ce100-2377-11ea-9e95-c809bb1e8656.PNG)

**Comment by tanersener** [comment]
Please remove `<` and `>` characters around the package name.
```
flutterFFmpegPackage  = "https-lts"
```

**Comment by shubham12387** [comment]
Sir i am not using File path anywhere in my code

![000](https://user-images.githubusercontent.com/29892678/71304806-4f22e980-23f1-11ea-92f8-0e15e400935a.PNG)

**Comment by tanersener** [comment]
But you are using `ImagePicker`. Can you check if `File` picked by `ImagePicker` has that prefix?

**Comment by shubham12387** [comment]
Sir i used print statement there is not file prefix

![111111](https://user-images.githubusercontent.com/29892678/71342795-cee0bd80-2583-11ea-91f4-66e60904288b.PNG)
![2222222222](https://user-images.githubusercontent.com/29892678/71342796-cee0bd80-2583-11ea-83e3-f3f31c50f71a.PNG)

**Comment by shubham12387** [comment]
I even tried using different filePicker pacakage but it still show the same error

**Comment by tanersener** [comment]
Can you please use `$recordedVideo.path` in your command. You are using `$recordedVideo` right now?

**Comment by shubham12387** [comment]
I am trying to save the extracted frame in my phone storage by using gallery saver package. This is error

My Code -- 
![222222222222](https://user-images.githubusercontent.com/29892678/71397627-1b8bcd80-2644-11ea-8bbe-fb7d5f1b7c9e.PNG)

My Output Error---
![Capture](https://user-images.githubusercontent.com/29892678/71397630-1f1f5480-2644-11ea-8ef5-fab297adc4f0.PNG)

**Comment by tanersener** [comment]
@shubham12387 Your question is not about the library. It is about `flutter`. Why don't you google about it?

**Comment by shubham12387** [comment]
Okay Sir Thanks a lot for your help.

**Comment by shubham12387** [comment]
Thanks Sir, I figured it out
I just needed to specify the path of the output image and it works like magic
