### ISSUE TITLE
AndroidX incompability?

### ISSUE THREAD

**Issue by k2evil** [tanersener/flutter-ffmpeg#90]
**Description**
My app can't be built after I added `flutter_ffmpeg` dependency.

**Logs**
```
Launching lib/main.dart on SM N960F in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  error: resource style/Theme.AppCompat.Light.DarkActionBar (aka com.example.flutter_app_instagram:style/Theme.AppCompat.Light.DarkActionBar) not found.
  /home/user3/Dev/projects/flutter/flutter_app_instagram3/android/app/src/main/res/values/styles.xml:3:5-7:13: AAPT: error: style attribute 'attr/colorPrimary (aka com.example.flutter_app_instagram:attr/colorPrimary)' not found.

  /home/user3/Dev/projects/flutter/flutter_app_instagram3/android/app/src/main/res/values/styles.xml:3:5-7:13: AAPT: error: style attribute 'attr/colorPrimaryDark (aka com.example.flutter_app_instagram:attr/colorPrimaryDark)' not found.

  /home/user3/Dev/projects/flutter/flutter_app_instagram3/android/app/src/main/res/values/styles.xml:3:5-7:13: AAPT: error: style attribute 'attr/colorAccent (aka com.example.flutter_app_instagram:attr/colorAccent)' not found.

  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_ffmpeg...
Running Gradle task 'assembleAarRelease'...


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'flutter_ffmpeg'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Finished with error: The plugin flutter_ffmpeg could not be built due to the issue above.
```

**Environment**
```
user3@User3-Startup:~$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/user3/Dev/Flutter/SDK/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/user3/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/user3/Dev/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/user3/Dev/Android/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM N960F • 2aed2c00863f7ece • android-arm64 • Android 9 (API 28)

• No issues found!

```

**Comment by tanersener** [comment]
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

Can you please fix this warning?

**Comment by k2evil** [comment]
> > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
> 
> Can you please fix this warning?

It already has been defined in local.properties file:
```
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.sdk=/home/user3/Dev/Flutter/SDK/flutter
sdk.dir=/home/user3/Android/Sdk
flutter.versionCode=1
```

**Comment by k2evil** [comment]
I fixed this by upgrading the gradle to `5.4.1-all` and gradle build tools to `3.5.3`, but it only works in debug mode.
I get the same error when I want to build a release apk from my project.

**Comment by tanersener** [comment]
Can you share build logs of the new versions?

**Comment by k2evil** [comment]
> Can you share build logs of the new versions?

What do you mean by "build logs of the new versions"? I don't know which logs do you exactly want

**Comment by tanersener** [comment]
In your first post, you've included logs of your build. 

I was trying to ask for them again since you've upgraded `gradle` and `gradle build tools` to newer versions. Are they the same?

**Comment by k2evil** [comment]
> In your first post, you've included logs of your build.
> 
> I was trying to ask for them again since you've upgraded `gradle` and `gradle build tools` to newer versions. Are they the same?

Yes... The error has been gone in debug mode, but still getting the same error in release mode...

**Comment by tanersener** [comment]
What is printed under the `* What went wrong:` section ?

**Comment by gisinator** [comment]
I can't build in release mode as well. "flutter run" works perfectly, but "flutter run --release" says:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_ffmpeg:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  C:\Users\StudentenEngel\AndroidStudioProjects\faver\build\flutter_ffmpeg\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  C:\Users\StudentenEngel\AndroidStudioProjects\faver\build\flutter_ffmpeg\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  C:\Users\StudentenEngel\AndroidStudioProjects\faver\build\flutter_ffmpeg\intermediates\res\merged\release\values\values.xml:2611: error: resource android:attr/fontVariationSettings not found.
  C:\Users\StudentenEngel\AndroidStudioProjects\faver\build\flutter_ffmpeg\intermediates\res\merged\release\values\values.xml:2612: error: resource android:attr/ttcIndex not found.
  error: failed linking references.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
