### ISSUE TITLE
[Question] Is it possible to determine video volume over time

### ISSUE THREAD

**Issue by hillelcoren** [tanersener/flutter-ffmpeg#91]
Thank you for your work on flutter_ffmpeg!

We're using ffmpeg on the server to determine the volumes of an mp4 file over time to sync multiple videos, for examples:

https://mudeo.app/song/joQeZ6JepZ

Here's the command we're using:

```
ffmpeg -i <file> -af astats=metadata=1:reset=1,ametadata=print:key=lavfi.astats.Overall.RMS_level:file=log.txt -f null -
```

It gives us this output:

```
frame:0    pts:0       pts_time:0
lavfi.astats.Overall.RMS_level=-83.134866
frame:1    pts:1024    pts_time:0.064
lavfi.astats.Overall.RMS_level=-79.609959
frame:2    pts:2048    pts_time:0.128
...
```

We currently need to send the video file to server to make it work, do you know if this would be possible using your package?

**Comment by tanersener** [comment]
I'm not sure if it will be fast enough compared to a server. But yeah, you can use this package to run your command.

**Comment by hillelcoren** [comment]
Thanks, that's great to hear!
