### ISSUE TITLE
use  ffplay for play video

### ISSUE THREAD

**Issue by irdeveloper89** [tanersener/flutter-ffmpeg#96]
Can I use ffplay like this

`ffplay SampleVideo_1280x720_1mb_encrypted.mp4 -decryption_key 76a6c65c5ea762046bd749a2e632ccbb`

for decryption video and play it?

**Comment by tanersener** [comment]
Unfortunately, you can't. `ffplay` is not included in the project. It's on the road map but I don't have a release date for that yet.
