### ISSUE TITLE
disableRedirection fails after upgrade from v0.2.8

### ISSUE THREAD

**Issue by dvorapa** [tanersener/flutter-ffmpeg#98]
**Description**
After upgrade from v0.2.8 to v0.2.10 I get the following error:
```
$ flutter analyze
  error • The method 'disableRedirection' isn't defined for the class
         'FlutterFFmpeg' • lib/main.dart:686:20 • undefined_method
```

**Expected behavior**
A) The option should work
B) The option should not throw an error

**Environment**
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale cs_CZ.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by tanersener** [comment]
Thanks for reporting this issue. Let me analyse the issue and understand the reason.

**Comment by tanersener** [comment]
Can you use `FlutterFFmpegConfig` to invoke `disableRedirection` method? `disableRedirection` method is moved under `FlutterFFmpegConfig` class since `v0.2.9`.

**Comment by dvorapa** [comment]
`FlutterFFmpegConfig`? How to do it?
This is everything I do with ffmpeg:

`final FlutterFFmpeg _flutterFFmpeg = FlutterFFmpeg();`

```
await _flutterFFmpeg
  .execute(
    '-i "$_songPath" -an -vcodec copy "$_tempFolder/${_song.id}.jpg"')
      .then( ... );
```

`_flutterFFmpeg.disableRedirection();`

Nothing else. So if I want to use `disableRedirection` (or any kind of disabling output from ffmpeg), I have to add:
`final FlutterFFmpegConfig _flutterFFmpegConfig = FlutterFFmpegConfig();`
??

There should be some "How to upgrade guide" or some better Changelog for this :D

**Comment by tanersener** [comment]
> There should be some "How to upgrade guide" or some better Changelog for this :D

Yeah, you're right. An upgrade guide would be awesome 😃

**Comment by dvorapa** [comment]
Anyway this is not a bug, right? Can be closed then

**Comment by tanersener** [comment]
Yes, you can close it.
