### ISSUE TITLE
Could not find com.arthenica:mobile-ffmpeg-https:4.3.1.

### ISSUE THREAD

**Issue by gisinator** [tanersener/flutter-ffmpeg#99]
**Description**
I just upgraded flutter to current stable v1.12.13+hotfix.5 and also changed ffmpeg from 0.2.8 to 0.2.10, now I cant build anymore. 

**Expected behavior**
it should build without errors

**Current behavior**
`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.arthenica:mobile-ffmpeg-https:4.3.1.
     Searched in the following locations:`

**Logs**
`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.arthenica:mobile-ffmpeg-https:4.3.1.
     Searched in the following locations:
       - file:/C:/Users/StudentenEngel/AppData/Local/Android/Sdk/extras/m2repository/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - file:/C:/Users/StudentenEngel/AppData/Local/Android/Sdk/extras/m2repository/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - file:/C:/Users/StudentenEngel/AppData/Local/Android/Sdk/extras/google/m2repository/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - file:/C:/Users/StudentenEngel/AppData/Local/Android/Sdk/extras/google/m2repository/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - file:/C:/Users/StudentenEngel/AppData/Local/Android/Sdk/extras/android/m2repository/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - file:/C:/Users/StudentenEngel/AppData/Local/Android/Sdk/extras/android/m2repository/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - http://download.flutter.io/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - http://download.flutter.io/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - http://download.flutter.io/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - http://download.flutter.io/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - http://download.flutter.io/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - http://download.flutter.io/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://google.bintray.com/exoplayer/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://google.bintray.com/exoplayer/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-https/4.3.1/mobile-ffmpeg-https-4.3.1.jar
     Required by:
         project :app > project :flutter_ffmpeg

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Finished with error: Gradle task `

**Environment**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

Any idea? :)

**Comment by gisinator** [comment]
Switched back to 1.7.8.hotfix4 and now it doesnt work here any more, either. Tried 0.2.8, 0.2.9 and 0.2.10, all preventing building with error above. I'm kinda stuck now, hope someone can help :)

**Comment by gisinator** [comment]
writing 
flutter_ffmpeg: 0.2.8
instead of
flutter_ffmpeg: ^0.2.8

works. But still: Can't build with 0.2.9 or 0.2.10.

I'll keep going with 0.2.8 for now and keep an eye on this issue here :)

**Comment by tanersener** [comment]
Parent project was being republished at that time. Can you try again?

**Comment by gisinator** [comment]
Appreciate your quick response and support.
Yes, now it builds without any issues :)

**Comment by nivas412** [comment]
> Parent project was being republished at that time. Can you try again?

Hi For also having the same issue i was stuck due the this can you please help me

**Comment by nivas412** [comment]
I am getting this errors
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.arthenica:mobile-ffmpeg-com.febbler:4.3.1.

**Comment by Dwayne01** [comment]
i am getting this error please what is the fix for this
